### ISSUE TITLE
Eye stencils

### ISSUE THREAD

**Issue by shakesoda** [bjornbytes/lovr#100]
OpenVR and Oculus APIs both have stencil masks available, and I'm told it can save around 10% off pixel fill. Seems valuable for any canvas which will be used for eye buffers.

**Comment by bjornbytes** [comment]
Two approaches I'm deciding between.

- Flexible.  `lovr.headset.getHiddenAreaMesh` returns a Mesh and you can do whatever you want with it (render to stencil buffer, depth buffer for z prepass, custom hit tests, etc.).
- Fixed.  There's just a conf.lua flag or a lovr.headset getter/setter that is like "hey do the hidden area mesh thing" and it'll render it automatically at the beginning of a frame.

Also unsure if I like using the depth buffer or the stencil buffer for this.

**Comment by bjornbytes** [comment]
I think it needs to at least be exposed (flexible) so that you can use it if you're doing a custom Canvas setup or want to decide between depth/stencil masking.  Might expose it as a pre-rendered Texture, because lovr.graphics.fill is a little easier to work with than a Mesh.

**Comment by bjornbytes** [comment]
Monitoring https://github.com/immersive-web/webxr/issues/463

**Comment by bjornbytes** [comment]
`lovr.headset.getDisplayMask`exists!
