### ISSUE TITLE
Emscripten branch doesn't compile with emcc 1.35.0

### ISSUE THREAD

**Issue by danvdragos** [bjornbytes/lovr#11]
![image](https://cloud.githubusercontent.com/assets/13160957/24075490/49ee8b36-0c25-11e7-85cd-0ee0619e49a9.png)

WebVRDisplay type is not defined. 

Are you using a modified version of emscripten? The type doesn't exist in past versions of emscripten and I didn't find any pull request in the master...

**Comment by bjornbytes** [comment]
I've been working off of an emscripten fork, trying to update it to work with the newest WebVR spec.

Unfortunately, it isn't in a working state right now.  I'll update this issue if anything changes.  Thanks for the interest!

**Comment by bjornbytes** [comment]
The WebVR target is functional now and is on the `webvr` branch.  It compiles against [this branch of my emscripten fork](https://github.com/bjornbytes/emscripten/tree/lovr).  It's still under active development but will be included in the next release.
