### ISSUE TITLE
macOS download fails to load

### ISSUE THREAD

**Issue by prime31** [bjornbytes/lovr#121]
A fresh download of the mac lovr.app fails with a libphysfs.dylib error. The issue seems to be that libphysfs.dylib is referenced by both @rpath/libphysfs.dylib and @rpath/libphysfs.1.dylib. A quick hack to fix it was to duplicate the libphysfs.dylib to libphysfs.1.dylib and then set the @rpath to the new name.

**Comment by bjornbytes** [comment]
Thanks for filing this!  I adjusted the library filenames and uploaded a new macOS build to https://lovr.org/download/mac.  Let me know if you have any more trouble.

**Comment by prime31** [comment]
New build looks good! If you don't mind, here are a few suggestions (feel free to ignore these as well):

- add a link on the front page to download the macOS app. It's very tricky to find the link to it!
- you can remove the `libopenal.1.18.2.dylib` and `libopenal.dylib` files from the bundle. lovr only references the `libopenal.1.dylib` (see output below)
- allow a folder to be dropped on the lovr.app directly. You just need to add the `CFBundleDocumentTypes` below to the Info.plist file and handle the incoming arguments at launch.

```xml
	<key>CFBundleDocumentTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeName</key>
			<string>Folder</string>
			<key>CFBundleTypeOSTypes</key>
			<array>
				<string>lovr-fold</string>
			</array>
			<key>CFBundleTypeRole</key>
			<string>Viewer</string>
			<key>LSHandlerRank</key>
			<string>None</string>
		</dict>
	</array>
```


lovr otool output:

```
lovr:
	@rpath/liblua.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libode.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libopenal.1.dylib (compatibility version 1.0.0, current version 1.18.2)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libopenvr_api.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libphysfs.1.dylib (compatibility version 1.0.0, current version 3.1.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 22.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1454.90.0)
```

**Comment by bjornbytes** [comment]
These are really good suggestions, thanks.

- Added a quick [downloads](https://lovr.org/downloads) page to the navbar to help surface the mac/nightly downloads better.
- The extra versions of OpenAL were removed in that last build (they weren't even symlinks, bah!)
- Supporting additional file extensions on macOS is going to be pretty challenging atm [due to a limitation of glfw](https://github.com/glfw/glfw/issues/1458).  If glfw makes it easier to access the app delegate or LÖVR moves away from glfw then I'll be sure to implement this.

**Comment by prime31** [comment]
Awesome! Thanks for the updates.

I might try to whip up a PR for the third one if I find the workflow requiring the command line to be less than optimal. I believe it can be done via a swizzle or just an NSNotification listener in an obc-c class “load” method.
