### ISSUE TITLE
glTF from Adobe Animate

### ISSUE THREAD

**Issue by kwiksher** [bjornbytes/lovr#139]
I loaded a glTF from Adobe Animate into LÖVE. It was fine on https://gltf-viewer.donmccurdy.com but hardly seen with LÖVE using Animation sample with Scene_1.glb. What is wrong with the code?

```lua
function lovr.load()
  model = lovr.graphics.newModel('Scene_1.glb')
  animator = lovr.graphics.newAnimator(model)
  animation = animator:getAnimationNames()[1]
  assert(animation, 'No animation found!')
  animator:play(animation)
  animator:setLooping(animation, true)
  model:setAnimator(animator)

  shader = lovr.graphics.newShader([[
    vec4 position(mat4 projection, mat4 transform, vec4 vertex) {
      return projection * transform * lovrPoseMatrix * vertex;
    }
  ]], nil)
end

function lovr.update(dt)
   animator:update(dt)
end

function lovr.draw()
  lovr.graphics.setShader(shader)
  model:draw(0, 0, -4, 0.2)
  lovr.graphics.setShader()
end
```

[Scene_1.glb.zip](https://github.com/bjornbytes/lovr/files/3435066/Scene_1.glb.zip)

![2019-07-26_1756 copy](https://user-images.githubusercontent.com/4041539/61941058-b0c16200-afd1-11e9-817a-7a93c184b510.jpg)

**Comment by bjornbytes** [comment]
Hi, there is a bug in `v0.12.0` with the glTF node transform that has been fixed in the `master` branch.  Are you using the `.js` build?  I could make an updated version and send you a project that's rendering the model correctly.  Let me know!

**Comment by kwiksher** [comment]
yes, please send me the updated .js build.  I tried it with emscripten with the master branch but it failed at opengl.c. It was compiled ok with v0.12.0.

Thank you.

**Comment by kwiksher** [comment]
with the latest master, the .js build has been successful but newModel fails to load .glb

<img width="499" alt="2019-07-31_1109" src="https://user-images.githubusercontent.com/4041539/62178437-05732d00-b384-11e9-8880-3165d12efefc.png">

Please look into it.

**Comment by bjornbytes** [comment]
Alright, WebGL is finally working again.  Try this project out:

```lua
function lovr.load()
  model = lovr.graphics.newModel('Scene_1.glb')
  shader = lovr.graphics.newShader([[
    vec4 position(mat4 projection, mat4 transform, vec4 vertex) {
      return projection * transform * vertex;
    }
  ]], [[
    vec4 color(vec4 graphicsColor, sampler2D image, vec2 uv) {
      vec4 c = texture(image, uv);

      if (c.a < .75) {
        discard;
      }

      return c;
    }
  ]])
end

function lovr.draw()
  lovr.graphics.setShader(shader)
  model:animate(1, lovr.timer.getTime())
  model:draw(-.5, 2, -1, .001)
  lovr.graphics.setShader()
end
```

The animation API is more simplified now, using `Model:animate(animationName|animationIndex, timestamp, alpha)`.  I also made the shader `discard` pixels with low alpha to add the "cutout" effect in the glTF material.  Let me know if you have any other issues!

**Comment by kwiksher** [comment]
thank you! It is working good.

<img width="724" alt="2019-08-02_1044" src="https://user-images.githubusercontent.com/4041539/62338249-c7584380-b512-11e9-8a0e-c90a7de4d2fd.png">
