### ISSUE TITLE
Compiling on Linux

### ISSUE THREAD

**Issue by Jcd1230** [bjornbytes/lovr#14]
Hi there,

I just came across LOVR today, and I have to say this project looks awesome! Keep up the good work!

I am a big fan of LOVE and have played around with OpenVR as well, so I just had to try this out.

Unfortunately, it seems LOVR did not compile out of the box on my Linux system (ArchLinux), however it seems to have been just an issue of adding some platform specific stuff to `src/filesystem/filesystem.c`

Here is a patch I made which fixed it for me: [linux_filesystem_patch.txt](https://github.com/bjornbytes/lovr/files/1186146/linux_filesystem_patch.txt)

I also found out (at least on my system) there was a small issue with the PhysFS path `state.fullSavePath` being used in both the source and destination of a `snprintf` call, which seems to be undefined behavior and was causing some weird behavior for me, so that is also fixed in the patch.

Unfortunately, I do not have my HTC Vive set up at the moment so I cannot check to see if all the VR functionality works on Linux, however I did a few tests of just the graphics system and the normal drawing functions seems to work fine in windowed mode at least.

There seem to be some random SegFaults on launch, but that might be due to not having a headset connected, or some Linux specific problems. Not sure.

I will be able to set up my Vive and try it out for real in a week or two, I am very excited to see it working!

I also noticed that you seem to be doing all this work on your own which is incredible, and I would just like to let you know if you needed any help, just add some Issues and I would be more than happy to help out if I can!

Thanks!

**Comment by bjornbytes** [comment]
Hey, thanks for filing this.  I haven't been prioritizing linux support, only because I wasn't sure if there was anyone interested in it.  Given your interest (and how far you were able to get!) I'll make some time to patch up the issues you mentioned and get things working better on linux.  Thanks!

**Comment by bjornbytes** [comment]
Things should be working properly on Arch now.  The instructions in COMPILING.md are also updated.  I've been observing jittery rendering, but this is in any OpenGL VR app, not just LÖVR.  If you run into anything else, don't hesitate to reopen this or file new issues.  Thanks!
