### ISSUE TITLE
can't run projects with macOS version

### ISSUE THREAD

**Issue by undefdev** [bjornbytes/lovr#155]
Hello!
I just wanted to give this a try, but the only thing I get running is the no game screen.
I've downloaded the mac binary from the website and tried to run the hello world, just like I would with LÖVE with `./LÖVR.app/Contents/MacOS/lovr foldername`.
I also tried to zip the main.lua and lovr.conf and run it with the zip, but it didn't work either.

I'm getting some terminal output when running LÖVR, don't know if it's related:
```
Unable to read VR Path Registry from /Users/bla/Library/Application Support/OpenVR/.openvr/openvrpaths.vrpath
```

Thanks for checking it out!

**Comment by bjornbytes** [comment]
Weird, I just tried downloading LÖVR.dmg from the downloads page, installing it to /Applications, and doing

```
/Applications/LÖVR.app/Contents/MacOS/lovr /path/to/project
```

and it was working (`/path/to/project` is a folder with a main.lua file).  I wonder what's going on.

**Comment by undefdev** [comment]
Tried it again (with bash this time to make sure, I usually use fish).
Still getting the no game screen.

![image](https://user-images.githubusercontent.com/13840966/66266757-8c7fce00-e829-11e9-9320-dd8959fd22e6.png)

I'm running MacOS high sierra.

**Comment by jminor** [comment]
When I run it from the command line on my Mac, I have to supply a full path to my project:
`/Applications/LÖVR.app/Contents/MacOS/lovr /Users/jminor/Projects/lovr_test`
If I reference the same project via a relative path, it doesn't work. I don't get the error message you mentioned though.
This is with the Mac build from the downloads page, v0.12.0

**Comment by undefdev** [comment]
> When I run it from the command line on my Mac, I have to supply a full path to my project

You're right, it works with the complete path!

**Comment by bjornbytes** [comment]
I'll be looking into this during the current release process, will post any updates here, hopefully with a fix!

**Comment by bjornbytes** [comment]
Someone is changing the working directory to the resources folder...

```sh
$ sudo dtruss /Applications/lovr.app/Contents/MacOS/lovr . 2> >(grep chdir)
chdir("/Applications/lovr.app/Contents/Resources\0", 0x0, 0x0)           = 0 0
```

**Comment by bjornbytes** [comment]
It was a "feature" of GLFW, fixed in https://github.com/bjornbytes/lovr/commit/505d315c18d3c6e3a405484cc433e069ee711a8e with a CMake flag!
