### ISSUE TITLE
Compiling on OS X (Sierra)

### ISSUE THREAD

**Issue by hellotoby** [bjornbytes/lovr#16]
Following the compilation instructions for Mac OS X, I run into the following cmake error:

`-- Checking for one of the modules 'openal'
CMake Error at /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindPkgConfig.cmake:640 (message):
  None of the required 'openal' found
Call Stack (most recent call first):
  CMakeLists.txt:152 (pkg_search_module)`

Brew has installed openal-soft version 1.18.1.

**Comment by bjornbytes** [comment]
Can you pull and try again?  I've had problems with `openal` vs. `openal-soft` package naming on macOS in the past.  I modified the CMakeLists.txt so that it tries both.

**Comment by hellotoby** [comment]
Getting the following now:

`-- Checking for one of the modules 'openal-soft'
-- Checking for one of the modules 'openal'
CMake Error at CMakeLists.txt:156 (message):
  OpenAL not found.`

**Comment by bjornbytes** [comment]
Does `pkg-config --list-all | grep openal` return anything?  You may need to add a path to `PKG_CONFIG_PATH` for it to be found as well (brew prints out a message warning about this after installing OpenAL).

**Comment by hellotoby** [comment]
Ah, that was it.
I needed to add `export PKG_CONFIG_PATH=/usr/local/opt/openal-soft/lib/pkgconfig`

Thanks for taking the time to help out 👍
