### ISSUE TITLE
Not packaged correctly for MacOS?

### ISSUE THREAD

**Issue by undefdev** [bjornbytes/lovr#165]
Hey,

just wanted to try the latest version, but I get the following error:

![image](https://user-images.githubusercontent.com/13840966/68088707-e8a63400-fe61-11e9-81d9-47f0d9ce1ff3.png)

In the report we get the following details:
```
Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /Users/*/Documents/*/libglfw.3.dylib
  Referenced from: /Applications/LÖVR.app/Contents/MacOS/lovr
  Reason: image not found
```

I'm running MacOS High Sierra.

**Comment by bjornbytes** [comment]
Ok, I reuploaded new versions to the GitHub release page as well as the website (had to clear my cache to get my browser to download the new version).  Sorry about this!

Background: glfw was packaging itself incorrectly because it was configured for older versions of CMake.  I updated glfw to the latest version which fixes it, so this shouldn't happen for future builds.

Thanks again for bringing this to my attention!

**Comment by jonathanperret** [comment]
@bjornbytes FYI, the GitHub-published release still exhibits this issue (this is my first time downloading LÖVR so I'm pretty confident I did not test an older download).

```sh
$ curl -LO https://github.com/bjornbytes/lovr/releases/download/v0.13.0/lovr-v0.13.0-macOS.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2212k  100 2212k    0     0  1755k      0  0:00:01  0:00:01 --:--:-- 2119k

$ hdiutil attach ./lovr-v0.13.0-macOS.dmg
/dev/disk4          	GUID_partition_scheme
/dev/disk4s1        	Apple_APFS
/dev/disk5          	EF57347C-0000-11AA-AA11-0030654
/dev/disk5s1        	41504653-0000-11AA-AA11-0030654	/Volumes/LÖVR

$ otool -L /Volumes/LÖVR/LÖVR.app/Contents/MacOS/lovr
/Volumes/LÖVR/LÖVR.app/Contents/MacOS/lovr:
	/Users/bjorn/Documents/dev/lovr/build/glfw/src/libglfw.3.dylib (compatibility version 3.0.0, current version 3.2.0)
…
```

The version I downloaded from https://lovr.org/downloads does have the fixed library path.

Hope this helps.

**Comment by bjornbytes** [comment]
Okay, it should be working now.  I think there was a problem with the GitHub UI I didn't notice when I first uploaded the new dmg.  Thanks!
