### ISSUE TITLE
Break demo fails on Pixel 2 + Daydream

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#167]
This person saw a failure with the Break demo on Pixel 2 + Daydream + VR Chrome:

https://twitter.com/aaryte/status/1195809179841134592

The console contained:

https://pastebin.com/4aEWVc8p

The error was: `lovr.js:formatted:1100 PANIC: unprotected error in call to Lua API (Temporary vector space exhausted.  Try using lovr.math.drain to drain the vector pool periodically.)`

No Lua stack trace. The demo does do a fair bit of math with temporaries, but why does it only fail on this one specific platform?

**Comment by bjornbytes** [comment]
I think this might be fixed now (on master, unreleased) but I don't know how to test it.

**Comment by mcclure** [comment]
I think the best way to test it would be if at any point there is a build of the lovr website with a Physics demo running with the maybe-fixed master, I can contact back the user who first reported the problem?

**Comment by bjornbytes** [comment]
The new version of Break is now live on the website.
