### ISSUE TITLE
Cylinders can't collide with cylinders

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#181]
lovr.physics cannot collide cylinders with cylinders. This is unintuitive.

Probable cause: Out of the box, ODE cannot collide cylinders with cylinders.  ODE can collide cylinders with cylinders *IF* libccd is enabled. Perhaps libccd is not properly enabled.

Example code demonstrating problem:
[main.lua.txt](https://github.com/bjornbytes/lovr/files/4017898/main.lua.txt)

**Comment by jmiskovic** [comment]
Yes, libccd was not being built by default. This [pull request](https://github.com/bjornbytes/ODE/pull/1) enables it in ODE submodule. It was tested on desktop and works as expected. No changes are needed in lovr code, just checking out this ODE commit. There is probably more work to integrate it into other builds like mobile and emscripten.

**Comment by bjornbytes** [comment]
ode is now building with ccd enabled.

verified that the example pasted here is working (thank you for providing an example!)

it also compiles under emscripten, which is a good sign.

thanks everyone
