### ISSUE TITLE
WAV files

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#182]
Sound sources cannot be wavs, only oggs. If you load a wav as a sound source, it plays silence.

Expected behavior: Wavs should work. If wavs cannot be made to work, they should at least throw an error when you load one as sound source.

Note, I have wav-parsing code just sitting around and would be happy to contribute it to Lovr in a PR sometime before 0.14.

**Comment by bjornbytes** [comment]
Ambisonic sounds also seems to use WAV as a common interchange format, it would be cool to support loading these.

**Comment by mcclure** [comment]
Is there anything unusual about the "ambisonic" wavs (like an unusual number of channels or additional RIFF blocks?)

**Comment by bjornbytes** [comment]
There can be between 2 and 16 channels but it's almost always 4.

And I think there can be additional blocks that describe the ordering of the channels (there are lots of different orderings, hasn't been standardized yet).

So I think SoundData will need to specifically handle this and maybe have an `isAmbisonic` flag.

Still learning about this so my info might be a little off!

**Comment by mcclure** [comment]
I am still interested in creating patches for some of the audio issues if I get time. I will plan on arbitrary channel #.

If you run across a specific link explaining any additional RIFF blocks associated with ambisonic wav I would be curious to see it.

**Comment by bjornbytes** [comment]
i16 and f32 WAVs (using either the regular 16-byte fmt block or the WAVE EXTENSIBLE FORMAT fmt block) are now supported.
