### ISSUE TITLE
Windows build broken on master: .lib missing for msdfgen

### ISSUE THREAD

**Issue by nevyn** [bjornbytes/lovr#184]
I know Bjorn is aware of this; I'm making this issue to track it, and somewhere to keep research for whoever investigates it. 

On VIsual Studio 2019 using "open folder" CMake mode, and master as of 4dc1f6fe57d8bad44e8e709fefeac63c8c68836f, this is the error I encounter:

![image](https://user-images.githubusercontent.com/34791/71786054-a4711480-3007-11ea-989a-9f9deeeb8f32.png)

`Cannot open file lib_msdfgen\msdfgen.lib`

And indeed, in out/build/x64-Debug/lib_msdfgen, there is only a .dll file and some other misc files; no lib file.

It seems public APIs must be marked as dllexported, but a naive attempt to do so just generated countless more errors, so I put it aside for now.

As I only have Windows machines to work on, this is a bit of an issue for me :S I'll try to dig into it some more if opportunity arises.

**Comment by bjornbytes** [comment]
Yeah, it seems like the C API I hacked together should be exporting its symbols:

https://github.com/bjornbytes/msdfgen/blob/lovr/msdfgen-c.h#L16-L24
