### ISSUE TITLE
Expose Headset Views

### ISSUE THREAD

**Issue by bjornbytes** [bjornbytes/lovr#198]
Goals

- Expose the view/projection matrices for headsets.
- Support an arbitrary number of views (e.g. 6-view CAVE, 4-view foveated, 1-view AR).

Details

- A view is a regular pose (3-float position, 4-float orientation) and a field of view (4-float angles).  That's 11 numbers instead of 32 for the view/projection matrices.  Normally there are 2 views.
- Multiview rendering pipeline and Canvas/Camera struct should support N views (at least 6), don't hardcode a "stereo" property.
- Likely just expose view count and per-view pose/fov in the headset module.  It's more of a "display" thing than a "device" thing (it's not like views correspond to eye devices or anything like that).
  - `lovr.headset.getViewCount() --> count`
  - `lovr.headset.getViewPose(index) --> x, y, z, angle, ax, ay, az`
  - `lovr.headset.getViewProjection(index) --> left, right, top, bottom`
  - Naming needs work
- OpenXR does all this really well, it's called "view configurations".
- This is all information that we already have anyway because we need it to render, so it should be relevant for all headset drivers.

Questions

- How do compositor layers/overlays interact with this, if at all?
- Any interactions with foveated rendering?
- Probably want to have some way to pick a view configuration in `conf.lua`.  Can view configurations change over time or is it okay to set it once at startup?  What if the one you want isn't supported?  Should it be a preference list like t.headset.drivers?
- Would anyone actually use any of this

**Comment by porglezomp** [comment]
> * Would anyone actually use any of this

I just ran into this issue because I need to access the FoVs of the camera so I can make a modified projection for rendering effects that extend beyond the screen boundaries, so here's a vote for yes.

**Comment by bjornbytes** [comment]
#206

**Comment by bjornbytes** [comment]
OpenVR and OpenXR and LibOVR expose 4 fov angles, but WebXR exposes a projection matrix and explicitly says that it can include shear so it can't necessarily be decomposed into 4 angles.

https://github.com/immersive-web/webxr/issues/461

Maybe on WebXR `getViewAngles` would return `nil` to indicate that the information can not be reliably exposed.  Or we could switch to exposing a projection matrix.
