### ISSUE TITLE
Document angle units

### ISSUE THREAD

**Issue by porglezomp** [bjornbytes/lovr#200]
Angles are just documented as "an angle." Some experimentation reveals that they are angles in radians—in my opinion it would be good to always say "an angle in radians" in the documentation.

**Comment by porglezomp** [comment]
I'm realizing these two issues might belong on [lovr-docs](https://github.com/bjornbytes/lovr-docs) instead of here, I can re-file them there if that would be better.

**Comment by bjornbytes** [comment]
Gonna make another list of pages to fix:

- `Mat4:fov`
- All the `HingeJoint` functions
- `Mesh:draw`
- `Model:draw`
- `Model:pose`

Let me know if there are any you saw that I missed.

And yes `lovr-docs` is best for docs stuff but it's not a strict rule or anything, here is fine.

**Comment by bjornbytes** [comment]
Fixed!
