### ISSUE TITLE
Multiview shader suggestions

### ISSUE THREAD

**Issue by porglezomp** [bjornbytes/lovr#204]
So far my experience working with multiview shaders, I have to solve two problems.

One, multiview render targets can be of two different types, so if you want to sample them you are forced to write:
```glsl
#ifdef MULTIVIEW
uniform texture2DArray input;
#else
uniform texture2D input;
#endif
```
This could be improved by defining `texture2DMultiview` as the appropriate type.

Second, sampling multiview textures needs different implementations on the two setups. Here are the two implementations I end up using:
```glsl
#ifdef MULTIVIEW
vec4 textureMultiview(texture2DArray tex, vec2 uv) {
  return texture(tex, vec3(uv, lovrViewID);
}
#else
vec4 textureMultiview(texture2D tex, vec2 uv) {
  vec2 newUV = fract(uv) * vec2(0.5, 1.0) + lovrViewID * vec2(0.5, 0.0);
  return texture(tex, newUV);
}
#endif
```
You could also provide an overload/alternate function that lets you specify explicit view IDs.

I think having these small affordances would make multiview shading more accessible, especially since having these features means they'd come with docs :)

**Comment by porglezomp** [comment]
I thought I was being very clever using `fract()` to handle different wrapping modes, but actually that only handles repeating. So I think these need separate sampling functions to implement different wrapping modes, since there's no way to trick the hardware into giving you clamping on the middle of a normal texture.

My version was using `clamp(uv, 0.0, 1.0)` in place of that `fract` to get clamping textures. Needs something fancier for mirrored wrapping.

**Comment by bjornbytes** [comment]
These are great suggestions.  We can use the Postprocessing example as a testcase and fix https://github.com/bjornbytes/lovr-docs/issues/15 in the process of adding these!

**Comment by bjornbytes** [comment]
These are implemented pretty much as described here, for clamp filtering only.
