### ISSUE TITLE
test-release.apk not updating in Oculus Go

### ISSUE THREAD

**Issue by zweihander11** [bjornbytes/lovr#213]
Any reason why this may be happening?
I succeeded installing the file on the Oculus Go system but it gets stuck with an 'Updating' message once I run it.

**Comment by bjornbytes** [comment]
I haven't seen anything like this before.  Does it persist after the headset is restarted?

**Comment by zweihander11** [comment]
Coincidentally the headset was updating while I was installing the .apk 
Eventually it all worked out as it should.

Thank you for replying!
