### ISSUE TITLE
Performance optimizations with LJFFI

### ISSUE THREAD

**Issue by aiverson** [bjornbytes/lovr#215]
Currently all of the graphics calls operate through the Lua CAPI. However, LuaJIT can't trace compile calls involving the Lua CAPI, which comes with a large performance cost. Using the FFI permits JIT compilation and drastically decreases that performance cost. However, using the FFI and having it fail to JIT for whatever reason in the surrounding code has a larger cost than using the C API sometimes.Intuition suggests that the code calling graphics functions is likely to be tight inner loops and otherwise likely to JIT well.

Have their been any benchmarks to validate the performance of the CAPI approach here vs an FFI approach?

Is potential use of the FFI to speed up rendering calls interesting to this project?

**Comment by bjornbytes** [comment]
There have been some experiments with using the FFI in the past.  Notably, vectors used the FFI in previous versions, but it became difficult to get reliable performance with things like cdata memory allocation and garbage collection and JIT compilation (so far I haven't missed cdata vectors).

But yes the FFI definitely results in a large speedup by avoiding the Lua<->C overhead (I think I saw 50-100x when just measuring the function call overhead, but in real projects the overall benefit gets diminished by actual work being done a la Amdahl's Law -- it would be worth doing another round of profiling to verify these statements).

Using the FFI comes with some important downsides though.

- LÖVR works with both LuaJIT and vanilla Lua right now, and vanilla Lua doesn't have an FFI.  (The only platform where LuaJIT doesn't work right now is WebAssembly; I've sketched out an idea where you could maybe polyfill a Lua FFI in emscripten, so maybe we could use LuaJIT everywhere, though it's really nice to have the option of switching back to vanilla Lua).
- To support both Lua flavors, two sets of Lua bindings would need to be supported.  This makes maintenance more difficult and increases the surface area for bugs and inconsistencies.  Optimizing for agility and happiness is an important thing to consider.

The LÖVE project selectively uses the FFI for a small set of functions (mostly random number generation and setting individual pixels in textures), which could be a good approach for frequently used functions like `lovr.graphics.setColor` or `lovr.graphics.clear` or `lovr.math.random`.  I think the best place to start would be profiling, to demonstrate that a real project is running into performance walls that could be alleviated by reducing the C API overhead.

(I've also been playing with the idea of moving the default `lovr.run` implementation into C, but I don't know if this will be difficult or useful yet.)

(Also, you might be interested in [lgf](https://github.com/planimeter/lgf) which is a Lua game framework built entirely on the LuaJIT FFI.)

This is a good thing to bring up, so thanks!

**Comment by bjornbytes** [comment]
Feel free to open new issues or reopen this one if there are more specifics you'd like to discuss.
