### ISSUE TITLE
Pico

### ISSUE THREAD

**Issue by bjornbytes** [bjornbytes/lovr#229]

**Comment by nevyn** [comment]
@bjornbytes Extremely rudimentary but I've at least pulled in the pico SDK and created a headset module for pico  in this branch: https://github.com/alloverse/lovr/tree/pico

I dunno how you wanna keep working, do you want to create a pico branch in this repo that I send PRs to, or set me as collaborator, or..?

I'm also not sure what a good next task for me is... CMake android support maybe? I can't run tup on my windows box, but I need to be able to build an apk to get anywhere at all with this. what'cha think?

**Comment by bjornbytes** [comment]
Perfect!  We can merge commits into a `pico` branch here.

I should be able to get started on tup+android soon.

I recently came across [this project](https://github.com/hunter-packages/android-apk) which might help for CMake side of things?

**Comment by nevyn** [comment]
thanks for that! :) That'll be a great inspiration!

My plan right now is to fork your minimal-android-vr, add a CMakeLists and just try to get it work with the Pico instead of Oculus. That should give me a starting point which I can then move over to lovr.

**Comment by nevyn** [comment]
Some initial progress on just getting cmake android support: https://github.com/bjornbytes/minimal-android-vr/pull/1

**Comment by bjornbytes** [comment]
Pulled in your initial pico branch into origin here.

**Comment by nevyn** [comment]
@bjornbytes This doesn't even remotely work but maybe it's a good starting point: https://github.com/alloverse/lovr/commit/b1446a4ce5ddc186a40ed3cf674ad20c6e9a0340

I'm working in Windows so I bet some stuff need to be adjusted for Mac, too... Currently stuck on 

```
make[3]: Entering directory 'C:/Users/nevyn/Dev/lovr/abuild'
[  3%] Generating native-tools/bin2h, native-tools/bsincgen
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

```

I'm sure it's something trivial, but I need a break :S

**Comment by bjornbytes** [comment]
Pico support is done, finally!

Building a Pico APK works the exact same way as building an Oculus APK, and is supported by both tup and CMake.  The `LOVR_USE_PICO` and `LOVR_USE_VRAPI` options can be used to choose which one to build.  The two flavors require different Java code and XML manifests, but the build system handles all of this.  In many cases the same Lua code can run on both devices unmodified.

Instructions are on the Compiling guide on the website, but here are some notes for convenience:

- An important difference between the two is that the Quest uses Android API level 26 whereas the Pico Neo 2 uses Android API level 27.  Sometimes I'll see confusing dlopen crashes when running the apk if I compiled using the incorrect API levels in either the manifest or the command line.
- Another really important note is that the design of the Pico Native SDK does not currently allow for using singlepass/multiview rendering, so shaders will need to be created with `{ stereo = false }` on there.  Fixing this in the future is really important, for both the performance benefits and the ability to run the same code/shaders everywhere.

I'll be testing more projects on Pico devices and I encourage others to do the same and report any issues!
