### ISSUE TITLE
Text wrap allows always exactly one word to exceed boundary

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#230]
Run this small test program which uses word wrap (I used lovr master git 37d8df478472)

```
function lovr.draw()
	local text = [[
I REALLY WANT A
I REALLY WANT ALIEN
I REALLY WANTA A
I REALLY WANTA ALIEN
]]
	local wrapWidth = 3.2
	local scale = 1/2
	lovr.graphics.setDepthTest()
	-- Draw background box
	lovr.graphics.setColor(0.2,0.2,0.2)
	lovr.graphics.plane("fill", -1 + wrapWidth/2,1 - 5/2,-2, 3.2, 5)
	-- Draw text
	lovr.graphics.setColor(1,1,1)
	lovr.graphics.print(text, -1,1,-2, scale, 0,0,1,0, wrapWidth/scale, 'left','top')
end
```

It looks like this:

<img width="1192" alt="Screen Shot 2020-04-01 at 1 01 34 PM" src="https://user-images.githubusercontent.com/277318/78165287-185d6600-7419-11ea-91c6-c59b33304e59.png">

Expected behavior: The gray area is 3.2 meters wide and the wrap is set to 3.2/scale meters. Therefore I expect all text to be within the gray area.

Problems:
* Exactly one word always reaches past the end of the gray area. It looks like it is choosing to wrap after drawing a word instead of before.
* (How I found this) This creates an effect where it appears to "punish" single-letter words like "A" because they get wrapped despite visibly longer words not getting wrapped (because the A was laid out right after the boundary but the longer word was laid out right before)
* Bonus problem: The documentation https://lovr.org/docs/lovr.graphics.print is unclear for the wrap parameter. It says "The maximum width of each line, in meters (affected by scale)." "Affected by" is vague, I'm not sure what it means.

**Comment by bjornbytes** [comment]
This is fixed.  It had to do with the space character starting juuust before the wrap limit.
