### ISSUE TITLE
Feature request: "Oversize glyphs", floating point MSDF textures (for SDF effects)

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#232]
Been reading the [MSDF paper](https://github.com/Chlumsky/msdfgen/files/3050967/thesis.pdf) (or trying to)  

It has this neat demonstration:

<img width="604" alt="Screen Shot 2020-04-01 at 3 44 44 PM" src="https://user-images.githubusercontent.com/277318/78179763-be1bcf80-742f-11ea-818b-8efd39ad627f.png">

I tried to reproduce this in LOVR

```
local str1n = "An SDF outline effect?"
local str1u = str1n:upper()
local str2n = "An SDF glowing effect!"
local str2u = str2n:upper()
local font, shader, shader2

local defaultVertex = [[
	vec4 position(mat4 projection, mat4 transform, vec4 vertex) {
		return lovrProjection * lovrTransform * lovrVertex;
	}
]]

function lovr.load()
	--font = lovr.graphics.newFont(128)

	-- Outline shader
	shader = lovr.graphics.newShader(defaultVertex, [[
vec4 inColor = vec4(0, 0, 0.5, 1);
vec4 outColor = vec4(1, 1, 0.75, 1);
float median(float r, float g, float b) {
  return max(min(r, g), min(max(r, g), b));
}
vec4 color(vec4 graphicsColor, sampler2D image, vec2 uv) {
  vec3 col = texture(lovrDiffuseTexture, lovrTexCoord).rgb;
  float sdf = median(col.r, col.g, col.b);
  float w = fwidth(sdf);

  // Draw outline-to-nothing transition
  if (sdf < 0.5) {
	float alpha = smoothstep(.4 - w, .4 + w, sdf);
	if (alpha <= 0.0)
		discard;
	return vec4(outColor.rgb, alpha);

  // Draw inside-to-outline transition
  } else {
  	float transfer = smoothstep(.6-w, .6+w, sdf);
  	return mix(outColor, inColor, transfer);
  }
}
]], {} )

	-- Glow shader
	shader2 = lovr.graphics.newShader(defaultVertex, [[
	vec4 inColor = vec4(0, 0, 0, 1);
	vec4 outColor = vec4(1, 1, 0.75, 1);
	float median(float r, float g, float b) {
	  return max(min(r, g), min(max(r, g), b));
	}
	vec4 color(vec4 graphicsColor, sampler2D image, vec2 uv) {
	  vec3 col = texture(lovrDiffuseTexture, lovrTexCoord).rgb;
	  float sdf = median(col.r, col.g, col.b);
	  float w = fwidth(sdf);
	  if (sdf < 0.5) {
	  	float alpha = smoothstep(0, 0.5, sdf);
	  	if (alpha <= 0.0)
			discard;
		return vec4(outColor.rgb, alpha);
	  } else {
		float transfer = smoothstep(0.5, .5 + 5*w, sdf);
		return mix(outColor, inColor, transfer);
	  }
	}
]], {} )
end

function lovr.draw()
	local scale = 1/2
	lovr.graphics.setFont(font)
	lovr.graphics.setDepthTest()
	-- Draw background box
	lovr.graphics.setColor(1,1,1)
	lovr.graphics.setShader(shader)
	lovr.graphics.print(str1n, -1,1+1.0,-2, scale, 0,0,1,0)
	lovr.graphics.print(str1u, -1,1+0.5,-2, scale, 0,0,1,0)
	lovr.graphics.setShader(shader2)
	lovr.graphics.print(str2n, -1,1+0.0,-2, scale, 0,0,1,0)
	lovr.graphics.print(str2u, -1,1-0.5,-2, scale, 0,0,1,0)
end
```
It looks pretty decent!
<img width="1192" alt="Screen Shot 2020-04-01 at 3 46 19 PM" src="https://user-images.githubusercontent.com/277318/78180000-1c48b280-7430-11ea-86fa-e04da23b9556.png">
I can get a slightly better look if I tweak the parameters, but I want to draw attention to some problems that suggest possible LOVR features to support this better:

**Feature request 1: Oversize glyphs**

<img width="1192" alt="Screen Shot 2020-04-01 at 3 41 14 PM" src="https://user-images.githubusercontent.com/277318/78180198-6b8ee300-7430-11ea-9db9-3b81d9e1fc54.png">

The glyph quads are neatly clipped to the glyph, which means the glow haloes get clipped. You can see this most clearly on the "O" and the "G".

Proposed solution: This could be helped if there were an optional way, when creating a Font object, or requesting its glyphs be "oversize". The glyph + padding in the MSDF texture would be larger than necessary, and the quad would also be larger than necessary.

Problems:
- Because glyph quads would surely overlap in this model, these special Fonts would probably not display right unless depth test is turned off.
- Even more awkwardly, if the haloes were large enough the haloes might slightly overlap the halo or the drawn body of another glyph; this would require a more elaborate solution outside the scope of this bug (for example, compositing glyph MSDFs into a bigger MSDF texture— a feature which if it makes sense at all it sounds better suited to a library than building into Lovr).

**Feature request 2: Floating point SDF textures / custom SDF scaling**

This problem is easier to describe if you edit the code up top and uncomment `font = lovr.graphics.newFont(128)`. Then you get this:

<img width="1192" alt="Screen Shot 2020-04-01 at 4 16 23 PM" src="https://user-images.githubusercontent.com/277318/78182769-cd514c00-7434-11ea-813d-d89b0db75af4.png">

This gives the font a higher resolution MSDF and it looks much nicer. But now the glow and outline bands are much much narrower. What if you try to make the bands wider in the shader? Well, you can't. Here's a shader that demonstrates the problem better:

```
local str1n = "Yellow if 0.0 <= SDF <= 1.0"
local str1u = str1n:upper()
local str2n = "Yellow if 0.0 < SDF < 1.0"
local str2u = str2n:upper()
local font, shader, shader2

local defaultVertex = [[
	vec4 position(mat4 projection, mat4 transform, vec4 vertex) {
		return lovrProjection * lovrTransform * lovrVertex;
	}
]]

function lovr.load()
	font = lovr.graphics.newFont(128)

	-- Outline shader
	shader = lovr.graphics.newShader(defaultVertex, [[
float median(float r, float g, float b) {
  return max(min(r, g), min(max(r, g), b));
}
vec4 color(vec4 graphicsColor, sampler2D image, vec2 uv) {
  vec3 col = texture(lovrDiffuseTexture, lovrTexCoord).rgb;
  float sdf = median(col.r, col.g, col.b);

  if (sdf < 0.0) {
  	return vec4(1.0,0.0,0.0,1.0);
  } else if (sdf > 1.0) {
  	return vec4(0.0,0.0,1.0,1.0);
  } else {
  	return vec4(1.0,1.0,0.0,1.0);
  }
}
]], {} )

	-- Glow shader
	shader2 = lovr.graphics.newShader(defaultVertex, [[
float median(float r, float g, float b) {
  return max(min(r, g), min(max(r, g), b));
}
vec4 color(vec4 graphicsColor, sampler2D image, vec2 uv) {
  vec3 col = texture(lovrDiffuseTexture, lovrTexCoord).rgb;
  float sdf = median(col.r, col.g, col.b);

  if (sdf == 0.0) {
  	return vec4(1.0,0.0,0.0,1.0);
  } else if (sdf == 1.0) {
  	return vec4(0.0,0.0,1.0,1.0);
  } else {
  	return vec4(1.0,1.0,0.0,1.0);
  }
}
]], {} )
end

function lovr.draw()
	local scale = 1/2
	lovr.graphics.setFont(font)
	lovr.graphics.setDepthTest()
	-- Draw background box
	lovr.graphics.setColor(1,1,1)
	lovr.graphics.setShader(shader)
	lovr.graphics.print(str1n, -1,1+1.0,-2, scale, 0,0,1,0)
	lovr.graphics.print(str1u, -1,1+0.5,-2, scale, 0,0,1,0)
	lovr.graphics.setShader(shader2)
	lovr.graphics.print(str2n, -1,1+0.0,-2, scale, 0,0,1,0)
	lovr.graphics.print(str2u, -1,1-0.5,-2, scale, 0,0,1,0)
end
```

This looks like:

<img width="1192" alt="Screen Shot 2020-04-01 at 4 24 41 PM" src="https://user-images.githubusercontent.com/277318/78183339-bceda100-7435-11ea-9ca2-a2d4d7db0e59.png">

What is happening here is the top two rows are yellow anywhere the sdf value is 0 <= n <= 1 and in the bottom two rows are yellow anywhere the sdf value is 0 < n < 1. In other words the values are clamped 0..1 and the 0 < n < 1 band is both narrow and gets narrower the higher the font resolution. That makes a lot of sense if we are using the MSDF only for antialiasing but for more complex effects it doesn't work as well.

Proposed solution: If we could request the MSDF texture be a floating point format such as `GL_RGBA32F`, we would have values above 0 and below 1 to play with and could extend the effects as far inward and outward as we liked.

Another (but more complicated to implement) feature that might help here is if Lua users could could put a custom coefficient on the MSDF texture, ie, rescaling the value in some way before writing it into the texture. That would allow a larger "band" to be represented in the 0..1 range of a normal texture, and even with floating point textures might make it easier to write effect shaders which are agnostic to the font size they are working with.

**Comment by bjornbytes** [comment]
- I've needed to increase texture padding in the past for some projects so I'll probably add that.  Likely just `{ padding = integer }` option to the Rasterizer object (and Font which passes it to its Rasterizer).
- Adding the ability to change the texture format seems reasonable, although I can't think of a use for this.  I think if it were added, only a subset of the formats would be able to be supported (e.g. 3/4 channel u8/f32 formats or something).  It looks like newer versions of libmsdfgen let you change the data type and channel count, so that's good.
- I don't understand the need to scale the signed distance field values in the texels themselves.  It seems like it would be possible to scale the signed distance field in the shader after it's sampled from the texture, giving you the ability to change the inner/outer glow size, falloff, bias/spread, etc. etc. without changing anything about the data in the SDF texture.  Doing it in the shader seems preferable to me because it's a lot more flexible and might avoid some clamping/precision issues.  If this seems incorrect, let me know.

**Comment by mcclure** [comment]
"I don't understand the need to scale the signed distance field values in the texels themselves. It seems like it would be possible to scale the signed distance field in the shader after it's sampled from the texture"

At the moment, to my understanding, we are using integer formats for the textures, which means the texels are clamped at 0-256. Most of the image winds up in fact clamped to either 0 or 256. If there was an ability to request float formats, then I agree with you we would not need the ability to scale and as you say could do that step in the shader.

**Comment by bjornbytes** [comment]
Made some changes that hopefully address everything here

- The font texture now uses a floating point format (`rg11b10f`)
- New font settings:
  - `padding` -- the number of padding pixels for glyphs (default is 2, spread / 2 is a good default)
  - `spread` -- I think this is the number of pixels that the SDF takes to get to 1 (default is 4.0)
- In addition, the font shader uses a much more accurate method of doing antialiasing, leading to more crisp/legible glyphs.
