### ISSUE TITLE
Vive Trackers

### ISSUE THREAD

**Issue by Rucoon** [bjornbytes/lovr#235]
In the version 0.12 change log I can see that support was added for Vive trackers but there is no mention of how to access them in the documentation. Is it just a device name I am missing?

**Comment by bjornbytes** [comment]
Hey, sorry about the confusion.  Trackers were originally supported as controllers but then they broke when LÖVR upgraded to use SteamVR Actions in v0.13.0.  A few people have asked about trackers lately so it seems pretty important to fix this.  This issue can stay open until they are added back.

**Comment by crertel** [comment]
I've got trackers I can test with if that's the limiting factor. Would that help?

**Comment by bjornbytes** [comment]
I think so!  My understanding is that someone with trackers would need to set up input bindings using the SteamVR UI, and then share the JSON binding file.  Trackers aren't available for me in the UI.

Those could be integrated into the JSON files in `src/resources`, and then LÖVR could add back the tracker devices and hook them up to those bindings.  The tracker devices would be either `tracker/1` through `tracker/4` or more semantic ones like `shoulder/left`, `waist`, etc., depending on how SteamVR does it.

**Comment by bjornbytes** [comment]
#335 adds support for the 12 different roles that trackers can be assigned to.  This allows for full body tracking, mixed reality, and tracked keyboard stuff using vive trackers.
