### ISSUE TITLE
Plane primitive rendering issues with standard shader

### ISSUE THREAD

**Issue by jmiskovic** [bjornbytes/lovr#242]
When using "standard" shader, the plane primitive is either always rendered black, or flickers in color. I was able to test on Oculus Quest, and on desktop with similar results.

The smallest example to reproduce is this:
```
function lovr.load()
  shader = lovr.graphics.newShader('standard')
  lovr.graphics.setBackgroundColor(0.5, 0.7, 1)
end

function lovr.draw()
  lovr.graphics.setShader(shader)
  lovr.graphics.setColor(1, 0.8, 0)
  lovr.graphics.plane('fill', 0, 1, -5,   2, 2,   lovr.timer.getTime(), 1, 0, 0)
end
```

This sample flickers on Quest, and shows black color on desktop. When using "unlit" shader, the plane is rendered correctly.

**Comment by bjornbytes** [comment]
I think this might be a symptom of "the standard shader is working as expected but the results are weird due to its complexity" plus maybe "using mediump floats on OpenGL ES has precision issues".  Still needs some investigation, but improving the defaults and documentation might be the fix here.

**Comment by bjornbytes** [comment]
I'm going to close this for now because I don't think there is a clear action to take to resolve it.  I do think it is a symptom of something that can be improved though.
