### ISSUE TITLE
lovr.headset.getHands() returns an empty table for Touch controllers with OpenVR

### ISSUE THREAD

**Issue by plabuda** [bjornbytes/lovr#246]
My setup: Oculus Rift CV1 + Touch Controllers. 
My problem: Neither Lovr 0.13 nor yesterday's nightly can recognize the controllers. 

Official example:
`function lovr.update(dt)
  for i, hand in ipairs(lovr.headset.getHands()) do
    print(hand, lovr.headset.getPose(hand))
  end
end`

Does not print anything. My own test:

`function lovr.draw()
  hands = lovr.headset.getHands() 
  lovr.graphics.print(#hands , 0, 1.7, -3, .5)
end`

Draws a zero.

Other apps see the controllers without problem. I even launched the project from within Steam VR, no luck. There seems to be one element returned by SteamVR when the headset isn't connected, but I did not investigate further. I know that Oculus app updated a few days ago - maybe it's connected?

[Edit 1 - I found other builds. Controllers are detected in 0.11 I'll keep looking for the version that broke]
[Edit 2 - 0.12 is also working. It seems that the bug was introduced when switching from GetControllers API to GetHands.]

~~If older builds are available for download somewhere I can try to see when it stopped working. (if it's not working on any it may be an issue on my side) I'll also try compiling the project myself to debug it on the C side.~~

**Comment by bjornbytes** [comment]
Things we've tried/noted:

- Retrieving the action handle succeeds, so OpenVR is at least aware of the action.
- `actionData.pose.bPoseIsValid` and `actionData.bActive` are always false for pose actions on touch controllers.
- Both pose and button inputs fail to return data.
- Tried removing app_key in the bindings, which didn't help.

Other things to try:

- Checking the SteamVR logs (Steam VR Menu -> Developer -> Web Console OR /path/to/Steam/logs/vrclient_lovr.txt)
- Regenerating the bindings using the SteamVR UI, noting any differences.
- Upgrading OpenVR

**Comment by bjornbytes** [comment]
Pushed something which may help: There was an error message in the Steam logs about the menu button on touch controllers, so I removed the menu button from the touch bindings.

**Comment by plabuda** [comment]
I will confirm tomorrow if this helped.

**Comment by bjornbytes** [comment]
We were able to track (heh) this down to mixed slashes in the OpenVR action manifest path, which ultimately came from mixed slashes in the save directory.  Fixed in c423b12
