### ISSUE TITLE
json can't be found when requiring

### ISSUE THREAD

**Issue by jumpsplat120** [bjornbytes/lovr#248]
If you follow the instructions found on https://lovr.org/docs/json , you run into an error with most current version of LOVR; v.0.13.0.

`local json = require 'json'`

![image](https://user-images.githubusercontent.com/8318935/80538783-29878d00-895b-11ea-8967-223c424be374.png)

**Comment by bjornbytes** [comment]
It should be `require 'cjson'` now, just updated those docs.
