### ISSUE TITLE
Missing resize callback

### ISSUE THREAD

**Issue by Papaew** [bjornbytes/lovr#250]
In `love.conf()` you can add parameter `t.window.resize` and window will be able to resize manually by user. And it’s supposed that you need callback to handle  this functionality.
Can you add `lovr.resize(width, height)` callback please?

**Comment by bjornbytes** [comment]
`t.window.resizable` already exists on the master version.

I'll add a `lovr.resize` callback soon.

**Comment by Papaew** [comment]
Thanks~

**Comment by bjornbytes** [comment]
Note: lovr.resize is done now
