### ISSUE TITLE
No warning/error given if you try to load an animation with greater than 48 bones.

### ISSUE THREAD

**Issue by ForestCSharp** [bjornbytes/lovr#252]
I tried to load a skinned/animated model with greater than 48 bones and I'm left with a crash. Upon debugging/looking at the code, it seems to be a read-access violation related to the bone limit, but I'm given no warning when using the prebuilt binaries re: this bone-limit.

**Comment by bjornbytes** [comment]
Thanks for filing this.  Are you able to share an example model with more than 48 bones in a skin?  This would make it a little easier to test a fix.  Thanks!

**Comment by ForestCSharp** [comment]
Here's a little test project. I got this to work by upping that MAX_BONES define (in shaders.c and ModelData.h). With that hacky fix, I also saw that if you make MAX_BONES too high, the shader can fail to compile with this:

![image](https://user-images.githubusercontent.com/7401287/80890798-4f779f00-8c85-11ea-86d7-2c3b6eaace66.png)

I imagine the more fullproof fix is to send bones via a storage buffer object and also send a bone_count uniform.

[anim_crash.zip](https://github.com/bjornbytes/lovr/files/4568665/anim_crash.zip)

**Comment by bjornbytes** [comment]
Yep exactly, 48 was chosen because it's around as high as we can go with a uniform array (on lowest-common-denominator GL implementations).  Using a buffer object internally would be way way better here.

Thanks for the test case!

**Comment by bjornbytes** [comment]
This is fixed now, there's at least an error message when creating a Model from a ModelData with too many joints in a skin.  However, for now the 48 bone limit is a hard cap unfortunately until the switch to buffers can be made.

**Comment by bjornbytes** [comment]
The documentation now also mentions the 48 joint limit.

**Comment by bjornbytes** [comment]
The gpu branch supports 256 joints per skin now, with the ability to expand to 65536 or more if needed.
