### ISSUE TITLE
Get position and pose of tracked objects that aren't hands or heads

### ISSUE THREAD

**Issue by aiverson** [bjornbytes/lovr#255]
I'm trying to make some utilities in Lovr. In particular, I want to display the location, pose, and tracking frustums of the lighthouse basestations in VR so I can easily visualize where they overlap, and where is untracked because of occlusion or orientation.

I looked for a function in the API docs, but don't see a binding for it. It's available in the OpenVR C++ api. Is it missing in OpenXR and therefore nonportable? Is it there and I'm blind?

If it's not there, should I write it, and where should I put it?

**Comment by bjornbytes** [comment]
Just added a [commit](https://github.com/bjornbytes/lovr/commit/0be36da3340ccdd774fceaa08f2426f46b659104) that adds 4 new devices `beacon/1` through `beacon/4` that work with `lovr.headset.getPose`.

Here's a test app:

```lua
function lovr.draw()
  for i = 1, 4 do
    local beacon = 'beacon/' .. i
    if lovr.headset.isTracked(beacon) then
      lovr.graphics.cube('fill', mat4(lovr.headset.getPose(beacon)):scale(.08))
    end
  end
end
```

I think LibOVR also exposes their tracking camera positions, so this could also potentially be implemented there, but I can't test that driver easily.

Been wanting to add these but I wasn't sure if it was something anyone would use.
