### ISSUE TITLE
Quality-of-life physics API improvements

### ISSUE THREAD

**Issue by jmiskovic** [bjornbytes/lovr#256]
It is currently tedious to work with physical objects, because of boilerplate code needed for each collider: create collider > store in table > set parameters > render each frame. Here are some suggestions to improve the flow.

1) The collider and shape functions could return the input object, to allow chaining of operations. Compare before and after sample code.
```
local ball = world:newSphereCollider(0,0,0, 1)
ball:setRestitution(0.5)
ball:setFriction(0.7)
ball:setTag("obstacle")

world:newSphereCollider(0,0,0, 1):setRestitution(0.5):setFriction(0.7):setTag("obstacle")
```

2) A new function for physics world that returns a read-only list of colliders. Currently both LOVR physics and user have to keep separate tables of colliders, that need to be synchronized when colliders are created/destroyed. This makes sense for special objects that require periodic attention, but most geometry is just created and drawn. A function like `world:getColliders()` to be used with `ipairs` would be ideal for drawing.

3) An optional default renderer for shapes. While this is already possible to implement on Lua side, the C iteration through collider/shapes list would significantly reduce crossing the Lua/C boundary.

Proposal from Lua side is:
```local ball = world:newSphereCollider(0,0,0, 1)
ball:setDefaultRenderer(true)
ball:setUserData({color={1,0,0})  -- define color or material
```

Even just one of these suggestions would make working with physics API less of a chore.

**Comment by bjornbytes** [comment]
Definitely want to add 2) as `World:getColliders`

I think 3) is tricky because it involves cross-pollination between modules which I try to avoid.  Is the intent to render wireframes for all the shapes/colliders and use it for quick debugging?  Something like `World:draw` that renders every collider might be doable for that.  I would implement it in l_physics so that the core physics module doesn't depend on the graphics module.

Doing 1) would create an inconsistency in the way setters work (people expect chaining everywhere) so I'd kinda want to have it in a Lua library, where it can be more expressive anyway (like metatables or accepting a table of options in addition to chaining).

**Comment by bjornbytes** [comment]
Added `World:getColliders`, closing this for now but the other improvements can still be discussed

**Comment by jmiskovic** [comment]
Perfect. Here's quick and dirty way to render colliders.

```function drawCollider(collider)
  local shape = collider:getShapes()[1]
  local shapeType = shape:getType()
  local x,y,z, angle, ax,ay,az = collider:getPose()
  -- draw shape at collider's position with correct dimensions
  if shapeType == 'box' then
    local sx, sy, sz = shape:getDimensions()
    lovr.graphics.box('fill', x,y,z, sx,sy,sz, angle, ax,ay,az)
  elseif shapeType == 'sphere' then
    lovr.graphics.sphere(x,y,z, shape:getRadius())
  elseif shapeType == 'cylinder' then
    local l, r = shape:getLength(), shape:getRadius()
    local x,y,z, angle, ax,ay,az = collider:getPose()
    lovr.graphics.cylinder(x,y,z, l, angle, ax,ay,az, r, r)
  elseif shapeType == 'capsule' then
    local l, r = shape:getLength(), shape:getRadius()
    local x,y,z, angle, ax,ay,az = collider:getPose()
    local m = mat4(x,y,z, 1,1,1, angle, ax,ay,az)
    lovr.graphics.cylinder(x,y,z, l, angle, ax,ay,az, r, r, false)
    lovr.graphics.sphere(vec3(m:mul(0, 0,  l/2)), r)
    lovr.graphics.sphere(vec3(m:mul(0, 0, -l/2)), r)
  end
end```
