### ISSUE TITLE
Starting with console on Windows doesn't work without .bat file

### ISSUE THREAD

**Issue by codecat** [bjornbytes/lovr#258]
If I start lovr via the command line like this:
```
lovr --console "D:\Games\Test"
```
Then it will run the game, but not attach the standard output to the command prompt, it immediately returns while still running the game:
![image](https://user-images.githubusercontent.com/136534/81576384-7da55f00-93a8-11ea-8059-58b146842c18.png)

But when I use the `lovrc.bat` file, it works fine, although it's executing the exact same line:
```
lovrc "D:\Games\Test"
```
![image](https://user-images.githubusercontent.com/136534/81576495-9c0b5a80-93a8-11ea-82f4-f967fec7d7ca.png)

I'm not entirely sure what's going on here, perhaps something with the standard output not being attached or something.

Additionally, another idea is that running with `--console` in this context could create its own console (with [`AllocConsole`](https://docs.microsoft.com/en-us/windows/console/allocconsole) or such), which also allows external tools to run lovr with a console without passing it through `cmd /c` first.

**Comment by bjornbytes** [comment]
Do print statements show up when running with `--console`?  I think the prompt showing up immediately is a quirk of the windows console.  I had trouble working around that.

I remember using `AllocConsole` when trying to get this to work but I don't fully understand the suggestion.  If it still shows stdout when running from both cmd and explorer and makes it a little bit easier to run LÖVR from other tools (like editors?), then that seems good.

**Comment by codecat** [comment]
Yes, `print` statements do show up, but as you say it's a bit weird.

When doing `--console` from outside of a cmd, the output is lost entirely if stdout isn't redirected, which is actually my use case; I'm adding support for LÖVR in [Loveman](https://nimble.itch.io/loveman), which has a "Start with console" button.

I suppose this is why LÖVE has a separate `lovec.exe` using the console exe type. 😅

**Comment by bjornbytes** [comment]
In ebc69c6c93026c55ca6133b5baf4384987f027aa `AllocConsole` is used if `AttachConsole` fails, let me know if that helps!

A separate `lovrc.exe` could be used as a last resort but it would be great to avoid shipping 2 nearly-identical executables if it can be helped.

**Comment by codecat** [comment]
Just tried it on nightly - this works fantastic, thank you for the quick fix! 🎉
