### ISSUE TITLE
Use minimp3 to implement MP3 loading

### ISSUE THREAD

**Issue by codecat** [bjornbytes/lovr#259]
The library is pretty straight forward: https://github.com/lieff/minimp3

I was originally going to implement it as an external module for lovr, but since lovr doesn't seem to have a `liblovr` or anything, it's kinda difficult to create an `AudioStream` from it.

I'd love to help implement this if possible! I think it should be pretty straight forward, however I do wonder how the API should look - how would it distinguish whether data is mp3 or ogg? If there's a filename it could just check the file extension, but if it's a `Blob` it would be a bit more involved - perhaps by adding a string that says `'ogg'` or `'mp3'`?

**Comment by bjornbytes** [comment]
I'm currently working on adding support for WAV (#182), once that's done it should be easier to add support for mp3.

I think file type detection would be similar to the way images work, which is just trial and error... though most formats have some sort of header which makes it possible to quickly reject stuff.

**Comment by codecat** [comment]
Oh cool, looking forward to that! That issue is labeled as "help wanted", is that still the case?

**Comment by bjornbytes** [comment]
Oh, I guess not, I was going to do it while tackling some other audio work so I'll remove that label, thanks!

**Comment by bjornbytes** [comment]
This feature was just merged into the dev branch and will be present in the next release
