### ISSUE TITLE
Disabling headsets for developing 3D applications cause blackscreen

### ISSUE THREAD

**Issue by Rabios** [bjornbytes/lovr#260]
Hi Everyone!!!
In fact i liked LOVR but unfortunately i don't have VR Headsets
So i tried to do it in 3D and i faced a problem that is a blackscreen,For no reason maybe

Here is conf.lua
```lua
-- Written by Rabia Alhaffar in 17/May/202
-- A script to disable headsets and setting MSAA and VSync already
-- Use this in case you are NOT developing VR game,Just 3D game
local title = "GAME"
function lovr.conf(t)
    t.modules.headset = false
    t.window.fullscreen = true
    t.window.msaa = 8
    t.window.title = title
    t.window.vsync = 1
    t.window.hotkeys = true
    t.window.icon = nil
    t.window.height = 768
    t.window.width = 1366
    t.math.globals = true
    t.modules.audio = true
    t.modules.data = true
    t.modules.event = true
    t.modules.graphics = true
    t.modules.math = true
    t.modules.physics = true
    t.modules.thread = true
    t.modules.timer = true
    t.math.ffi = true
end
```

Also here is main.lua,Main code(Same from examples in the official website)
```lua
function lovr.draw()
    local angle = lovr.timer.getTime()
    lovr.graphics.cube('fill', 0, 1.7, 0, 0.5, angle)
end
```

Which give me a blackscreen,As shown below
![Screenshot (105)](https://user-images.githubusercontent.com/47897019/82137482-422fe800-9821-11ea-98a8-01131b488941.png)

Can anyone tell me what is the problem here,What is going on?
Have i did something wrong,Or it's a bug needed to fix?

**Comment by Rabios** [comment]
![Screenshot (105)](https://user-images.githubusercontent.com/47897019/82137386-15c79c00-9820-11ea-8a29-f45c1eb8be91.png)

**Comment by jmiskovic** [comment]
The cube is being rendered, but it is not currently in viewport. You have placed cube straight above the camera, and not in front of it. The coordinate system is +X right, +Y up, and -Z forward. When headset is `false`, viewport is at origin position looking down the Z axis.

Try this:
```
function lovr.draw()
    local angle = lovr.timer.getTime()
    lovr.graphics.cube('fill', 0, 0, -2, 0.5, angle)
end
```

**Comment by Rabios** [comment]
@jmiskovic Ah sorry,Thank you!!!

**Comment by Rabios** [comment]
@jmiskovic And...Can i ask you to write a note about that in the official website,Just for beginners?(I'm fine)

**Comment by bjornbytes** [comment]
Added a note to the Tips section of the Getting Started guide.
