### ISSUE TITLE
Command line

### ISSUE THREAD

**Issue by TheKnarf** [bjornbytes/lovr#271]
It's most natural for me to run it from the command line, like I would do with say a Python script or a Node script.

```
python main.py # Starting a python script
node main.js # Starting a node script
lovr main.lua # This is the syntax I would want to start a lovr script / project
```

No after installing the mac app of lovr I was able to do something similar by running:

```
/Applications/LÖVR.app/Contents/MacOS/lovr .
```

This works but is in part a bit lacking, there are a few things I would have wanted:

1. To have a lovr command in my path instead of calling into the `.app`

_I can sorta fix this by adding an alias or wrapper script, however I would rather have it fixed in combination with the next point._

2. To have a [homebrew](https://brew.sh/) package for lovr

3. To extend the lovr command with other sub commands and parameters. F.ex it would be natural to have a `lovr --help` or `lovr help` command. I do see that lovr already has some support for this as it do support `--version`.

4. Maybe some kind of `build-apk` command (I'm developing on a mac and testing on an oculus quest).

**Comment by bjornbytes** [comment]
There isn't really a technical reason why `lovr file.lua` isn't possible.  There are some mild design considerations, like whether main.lua's folder would still be treated as the "source archive" or if it's assumed that main.lua is a self-contained project source.

I personally don't have much knowledge or interest in setting up package manager stuff, but I would welcome others to do so.

I think `--help` is a good idea, especially if there are more commands.

I'm definitely planning on having some sort of CLI command to export a project to various platforms.  It would just need to create a zip of the directory and then fuse it to the executable, emit a static HTML page, or call into an android tool to add it to an apk.  There's also potential for the CLI to sync project files to an apk already on the device for quick android iteration.

**Comment by bjornbytes** [comment]
There isn't really a clear task here so I'm going to close this, can continue discussing stuff though.
