### ISSUE TITLE
Severe flickering on 0.13/nightly

### ISSUE THREAD

**Issue by oilboi** [bjornbytes/lovr#278]
Trying multiple draw calls results in extreme flickering with the latest builds

**Comment by bjornbytes** [comment]
This issue is widespread; if anyone has a simple repro they can paste here that would help.  I've seen it from time to time in my own projects but it's intermittent and somewhat hard to reproduce.

**Comment by bjornbytes** [comment]
Buffer-related flicker bugs should be fixed now, please reopen this if you still see them!

**Comment by bjornbytes** [comment]
Ok this should finally be fixed in `61e9c7`
