### ISSUE TITLE
Thread:wait() crashes on Windows

### ISSUE THREAD

**Issue by nevyn** [bjornbytes/lovr#285]
![image](https://user-images.githubusercontent.com/34791/92995558-f65a2a80-f504-11ea-9c64-53f1b7f601ad.png)

Repro:

```
function lovr.load()
  thread_code = [[
    print("starting thread")
    local lovr = { thread = require 'lovr.thread' }
    local channel = lovr.thread.getChannel("test")
      channel:push(1)
    print("ending thread")
  ]]

  channel = lovr.thread.getChannel('test')
  thread = lovr.thread.newThread(thread_code)
  thread:start()
  message = channel:pop(true)
  thread:wait()
  print("ok done")
```

It looks like it could be a race? When breaking in thrd_detach, `thr` is a valid pointer when entering the function, but slightly after, it's a broken handle.

Removing the thread:wait and it doesn't crash anymore; but then I also can't be sure the thread has really finished. And also `lovrThreadDestroy` isn't called so the object leaked??

**Comment by bjornbytes** [comment]
This looks like a platform difference / bug in the tinycthread library we're using:

```c
int thrd_join(thrd_t thr, int *res)
{
#if defined(_TTHREAD_WIN32_)
  DWORD dwRes;

  if (WaitForSingleObject(thr, INFINITE) == WAIT_FAILED)
  {
    return thrd_error;
  }
  if (res != NULL)
  {
    if (GetExitCodeThread(thr, &dwRes) != 0)
    {
      *res = (int) dwRes;
    }
    else
    {
      return thrd_error;
    }
  }
  CloseHandle(thr);
#elif defined(_TTHREAD_POSIX_)
  void *pres;
  if (pthread_join(thr, &pres) != 0)
  {
    return thrd_error;
  }
  if (res != NULL)
  {
    *res = (int)(intptr_t)pres;
  }
#endif
  return thrd_success;
}
```

On the pthread path, `res` is checked for NULL, whereas on the windows path `res` gets written to unconditionally.  Right now we're passing in NULL for `res` when calling `Thread:wait` -> `lovrThreadWait` -> `thrd_join`.  Should either pass in a pointer to an unused value or modify tinycthread to nullcheck res on windows (I'm going to try to implement the latter).

**Comment by bjornbytes** [comment]
Originally I left a comment about `res` being NULL but that wasn't correct.  It looks like both `thrd_join` and `thrd_detach` call `CloseHandle` on windows, so the thread handle is accidentally getting cleaned up twice which throws an error in a debugger.  Going to try to modify `thrd_join` to not call `CloseHandle` soon.

**Comment by bjornbytes** [comment]
This should be fixed now!
