### ISSUE TITLE
Keyboard events on Android eventually crash the app

### ISSUE THREAD

**Issue by jmiskovic** [bjornbytes/lovr#286]
Keyboard events (keypressed, keypressed, textinput) are correctly emitted but they crash the application after typing for some time.

After adding a key counter, I noticed that the crash happens on keystroke number 254. It is reliably reproducible on Oculus Quest.

This line from attached [logcat.log](https://github.com/bjornbytes/lovr/files/5214384/logcat.log) seems to indicate a JNI reference problem:

`Abort message: 'art/runtime/indirect_reference_table.cc:132] JNI ERROR (app bug): local reference table overflow (max=512)'`

**Comment by bjornbytes** [comment]
This is fixed now

**Comment by jmiskovic** [comment]
Can confirm it works, thanks!
