### ISSUE TITLE
Enable use of system OpenXR headers/loader on Linux

### ISSUE THREAD

**Issue by Wallbraker** [bjornbytes/lovr#295]
As the topic says, it would be good to enable the use of the system packages for OpenXR on Linux. Similar to `LOVR_SYSTEM_OPENAL`. The OpenXR headers and loader is available in [Debian][1] as packages in the official repository. As well in [Ubuntu][2] in 20.10. On top of that there is even a [PPA][3] that should have even more up to date packages.

[1]: https://packages.debian.org/bullseye/libopenxr-dev
[2]: https://packages.ubuntu.com/groovy/libopenxr-dev
[3]: https://launchpad.net/~monado-xr/+archive/ubuntu/monado

**Comment by bjornbytes** [comment]
Thanks for the package info, working on (testing) this in #298
