### ISSUE TITLE
More MaterialTextures?

### ISSUE THREAD

**Issue by mahalis** [bjornbytes/lovr#30]
It’d be helpful to have a few more texture slots available in Material—just having “diffuse” and “environment” is pretty limiting. Assuming most folks these days will use a nominally PBR shading model, the most useful additions would be:

- roughness
- metalness
- emissive

The default material doesn’t need to do anything with these, of course, but having them available would make it possible for people to set up their own more advanced materials.

**Comment by bjornbytes** [comment]
That's funny, I started thinking/working on this a couple of days ago.  I agree, the current selection is really limited and in general materials shouldn't be "fixed function".  Here's a potential API:

```lua
-- Specify a format for materials
material = lovr.graphics.newMaterial({
  metalnessRoughness = 'texture',
  environment = 'cubemap',
  bumpMap = 'texture',
  diffuse = 'color'
})

-- Or, pass in your shader and we extract the format from its uniforms
material = lovr.graphics.newMaterial(pbrShader)

material:setProperty('metalnessRoughness', texture)
```

I'm not sure how this would impact model loading, I guess they would just try to read as many properties from the asset as they can and build up their own material format.  The names for the properties would probably be prefixed with `lovr` and match whatever is used in default shaders.

It also might be simpler to keep the set of properties completely fixed and just add more of the commonly used ones.

**Comment by mahalis** [comment]
Either of those options makes sense to me—the automatic extraction sounds useful, though it might get complicated with materials that have different texture samplers in their vertex and fragment shaders (e.g. a displacement map in the former vs. standard textures in the latter).

**Comment by bjornbytes** [comment]
Materials and models now support emissive, metalness, roughness, occlusion, and normal textures.
