### ISSUE TITLE
Scene graph

### ISSUE THREAD

**Issue by newobj** [bjornbytes/lovr#304]
What's considered the right way to create a hierarchical scene graph in lovr (e.g. where a parent's transform affects its children?) Joints? Am I missing some other parenting facility? If it's joints, do I want a distance joint? What's optimal for a completely static relationship? Thanks!

**Comment by bjornbytes** [comment]
Try using `lovr.graphics.push` and `lovr.graphics.pop`.  You can give each object a `Mat4` for its local transform and keep track of its children, and then iterate over the objects starting from the root.  It would look something like this:

```lua
function object:draw()
  lovr.graphics.push()
  lovr.graphics.transform(self.localTransform)
  for i, child in ipairs(self.children) do
    child:draw()
  end
  lovr.graphics.pop()
end
```

This will nest all of their transforms during rendering, just like a traditional scene graph.  From there you can customize it further to fit your needs.  Also, getting an object's global transform would be possible by multiplying its local transform by the local transforms of its parents.

**Comment by newobj** [comment]
Thank you! Sorry to re-open, one more question:

If I want to find objects under the cursor (via their colliders, and this is a desktop app, not VR), do you recommend taking a transform based approach, or using joints in that case?

**Comment by bjornbytes** [comment]
I think a transform-based approach works here too.  There are a few code examples for mouse-picking in Slack, but I think the basic approach is to use the inverse of the projection/view/transform matrix to get a ray for the mouse, and then it can be used with `World:raycast` to get a collider.
