### ISSUE TITLE
arg[0] is nil on Android

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#310]
This is not a blocker because you can get the value of `arg[0]` from lovr.filesystem.getSource(). However, it is inconsistent, so I would consider that bad. My expected behavior is code written for PC works without changes on Android.

I can't remember where on lovr.org the docs for `arg` are.

**Comment by bjornbytes** [comment]
This behavior is consistent with other projects running in fused mode (fused exe on windows, .app on macOS).
