### ISSUE TITLE
getIdentity() doesn't return a value until setIdentity() is called on Android

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#311]
When you call getIdentity() on Android, it returns nil. If first you call setIdentity() with a garbage string argument (it has to be a string, but it's discarded), getIdentity will return the correct Android identifier. This is obviously silly…

**Comment by bjornbytes** [comment]
This matches the behavior of other platforms, but given that the identity is handled differently on Android I think it's okay to change.

**Comment by mcclure** [comment]
Well, should the other platforms change? i could imagine doing something like
```
local identity = lovr.filesystem.getIdentity()
lovr.filesystem.setIdentity("TempIdentity")
-- Bunch of stuff
lovr.filesystem.setIdentity(identity)
```
Does this, for example, work if getIdentity() returns nil when it has its default value?

**Comment by bjornbytes** [comment]
On desktop platforms, `getIdentity` should return `nil` if the identity hasn't been set yet.  There is some expectation that if `getIdentity` returns a value, then `getSaveDirectory` will return a valid writable path usually derived from `getAppdataDirectory` and the identity.  Before `setIdentity` is called, this can not be guaranteed.  There is also no default identity from `lovr.filesystem`'s point of view (there is only a default value for `t.identity` in `conf.lua`), so it would not know what to return.

**Comment by bjornbytes** [comment]
Hm, there are issues with setting up the save path earlier on Android because of the `precedence` argument.

- If the identity was initialized at startup, then a call to setIdentity would not mount the save directory.
- The save directory can't be mounted at startup because we don't know what precedence to use.
- Maybe setIdentity could check `savePath` instead of `identity` to see if it needs to run.  That would allow Android to set up the identity earlier but still set up the save directory when setIdentity is called.  This would break the invariant of "`getIdentity` returns the name of the mounted save folder where writes will go" but that might be okay.

**Comment by mcclure** [comment]
This is all I know:

- For Lodr to work on Android, I need the application identifier. Other Android-related features may need the application identifier as well. (And if you ever support iOS or MacOS, you will occasionally need the application identifier [there called the application Bundle Identifier] there as well.) (…and if you ever support UWP, then you may occasionally need an application identifier [there called the AUMID] **there** as well.)
- In 0.14, you removed the application identifier from lovr.filesystem. My understanding was you did this because you concluded the Identity was the same as the application identifier.
- I don't care either way how Identity works on Android. However, **if** the Identity is ontologically distinct from the application identifier, then I need a separate function for the application identifier.
- [This is what Lodr is doing right now](https://github.com/mcclure/lodr/blob/42a671f69a0518e384ac99c6f119fa0100adf302/_lodrSupport/target.lua#L3). This is self-evidently silly and doesn't match any ontological model of what the Identity is.

There are probably multiple valid ways to resolve this, but these are the restrictions I'd put on any solution.

**Comment by bjornbytes** [comment]
Now that `lovr.system` exists, it could be a good area to add a generic `lovr.system.getApplicationId` that doesn't have to deal with the intricacies of what the save directory is and when it is set up.

**Comment by mcclure** [comment]
That would make sense to me.

**Comment by mcclure** [comment]
(But, also, separately from the question of the application identifier, if you forcibly set the application identifier to the identity, getIdentity() should return that identity without the need to set the garbage identity.)

**Comment by bjornbytes** [comment]
Android now mounts the save directory earlier, fixing this quirk.
