### ISSUE TITLE
After drawing "too many" cubes, planes are not drawn

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#312]
Try this test program

https://github.com/bjornbytes/lovr-docs/pull/40

It will draw many cubes and a sphere

![image](https://user-images.githubusercontent.com/277318/97508938-39f2e180-1957-11eb-875a-20d3140e265b.png)

However, there are about 36 plane() calls forming a checkerboard floor in the code, which are not drawn.

Now, try inserting `break` at line 85, so that it draws only 1 cube

![image](https://user-images.githubusercontent.com/277318/97508986-5abb3700-1957-11eb-8537-a4f7c5983bbe.png)

Now it draws the floor!

What the hey?

Commenting out the sphere (comment out `cubemap.draw()` at the bottom) does not change the behavior of the program in any way.

I saw this on Windows with an AMD Radeon R9 390, I saw it in both the Rift and Desktop drivers. I did **not** see it on Oculus Quest. Holo reproduced some form of this but I didn't get details.

**Comment by jmiskovic** [comment]
Not reproducible on Linux with IntelHD, the floor is drawn in all cases.

**Comment by mcclure** [comment]
I thought this test was done with the oculus driver, but it was actually done with the steamvr driver with an oculus headset. I'm certain this doesn't change anything.

Bjorn has a potential fix for this but I have not tested it yet.

**Comment by mcclure** [comment]
Tested bjorn's 38875cb3997f , it fixes the **flickering** I was seeing (and might fix the flickering holo was seeing) but didn't fix the missing floor. Will test in renderdoc

**Comment by mcclure** [comment]
Here is a more minimal test case that removes all that distracting sphere/cube mapping stuff.

```
local scene = {}

function lovr.load()
	lovr.graphics.setBackgroundColor(0.9,0.9,0.9)

	scene.floorSize = 6
	scene.cubeCount = 60
	scene.boundMin = lovr.math.newVec3(-10, -1, -10)
	scene.boundMax = lovr.math.newVec3(10,   9,  10)
	scene.speed = 1
	scene.cubeSize = 0.2
	scene.cubes = {}

	for i=1,scene.cubeCount do
		scene.generate(i, true)
	end
end

function scene.generate(i, randomZ) -- Generate each cube with random position and color and a random rotational velocity
	local cube = {}
	cube.at = lovr.math.newVec3()
	cube.at.x = scene.boundMin.x + math.random()*(scene.boundMax.x-scene.boundMin.x)
	cube.at.y = scene.boundMin.y + math.random()*(scene.boundMax.y-scene.boundMin.y)
	if randomZ then
		cube.at.z = scene.boundMin.z + math.random()*(scene.boundMax.z-scene.boundMin.z)
	else
		cube.at.z = scene.boundMin.z
	end
	cube.color = {math.random()*0.8, math.random()*0.8, math.random()*0.8}
	scene.cubes[i] = cube
end

function lovr.update(dt) -- On each frame, move each cube and spin it a little
	for i,cube in ipairs(scene.cubes) do
		cube.at.z = cube.at.z + scene.speed*dt
		if cube.at.z > scene.boundMax.z then -- If cube left the scene bounds respawn it
			scene.generate(i)
		end
	end
end

function lovr.draw()
	lovr.graphics.setShader()

	-- First, draw a floor
	local floorRecenter = scene.floorSize/2 + 0.5
	for x=1,scene.floorSize do for y=1,scene.floorSize do
		if (x+y)%2==0 then
			lovr.graphics.setColor(0.25,0.25,0.25)
		else
			lovr.graphics.setColor(0.5,0.5,0.5)
		end
		lovr.graphics.plane('fill', x-floorRecenter,0,y-floorRecenter, 1,1, math.pi/2,1,0,0)
	end end

	-- Draw cubes
	for _,cube in ipairs(scene.cubes) do
		lovr.graphics.setColor(unpack(cube.color))
		lovr.graphics.cube('fill', cube.at.x, cube.at.y, cube.at.z, scene.cubeSize)
	end

	-- See issue #313
	lovr.graphics.setColor(1,1,1)
end
```

Notice, you can adjust the cube count as well as the plane count up and down by adjusting floorSize and cubeCount. Things I notice experimenting with this:

- The problem appears **whenever the number of cubes is greater than 1**. If the number of cubes is **exactly** 1 there is no problem.
- The problem is not dependent on the number of planes.
- I didn't notice this before-- the floor planes draw fine on the **first frame only**. ??

**Comment by mcclure** [comment]
Renderdoc observations.
- In general, the problem does not occur when Renderdoc is attached :(
- However, it will occasionally occur for single frames when Renderdoc is attached.
- I managed to capture one frame where the draw failed. (The one I captured used 60 cubes and 36 planes; with no renderdoc I was able to get a constantly-invisible floor with just 2 cubes and 1 plane.)

![image](https://user-images.githubusercontent.com/277318/97662610-eadba800-1a4d-11eb-9c74-397da8f915b5.png)

RenderDoc did find some problems.

![image](https://user-images.githubusercontent.com/277318/97662654-fdee7800-1a4d-11eb-860b-a4208393cb89.png)

I tried to look in the mesh viewer and it wasn't showing anything. Not sure why not. Can experiment more later. Why is it drawing two elements and two indexed? It looks like it's drawing both the cubes and the floor twice.

![image](https://user-images.githubusercontent.com/277318/97662742-40b05000-1a4e-11eb-8052-2f7a24647b1b.png)

I saved the .rdc files. Do you want them

**Comment by mcclure** [comment]
For comparison:

- Tested with 38875cb (0.14 HEAD) and the desktop driver .In the desktop driver the floor does draw, but it flickers blank about one frame every four seconds.

- Tested in a compiled version of lovr 6bce095660c4c (+ irrelevant mods, it's from my fork), which is a commit from july. This build was built with the oculus driver (i am testing with an oculus headset but the above tests were all compiled with steamvr). This version did **not** see the missing floor problem in either the oculus or the desktop drivers.

**Comment by bjornbytes** [comment]
Guessing this is fixed via the recent "amd always uses webgl buffer mode" patch, though I have no way to confirm.

**Comment by bjornbytes** [comment]
Needs to be retested (Currently working on updating the sample)
