### ISSUE TITLE
"Mirror" inherits most recent color, shader etc state of draw call

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#313]
I think this explains many of the sporadic problems we've been seeing with the Rift mirror window for a long time.

Consider this test program.

```
function lovr.load()
	lovr.graphics.setBackgroundColor(1,1,1,1)
	shader = lovr.graphics.newShader("standard")
end

function lovr.draw()
	lovr.graphics.setShader(shader)
	lovr.graphics.setColor(1,0,0)
	lovr.graphics.cube('fill', 0,1,-1, 0.25)
end
```

Run this in the desktop driver. Works fine. Run this in the Rift driver. The mirror window is black. Now, try adding the line `lovr.graphics.setShader()` to the final line of lovr.draw. Now it draws, but there is a red tint over everything

![image](https://user-images.githubusercontent.com/277318/97509413-973b6280-1958-11eb-9d33-ab88b57bd8b4.png)

Now try adding `lovr.graphics.setColor(1,1,1)` to the end of lovr.draw. Now the scene works okay.

The problem is that the [draw call for the mirror window](https://github.com/bjornbytes/lovr/blob/master/src/resources/boot.lua#L223) inherits the final shader, final collor, final setWireframe() mode etc of the lovr.draw function. We could fix this by adding `lovr.graphics.reset()` to the default lovr.mirror() but Bjorn points out this would violate expectations re: state persisting between draw calls. Bjorn suggests one solution might be a pipelines approach that allows you to create scoped states or whatever.

[See also](https://github.com/bjornbytes/lovr-docs/pull/40).

**Comment by mcclure** [comment]
I thought this test was done with the oculus driver, but it was actually done with the steamvr driver with an oculus headset. I'm certain this doesn't change anything

**Comment by bjornbytes** [comment]
- Canvas
- Shader
- Culling or Winding
- Wireframe
- Blend Mode
- Color
- Color Mask
- Stencil Test

Is I think everything that could affect the `lovr.graphics.fill`.  That's a lot.

**Comment by bjornbytes** [comment]
Not immediately relevant, and details subject to change, but the upcoming graphics stuff has passes.  Render state is reset at the beginning of a pass.

So you can do

```lua
lovr.graphics.render(headsetCanvas, function(cmd)
  cmd:setColor(color)
  cmd:cube('fill', x, y, z)
end)

lovr.graphics.render(windowCanvas, function(cmd)
  -- cmd:setState(mirrorState) -- if needed
  cmd:fill(headsetCanvas)
end)
```

And they will not conflict with each other.  boot.lua will handle the canvases and calls to .render so in a practical sense this just means that lovr.draw and lovr.mirror will not conflict anymore, fixing this issue and a whole class of other issues related to the global graphics state.
