### ISSUE TITLE
0.14 does not submit frames to headset when lovr.draw not present

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#314]
Tests with a local build of lovr 0.14, Oculus Rift, SteamVR driver. 4 tests, 1 and 4 succeed, 2 and 3 fail.

Test 1:
`lovr.exe include2`. Include2 does not exist.
Expected behavior: "Game not found" screen
Observed behavior: "Game not found" screen
**Test succeeds**

Test 2:
`lovr.exe include1`. Include1 is an empty folder.
Expected behavior: "Game not found" screen
Observed behavior: Hang, go to Vive main screen and "lovr: waiting" is visible in a little box.
**Test fails**

Test 3:
`lovr.exe include1`. Include1 is a folder containing an empty file named "main.lua".
Expected behavior: Black headset, blank window
Observed behavior: Hang, go to Vive main screen and "lovr: waiting" is visible in a little box.
**Test fails**

Test 4:
`lovr.exe include1`. Include1 is a folder containing an file named "main.lua" containing `function lovr.draw() end`.
Expected behavior: Black headset, blank window
Observed behavior: Black headset, blank window
**Test succeeds**

**Comment by bjornbytes** [comment]
Cause: `lovr.headset.renderTo` is only called if `lovr.graphics`, `lovr.headset`, and `lovr.draw` are defined.  This behavior is configurable.

If it is important to, by default, submit a blank texture to the compositor instead of submitting no texture when `lovr.draw` is `nil`, one way to do this would be to change `boot.lua` to declare an empty function as the default implementation of `lovr.draw`.  But I am not sure whether this is clearly a better default behavior.

**Comment by mcclure** [comment]
I think it maybe helps to consider when these failure modes would likely occur.

In the "main.lua is present but empty" case, probably the user can understand themselves why not drawing anything results in not drawing anything. Probably we don't need to worry about that case.

However in the "no main.lua or conf.lua" case, the most likely way you could get that would be to tell Lovr to open the *wrong folder*. In that case probably they got there by accident and they don't understand that they just pointed it at an empty folder. Maybe we should do something like throw a "no game found" error in that case, and ignore the case of "code exists but no lovr.draw".

**Comment by bjornbytes** [comment]
Hmm, so I get the no-game screen when pointing lovr at an empty folder.  I wonder if "Test 2:" the *working directory* had a main.lua and a conf.lua, causing main/conf to get recognized.

The change I am considering making here is to allow `lovr.headset.renderTo(nil)`.  If the callback is nil, nothing will be rendered and the texture submitted to the VR compositor will just be the background color.  That way if lovr.draw is missing, frames will still be submitted to the runtime.

**Comment by mcclure** [comment]
Actually… I think that if the user has provided a main.lua but specifically doesn't implement draw(), it might be *better* to draw nothing. This would mean you could make lovr programs that don't draw anything, such as build scripts.

Another option might be to have `renderTo(nil)` draw a blank screen, but `renderTo(false)` refrain entirely from rendering. This way someone who actively *does not want to draw* can opt out of it by setting lovr.draw to false, but the sloppy case does something unsurprising.

If lovr behaves right when pointed at an empty folder, then maybe there is no bug. However, regardless of what you do, I think the behavior of a nil/default lovr.draw should be [documented](https://lovr.org/docs/lovr.draw).

**Comment by bjornbytes** [comment]
Made a change:

- The lovr.headset.renderTo callback can be nil now, causing an empty frame to be submitted.  This means that compositors will no longer get confused and think the app is unresponsive when lovr.draw is nil.  To get the old behavior, disable the graphics module or modify lovr.run to not call lovr.headset.renderTo.
- lovr.mirror is called when lovr.draw is nil now.  As a consequence of this, the window will be (correctly?) cleared to the background color when lovr.draw is nil.

See 709a41a35242bf3b8f79cd995bb8cb695076fd80 for more info.
