### ISSUE TITLE
lovr.graphics.plane subdivisions

### ISSUE THREAD

**Issue by bjornbytes** [bjornbytes/lovr#315]
Add a subdivisions argument to plane:

`lovr.graphics.plane(style, transform, u, v, w, h, subdivisions)`

For heightmaps

**Comment by bjornbytes** [comment]
Defaults to zero

**Comment by bjornbytes** [comment]
Use it for a spiffy heightmap example

**Comment by bjornbytes** [comment]
Maybe a ShaderFlag to help write vertex shaders that displace vertices based on textures.

**Comment by shakesoda** [comment]
having separate subdivisions for x and y would be useful for things like screen space techniques (by default they can just be the same value). note the (undesired) wide polygons in the wireframe:
![image](https://user-images.githubusercontent.com/219510/97662303-dee2ec80-1a33-11eb-865b-580bafb285ea.png)

**Comment by bjornbytes** [comment]
:+1: wonder if it should be a table or 2 numbers

**Comment by bjornbytes** [comment]
This is implemented on dev branch (takes x and y subdivisions, works with both line and fill modes).
