### ISSUE TITLE
Calling require("lovr.math") on a helper thread corrupts heap

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#316]
I initially misunderstood this bug. [The actual bug is described in this comment.](https://github.com/bjornbytes/lovr/issues/316#issuecomment-719680594)

-----

Summary: Running very specific code causes lovr.errhand to fail with `bad argument #1 to '?' (quat expected, got light userdata)`. This error is internal to errhand and not caused by user code.

**Repro instructions**

- Build lovr 0.14 (I used steamvr driver)
- Check out `git@github.com:mcclure/lovr-ent.git`, make sure you have commit `42a671f69a0`
- Edit `lua/app/test/thread/init.lua`. There is a line:
        local ThreadTest = classNamed("ThreadTest", Ent)
    Change this line to:
        local ThreadTest = classNamed("ThreadTest")
    IE, remove the "ent" argument.
- Run this with `lovr.exe lovr-ent/lua app.test.thread`.

Result:

```
Error:
app/test/thread/init.lua:47: attempt to call method 'super' (a nil value)

Stack:
pl/class.lua:34: in function 'call_ctor'
pl/class.lua:164: in function 'CLS'
engine/common_ent.lua:40: in function 'load'
engine/common_ent.lua:47: in function <engine/common_ent.lua:44>
engine/ent.lua:143: in function 'route'
engine/ent.lua:80: in function 'insert'
main.lua:54: in function 'load'
boot.lua:177: in function <boot.lua:175>
[C]: in function 'xpcall'
Error occurred while trying to display another error:
bad argument #1 to '?' (quat expected, got light userdata)

Stack:
[C]: at 0x7ff7e906fb70
[C]: in function '__index'
boot.lua:274: in function <boot.lua:260>
[C]: in function 'xpcall'
```

**Okay, what's the bug?**

The first reported error-- "attempt to call method super"-- is correct. The "Ent" removed from init.lua is the superclass of the ThreadTest class; if ThreadTest has no superclass, then the self:super() call in its constructor is nil.

The `bad argument #1 to '?' (quat expected, got light userdata)`, which triggers inside errhand, is the bug.

**Variants**

I can fiddle around with the app/test/thread code a great deal and the error-reporting crash still occurs. It doesn't seem to matter what kind of error it is. If an error occurs there, you get the "bad argument to ?".

Conversely, I can't find a way to reproduce this problem except by running this exact code.

One thing that does make the crash go way. In lua/main.lua in lovr-ent there is a variable "singleThread". If you set this to true, then app/test/thread/init.lua will not create its helper thread. If you turn on singleThread, **the crash will not occur**. The error will be reported normally.

**Analysis**

I think this is actually a luajit bug, which would mean there's not much we can do. The symptom (nonsense being passed to a C call) is characteristic of other luajit bugs, as is the fact that the bug seems to be more a byproduct of code structure than any one thing the code does.

Because of the "singleThread" thing, I thought for a bit this might *actually* be a bug related to entering errhand while a second thread is running. To test this, I made a small test program. Put these two in the same directory:

main.lua:
```
local y
local function x()
	local thread = lovr.thread.newThread("thread.lua")
	thread:start()
	local name = "test"
	local channelSend = lovr.thread.getChannel(name.."-up")
	local channelRecv = lovr.thread.getChannel(name.."-dn")

	lovr.timer.sleep(1)
end
x()
for i=1,300000 do
	local g = {}
	g.x = 3
end
collectgarbage()
y()
```
thread.lua:
```
local thread = require("lovr.thread")
local name = "test"
local channelSend = thread.getChannel(name.."-up")
local channelRecv = thread.getChannel(name.."-dn")

while true do
	channelRecv:pop(true)
end
```
This is an attempt to recreate the thread API calls that app.test.thread does, as well as wait a little bit and run a gc, before crashing. This succeeds (that is, it fails with a normal error).

There is *one* way this could still be a lovr.thread bug. That would be if printing the unusually deep stack in app.test.thread, with references to many different files is actually causing the gc to be invoked *by lovr.errhand*. It seems like a stretch and I don't know how to confirm that hypothesis.

**Comment by bjornbytes** [comment]
Is it possible that the library is modifying the global lightuserdata metatable?  Does `quat` in the error refer to cpml's quat or lovr's quat?  Does modifying `t.math.globals` in `lovr.conf` change anything?  What is the implementation of `lovr.errhand` in this project?

**Comment by mcclure** [comment]
This also reproduces 100% if I execute the above with the given steps and there is ANY error in the thread (ie, i always get the "bad argument #1 to '?' (vec4 expected, got light userdata)")

**Comment by mcclure** [comment]
> Is it possible that the library is modifying the global lightuserdata metatable?

The metatable *for lightuserdata itself*? I don't think so, It **is** loading cpml, but rather than that modifying the metatable it uses `ffi.metatype(new, vec2_mt)` for various types such as `cpml_vec2`.

> Does quat in the error refer to cpml's quat or lovr's quat?

That's an interesting question but I'm not sure yet. It looks to me like a lovr internal error which would always be looking for lovr quat. Although CPML is being loaded, at this point in the code path no CPML objects (say, no CPML quats) would have been loaded.

> Does modifying t.math.globals in lovr.conf change anything?

How should I modify it?

> What is the implementation of lovr.errhand in this project?

It is the default. I have also performed this test with lodr, in which case it uses lodr's errhand (which calls lovr's default errhand). It fails the same way in the same place with lodr.

**Comment by mcclure** [comment]
Another weird detail: Say that I run the test in the top of this thread, except
1. I do **not** remove the ", Ent"
2. I change lua/app/test/thread/action.lua so that instead of saying `return x+1` it says `return x+nil` (in other words, I cause an error to happen on a helper thread)
I get the "bad argument to ?" error.

The lovr-ent main contains this:
```
function lovr.threaderror(thread, message)
	error(string.format("Error on thread:\n%s", (message or "[nil]")))
end
```
If I remove this, the "bad argument to ?" goes away.

If I try to reproduce this in my non-lovr-ent demo (the one quoted in my first post) by adding errors to the thread or by adding the lovr-ent threaderror to the simple demo, I do not reproduce it.

I don't know what to make of this. It seems to make the "luajit error" hypothesis less likely and a "lovr-ent is somehow breaking lightuserdata/quat" hypothesis (which you seem to be leaning toward) more likely

**Comment by mcclure** [comment]
Added prints to boot.lua. The error is occurring on the line
```
local projection = mat4():perspective(.1, 100, math.rad(67), width / height)
```

**Comment by mcclure** [comment]
The error is happening specifically in the `mat4()` call

**Comment by mcclure** [comment]
The error occurs **even if I never load CPML into the process**

**Comment by bjornbytes** [comment]
It's as if the Lua stack gets messed up in `l_lovrMathMat4` or `l_lovrMat4Set`.

**Comment by mcclure** [comment]
I thought the error was in mat4() but it wasn't. It is weirder than that.

The error occurs when mat4.perspective is accessed.

Not when it is called; when it is **accessed**.

In my current boot.lua, after `if lovr.graphics.hasWindow()` in `lovr.errhand`, i have the lines

    local emptyMat = mat4()
    print("_WINDOW2.3")
    print("_WINDOW2.3025", type(emptyMat))
    print("_WINDOW2.305", emptyMat)
    print("_WINDOW2.31", emptyMat.perspective)

This prints

```
_WINDOW2.3
_WINDOW2.3025   userdata
_WINDOW2.305Error occurred while trying to display another error:
bad argument #1 to '?' (quat expected, got light userdata)

Stack:
[C]: at 0x7ff6fbadf870
[C]: at 0x7ff6fbacf7a0
[C]: in function 'print'
boot.lua:287: in function <boot.lua:264>
[C]: in function 'xpcall'
```

**Comment by mcclure** [comment]
So:
```
  local width, lines = font:getWidth(message, wrap)
```
[This specific line](https://github.com/bjornbytes/lovr/blob/master/src/resources/boot.lua#L252), in boot.lua.
My boot.lua currently says

```
    print("uhF", mat4().perspective)
  local width, lines = font:getWidth(message, wrap)
    print("uhG", mat4().perspective)
```

Assuming we have prepared the scene by instantiating ThreadTest, when I hit these lines it prints

```
in l_lovrMat4Set
top is 1
type is -1
none path 1.000000Returning
uhF     function: 0x0425e198
in l_lovrMat4Set
top is 1
type is -1
none path 1.000000Returning
Error occurred while trying to display another error: error in error handling
```
(The top, type, none path stuff are printfs inside mat4(); they show mat4() is not doing anything strange.)
So mat4().perspective returns something valid before calling font:getWidth; and something invalid after.
If I attempt to print message at this step, "message" is a reasonable looking string (a note I was calling a nil self.super, which I was, and a stacktrace)

That's **if** I got there by the route of instantiating ThreadError() and calling the nil self.super at the end of the constructor.

If I got there by the path of triggering an error in a thread, and then calling error() in lovr.threaderror, instead I fail [here](https://github.com/bjornbytes/lovr/blob/master/src/resources/boot.lua#L239) (in boot.lua):
```
function lovr.errhand(message, traceback)
  print("_IN ERRHAND")
  print("uh9", mat4().perspective)
```
This prints:
```
_IN ERRHAND
in l_lovrMat4Set
top is 1
type is -1
none path 1.000000Returning
Error occurred while trying to display another error: error in error handling
```

If I attempt to print "message" at THIS step, I get: `bad argument #1 to '?' (quat expected, got light userdata)`
If I attempt to print `mat4().perspective` before calling `error()` inside threaderror, that works fine.

**Comment by mcclure** [comment]
If I get there by the path of triggering an error in a thread, and then calling error() in lovr.threaderror, **mat4 is already broken by the time I enter lovr.threaderror**.
If on the first line of lovr.threaderror I print a `mat4().perspective`, **that** triggers errhand with an error of `bad argument #1 to '?' (quat expected, got light userdata)`

**Comment by bjornbytes** [comment]
This is fixed
