### ISSUE TITLE
Driver change after lovr.event.restart() -> permanently uncapped FPS

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#318]
**Repro case**

Make a directory `demo1`. Write this into `demo/main.lua`:

```
function lovr.update(dt)
	print(string.format("Update %0.03f ; fps %0.03f", dt, lovr.timer.getFPS()))
end
```
And put this in `demo/conf.lua`:
```
local f = "sentinel.txt"

function lovr.conf(t)
	local existed = lovr.filesystem.isFile(f)

	print(string.format("Looking for %s at %s", f, lovr.filesystem.getRealDirectory("conf.lua")))
	if not existed then
		print("Sentinel didn't exist so crashing")
		f() -- Illegal
	end

	t.headset.drivers =  {"desktop"}
end

local oldErrhand = lovr.errhand
function lovr.errhand(...) -- Mini-lodr, wraps default errhand but will restart after 2s
	print("In errhand, will wait 2 seconds...")

	local oldErrhandResult = oldErrhand(...)
	local startTime = lovr.timer.getTime()

	return function(...)
	    if lovr.timer.getTime() - startTime > 2 then
	    	print("Restarting")
	    	return 'restart', lovr.restart and lovr.restart()
	    end
	    return oldErrhandResult(...)
	end
end
```

Run `lovr.exe demo1`. It will immediately drop into the error screen. Open another window and say `touch demo1/sentinel.txt`. This will cause main.lua to start running with an FPS over a thousand. Close and reopen the application. Now that sentinel.txt is there from the start, the FPS will be nicely capped to 60.

**Variants**

I ran my tests on Win10 with the SteamVR driver on an AMD card.

* I originally saw this testing with lodr. If you run this main.lua, you can see the bug with a conf.lua as minimal as `function lovr.conf(t) f() t.headset.drivers={"desktop"} end`. Run this, remove the f() and save and lodr will reboot you into 1000fps land
* It's not necessary to call lovr.errhand. It's only necessary to perform graphics operations. I have a variant of this where instead of doing the "mini-lodr" I call lovr.graphics.print() myself and call the basic functions like present(). This repros the 1000fps bug.
* However it **is** necessary to perform graphics operations. I have a version where the errhand calls print() only and does no graphics. This does not reproduce the 1000fps bug.
* If you run any of these versions, and you move the `t.headset.drivers={"desktop"}` **before** the `f()`, the problem does not reproduce.

**Conclusions**

Based on the discovery that setting headset.drivers before crashing fixes the bug, I conclude the problem here is that **allowing the SteamVR driver to wake up and draw frames on the first boot, but then waking up and requesting the desktop driver on a successive restart**, breaks the framerate.

**Is this worth fixing?**

It's definitely a bad bug, but it's kind of hard to trigger. It's very easy to trigger if you have any error in conf.lua at all **and** you're using lodr, but you mainly use lodr during development, and if you know how the bug works you can easily avoid it by intentionally putting the t.headset.drivers= before any complex code that might result in an error. The main problem with this bug is **it's hard to tell what's happening;** the failure mode (1000 FPS) is bad (because your CPU will peg...) but not obvious (you might not know why your CPU is pegged...). If this bug is hard to fix, it might be better to simply have lovr crash **harder** (ie, quit) if you try to change drivers after a restart. 

I could maybe imagine someone making a game with a settings screen that allows you to swap between drivers and that uses lovr.event.restart(), and this bug could actually be exposed to a user then. Maybe.

**Comment by bjornbytes** [comment]
Non-desktop headset drivers disable vsync because it messes up their frame timing.

The desktop headset driver doesn't modify vsync because it tries to use whatever was set in conf.lua.

I guess either `lovrPlatformCreateWindow` or `lovrGraphicsCreateWindow` could force-set the vsync if the window already exists, in case a headset driver from a previous restart changed it and the headset driver was changed or disabled in a way that means that the new instance of lovr actually wants the original vsync setting.

**Comment by bjornbytes** [comment]
Fixed this in 5c381ea.  `lovr.graphics.createWindow` will always set the window's vsync to the `flags.vsync` parameter, even if the window already existed and had its vsync changed by someone else.  I haven't tested this change yet.

**Comment by mcclure** [comment]
I will attempt to test it

**Comment by mcclure** [comment]
In my testing with 5c381ea the problem is fixed
