### ISSUE TITLE
Submodule ODE commit hash refers to a commit not in any branch

### ISSUE THREAD

**Issue by aiverson** [bjornbytes/lovr#332]
My automated builds of lovr are failing now that I tried to update them to the latest version because they can't fetch the submodules anymore. After hunting around a bit, the problem appears to be that the current master branch uses a commit in the ODE submodule that isn't properly in the repo it is pointing at, which results in the fetching failing from my automated builds, but happening to work in other cases.

**Comment by nevyn** [comment]
Fixed by https://github.com/bjornbytes/ODE/pull/2
