### ISSUE TITLE
Toggle fullscreen?

### ISSUE THREAD

**Issue by newobj** [bjornbytes/lovr#337]
Sorry if I missed an obvious API, but is there a way to set/get/toggle fullscreen for the window? I'm using LOVR for a desktop app, non-headset. Thanks.

**Comment by bjornbytes** [comment]
There isn't a way to do this right now

**Comment by bjornbytes** [comment]
Clarification: You can set `t.window.fullscreen` to get a borderless fullscreen window, but you can't change the fullscreen state after the window is created right now.
