### ISSUE TITLE
Automate Android Package ID

### ISSUE THREAD

**Issue by bjornbytes** [bjornbytes/lovr#342]
Currently the Android package ID is hardcoded to org.lovr.app in a few places:

- Activity Java files
- Android Manifest XML files
- Build system path to .class file
- JNI C symbol names

Changing the package ID is important for installing multiple lovr apps on a device or just using a custom one for store submission.  It would be great to be able to have a single piece of configuration in the build system that can be used to set the android package ID for a project (defaulting to org.lovr.app if left unspecified).

To investigate: Check out the `--rename-manifest-package` aapt flag to see if that can be used to specify the package ID for the manifest.  Relative Java package paths could be useful?  Preprocessor hacks could be used to set the C symbol names.

This quirk isn't documented, so at the very least it needs to be added to the Compiling guide until it's improved.

**Comment by mcclure** [comment]
> This quirk isn't documented, so at the very least it needs to be added to the Compiling guide until it's improved.

Something else you should document at the same time: this line in the AndroidManifest_oculus.html:
```
<application android:allowBackup="false" android:label="LÖVR">
```
This is correct for a shipping application. However, this will produce an APK which is not debuggable, which will mean you cannot attach RenderDoc. To make RenderDoc work, change this line to
```
<application android:allowBackup="false" android:label="LÖVR" android:debuggable="true">
```

**Comment by bjornbytes** [comment]
This is done.  You can now optionally set `CONFIG_ANDROID_PACKAGE` (or `-DANDROID_PACKAGE` in CMake) to set the package id of the installed apk.
