### ISSUE TITLE
macOS Permission Issues

### ISSUE THREAD

**Issue by bjornbytes** [bjornbytes/lovr#345]
Trying to run LÖVR.app on new versions of macOS results in permission errors:

> You do not have pemission to open the application "LÖVR"

And from the terminal:

> zsh: permission denied: /Applications/LÖVR.app

Maybe this is due to missing notarization or some other permission request that needs to be made?

**Comment by ripter** [comment]
Because the app isn't signed, users need to use control-click to give the app permission to run. You can find out more here: https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac
