### ISSUE TITLE
Build error in WSL2

### ISSUE THREAD

**Issue by tapir** [bjornbytes/lovr#349]
I have Ubuntu 20.04 installed in Windows 10 via WSL2.
After setting up everything according to the documentation and running this command
`cmake -DANDROID_SDK=~/my-android/sdkroot -DCMAKE_TOOLCHAIN_FILE=~/my-android/sdkroot/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_NATIVE_API_LEVEL=26.0.3 -DANDROID_KEYSTORE=~/my-android/lovr.keystore -DANDROID_KEYSTORE_PASS=XXXXX -DANDROID_MANIFEST=~/my-android/AndroidManifest_oculus.xml -DANDROID_ASSETS=~/lovr-project ..`

I get this error
`Error copying file "/home/tapir/lovr/src/resources/Activity_.java" to "Activity.java".
make[2]: *** [CMakeFiles/buildAPK.dir/build.make:58: CMakeFiles/buildAPK] Error 1
make[1]: *** [CMakeFiles/Makefile2:218: CMakeFiles/buildAPK.dir/all] Error 2
make: *** [Makefile:130: all] Error 2`

Any ideas what might have gone wrong?

**Comment by bjornbytes** [comment]
Try adding `-DLOVR_USE_VRAPI=ON`

**Comment by tapir** [comment]
Thanks, seems like this info is missing from the docs.

**Comment by bjornbytes** [comment]
Looks like we added it to the docs here but it isn't merged yet https://github.com/bjornbytes/lovr-docs/pull/37

I'd also like it if CMake yelled if no android backend is given.

**Comment by tapir** [comment]
For future reference, to anyone trying to compile it: use openjdk-8 instead of a newer version. android doesn't like them.
