### ISSUE TITLE
Project folders with special characters don't work on Windows

### ISSUE THREAD

**Issue by msub2** [bjornbytes/lovr#365]
I just started messing around with LOVR today and I think I've found an issue. I was following the Getting Started guide, and named my project folder "LÖVR". However, when I dragged the folder onto lovr.exe it wouldn't detect the game. As soon as I changed the folder name to be just "LOVR" the game worked as expected.

**Comment by bjornbytes** [comment]
Thanks for the report!  Just tried it on linux and things were working, I'll need to investigate further on a windows machine
