### ISSUE TITLE
Lovr app not running on Mac Big Sur

### ISSUE THREAD

**Issue by agoralski** [bjornbytes/lovr#366]
Upon starting the app - it crashes. Looks like it cannot find opengl library, here's the log from the crash report:

`Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: No shared cache present
Library not loaded: /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
  Referenced from: /Applications/LÖVR.app/Contents/MacOS/lovr
  Reason: image not found`

**Comment by bjornbytes** [comment]
I believe this has been fixed on the latest master branch, were you running the v0.15.0 release or compiling from source?

**Comment by nevyn** [comment]
This is the luajit image_base bug I fixed recently :)
