### ISSUE TITLE
STL support for ModelData

### ISSUE THREAD

**Issue by dromer** [bjornbytes/lovr#380]
There are many free STL available. Having to convert them in all cases would be quite tedious.
In general STL is a more simple format compared to OBJ so supporting it is hopefully not too hard.

Hope you will consider :)

(we are actually converting VTK mesh objects to STL and I don't really feel like adding OBJ export to that as well :D)

**Comment by bjornbytes** [comment]
This sounds good to me.  I have written an STL parser before and it's a nice and simple format.

**Comment by bjornbytes** [comment]
Progress

![image](https://user-images.githubusercontent.com/784805/108892119-be373780-75cc-11eb-9efe-0fe697a06b1f.png)

**Comment by bjornbytes** [comment]
Binary STL models are now supported in the `dev` branch and will be released in the next version.

ASCII STL files are more challenging to parse, but those could also be supported in the future.

**Comment by dromer** [comment]
Hah, awesome :)

**Comment by dromer** [comment]
Actually atm we have `particle_mesh.stl: ASCII text, with CRLF line terminators` so that would be what we're looking out for :)
