### ISSUE TITLE
Underscores don't draw anymore

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#385]
Check out dev (I used `6eef950`). Run a `main.lua` containing

require "a_b"

You will see

![image](https://user-images.githubusercontent.com/277318/111846005-5c70a180-88dc-11eb-8e4a-fb28af668647.png)

Notice: The underscore is rendering as a space.

I am seeing this on both Oculus Quest and desktop driver on Windows. I'm pretty sure I didn't see this problem before.

**Comment by bjornbytes** [comment]
Changing the font's padding from 2 to 3 fixes it.  Need to figure out why

**Comment by bjornbytes** [comment]
Fixed in 3a35f81918d37369b895357a6a7c6c1f341ece62, it was integer overflow
