### ISSUE TITLE
LOVR sometimes can't restart properly when I put on Oculus Quest 2.

### ISSUE THREAD

**Issue by brainrom** [bjornbytes/lovr#391]
Most of time, all works perfect, but sometimes, when I take off Quest and then put it on again, image flicks one time and then all FOV goes black. AFAIR, it caused by launching "second instance" and attempt to capture already captured display.
Log from logcat:
```
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.lovr.app/.Activity }
--------- beginning of system
--------- beginning of tracking
--------- beginning of crash
--------- beginning of main
03-25 10:55:39.054  4485  4509 D LOVR    : Loading a script from the user files directory. To upload a new script, cd to your project directory and run: adb push --sync . /sdcard/Android/data/org.lovr.app/files/.lodr
03-25 10:55:42.092  6120  6151 D LOVR    : Loading a script from the user files directory. To upload a new script, cd to your project directory and run: adb push --sync . /sdcard/Android/data/org.lovr.app/files/.lodr
03-25 10:55:44.438  6120  6241 D LOVR    : Warning: Could not load module "graphics": Window is already created
03-25 10:55:44.438  6120  6241 D LOVR    : Error:
03-25 10:55:44.438  6120  6241 D LOVR    : phong.lua:2: attempt to index field 'graphics' (a nil value)
```
As you can see, shader can't use graphics module too.

**Comment by bjornbytes** [comment]
A new version of lodr has since been released.  I wonder if the problem is fixed?  It is hard for me to tell if this is an issue with lovr or lodr.

**Comment by brainrom** [comment]
New version of lodr is just a compatibility patch for LOVR 0.15 (`lovr.system.getOS()`). I'll test LOVR 0.15 on Oculus Quest 2 today and will give a feedback.

**Comment by brainrom** [comment]
After Oculus OS force upgrade to version user-1528060.13960 I'm unable to reproduce this bug anymore. Not on 0.14 nor 0.15.
