### ISSUE TITLE
`lovr.headset.getHands` looks for device poses not actual active hands

### ISSUE THREAD

**Issue by Wallbraker** [bjornbytes/lovr#401]
In OpenXR hand tracking is de-coupled from controller tracking, meaning that handtracking can be active while controller tracking is disabled. This is the case when using the NorthStar headset and Monado. But the implementation of `lovr.headset.getHands` (`l_lovrHeadsetGetHands`) checks for controller poses to test activeness of hands. See below.

```c++
static int l_lovrHeadsetGetHands(lua_State* L) {
  if (lua_istable(L, 1)) {
    lua_settop(L, 1);
  } else {
    lua_newtable(L);
  }

  int count = 0;
  float position[4], orientation[4];
  Device hands[] = { DEVICE_HAND_LEFT, DEVICE_HAND_RIGHT };
  for (size_t i = 0; i < sizeof(hands) / sizeof(hands[0]); i++) {
    FOREACH_TRACKING_DRIVER(driver) {
      if (driver->getPose(hands[i], position, orientation)) {
        luax_pushenum(L, Device, hands[i]);
        lua_rawseti(L, -2, ++count);
      }
    }
  }
  lua_pushnil(L);
  lua_rawseti(L, -2, ++count);
  return 1;
}
```

**Comment by bjornbytes** [comment]
Copying notes from Slack:

- Something like `headset_isTracked(Device)` would be nice, it would fix `lovr.headset.isTracked` and `lovr.headset.getHands`.  A lot of the time its implementation will be similar to that of getPose, but may be able to save some work.
- isTracked/getHands could also check getSkeleton
- OpenXR driver could return a pose (e.g. palm joint) when only hand tracking is active

**Comment by Wallbraker** [comment]
On the last point, IIRC HoloLens emulates a controller with hands for the application either via `khr/simple_controller` or `microsoft/hand_interaction` interaction profiles (see [extension](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XR_MSFT_hand_interaction)). And somebody is writing similar emulation for Monado right now.

**Comment by bjornbytes** [comment]
The OpenXR headset driver has been modified to:

- Properly check pose actions for `isActive` before locating their spaces (fixes an issue I saw on the FB runtime where locating action spaces would return invalid pose data with valid locationFlags when hand tracking is in use).
- Fall back to using hand tracking data when asking for a hand pose

This should fix the issue where hands/poses don't show up properly with hand tracking.  Let me know if you still see anything weird!
