### ISSUE TITLE
lovr.headset.newModel on Oculus Mobile returns sideways hand model in 0.15

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#417]
In my debug UI, I have some code that draws visible markers for the handsets. At startup it calls lovr.headset.newModel(controllerName); if this returns a model it displays that model. If it returns nothing, it displays a cube. Until today this code has only ever returned anything on OpenVR/SteamVR.

On upgrading from 0.14 to 0.15, newModel has suddenly, for this code, running on Quest, started returning a white hand model, pointing sideways.

![com mermaid test skategirl_hotswap-20210419-225837](https://user-images.githubusercontent.com/277318/115331198-7adbee00-a163-11eb-80e5-52a4de09f9cd.jpg)

In this image the line pointing forward from the wrist is the direction the controller is actually pointing. Last time I tested this code with OpenVR it oriented the controllers correctly. It is correct that the hand is red (it's red because I'm tinting it red). I am seeing all this in handset mode (hand tracking is not activated).

I don't know what I expect `lovr.headset.newModel` to do on Quest exactly but I DEFINITELY don't expect it to return a hand. I would expect hand models and controller models would be vended from two different functions.

**Comment by bjornbytes** [comment]
I think what is happening is animated/non-animated hand model pose breaks, and then fixing one breaks the other, GOTO 10.  Going to try adjusting the root node transform in `vrapi_newModelData` based on the animated flag so that they both work.

**Comment by bjornbytes** [comment]
Fixed in 89550e5
