### ISSUE TITLE
AppImage doesn't work on Debian stable

### ISSUE THREAD

**Issue by monolifed** [bjornbytes/lovr#421]
It requires glibc 2.29. But debian stable(buster) has 2.28-10

**Comment by bjornbytes** [comment]
It begins

**Comment by bjornbytes** [comment]
I am not yet familiar with the details of packaging libc in a portable way.  Should I research the distros+versions that lovr wants to support, find which libc version they use, and build using the lowest one?  Should I use musl and statically link against libc?  Any thoughts are appreciated!

**Comment by monolifed** [comment]
Love seems to use ubuntu 16.04 and https://github.com/pfirsich/love-appimages
https://github.com/love2d/love/blob/master/.github/workflows/main.yml

This comment might be relevant
https://github.com/pfirsich/love-appimages/blob/master/build.py#L16
```python
# https://github.com/AppImage/pkg2appimage/blob/master/excludelist
# https://discourse.appimage.org/t/will-a-new-appimage-run-on-older-distributions/84/3
# We assume that among other libs glibc and libstdc++ are installed on the user's system
# But those libraries should be backwards compatible, so you should build löve on,
# as the comment says "the oldest system you are targeting"
```

**Comment by bjornbytes** [comment]
Out of curiosity I tried compiling with `musl-gcc` and it did not work at all, mainly due to other dependencies relying on libc++.

I guess I'll need to make future builds in a VM on an older version of Linux.

For reference the current appimage was compiled on Ubuntu 20.10 (with libc 2.32).

**Comment by bjornbytes** [comment]
I made a note of this on the website and will be remedying in the next release

**Comment by monolifed** [comment]
It works in Debian 11 Bullseye
