### ISSUE TITLE
Oculus driver crashes 100% on quit

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#423]
Test: Build lovr 0.15/master with the Oculus driver (I used fc87bffbe0bc) run any app (I tested with `devenv.com /debugexe build\Debug\lovr.exe C:\Users\Andi\work\lv\lodr C:\Users\Andi\work\lv\lovr-docs\showcase\Break` in the VS 2019 native tools window ... but, running with the "No game found :(" window is adequate) and then close it.

oculus_destroy will crash on the line `ovr_DestroyTextureSwapChain(state.session, state.chain);`.

![image](https://user-images.githubusercontent.com/277318/115782069-3a5db980-a389-11eb-92aa-f451aab705c6.png)

Commenting out ovr_DestroyMirrorTexture does not change this crash. The crash will also trigger on a `lovr.event.quit("restart")` (such as from lodr).

If you **don't** run in the debugger, this quit just looks like a normal quit. But you won't be able to use lodr because the crash will trigger on first restart.

**Comment by bjornbytes** [comment]
Which version of LibOVR?

**Comment by mcclure** [comment]
1.43.0. I am testing with 23.0.0 now.

**Comment by mcclure** [comment]
(How the heck did it go from version 1.43.0 to 23.0.0?)

**Comment by mcclure** [comment]
Problem reproduces with most current Oculus SDK (23.0.0). Same line, same behavior.

**Comment by mcclure** [comment]
It looks like we're using these functions correctly. If I comment out `ovr_DestroyTextureSwapChain`, it just crashes on ` ovr_Destroy(state.session);`. Maybe something we're doing earlier is corrupting the heap.

**Comment by mcclure** [comment]
If I comment out
```
    lovrRelease(state.textures.data[i], lovrTextureDestroy);
```
At the top of oculus_destroy, the problem stops expressing. I can comment or uncomment whatever else I like, it doesn't really matter. If we release the state.textures.data textures, either `ovr_DestroyTextureSwapChain` or `ovr_Destroy` (whichever we call) will crash. If we skip releasing those textures, `ovr_DestroyTextureSwapChain` and `ovr_Destroy` succeed, apparently cleanly.

Maybe something is getting double-freed?

**Comment by bjornbytes** [comment]
Ok, I believe this is enough information to fix the issue.  It looks like `lovrTextureDestroy` is unconditionally calling `glDeleteTextures` (and `glDeleteRenderbuffers`), which it probably only ought to do if `texture->native` is `false`.

**Comment by mcclure** [comment]
Sounds like this could potentially trigger even outside the Oculus driver then.

**Comment by bjornbytes** [comment]
Native texture handles were always getting destroyed, so either this was never noticed or it's new behavior in LibOVR.  I pushed a commit to `dev` that makes the change described above, could you verify that it fixes the problem?

**Comment by mcclure** [comment]
I will test this sometime later this week, thanks
