### ISSUE TITLE
Steam spatializer applies reverb even to non-spatialized sources

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#425]
Copied from #424:

Check out the branch [break-phonon-test-2](https://github.com/mcclure/lovr-docs/tree/break-phonon-test-2) of my lovr-docs repo and run Showcase/Break. This version of break has some tweaks to support testing (the sounds have all been edited to have long periods of silence afterward).

Run this with the Phonon spatializer. This demo has three types of sound effect: a series of short tone blips when the ball bounces off something; a "BEEP BEEP BEEP!" when the game is about to start; a "BRUH-NUH!" when you lose. [As you can see](https://github.com/mcclure/lovr-docs/blob/break-phonon-test-2/showcase/Break/main.lua#L152), a full suite of effects are applied to the tone blips, but none to the other two sounds. In testing, the BEEP BEEP BEEP and BRUH-NUH have reverb even though they should be no-effects sounds (IE the spatializer shouldn't even get the CHANCE to process them). If you disable reverb globally (`geometryMode = "disable" at the top`) they sound normal.

**Comment by bjornbytes** [comment]
It seems like they're still using the old API for effects.

The BEEP BEEP BEEP and BRUH NUH are created with `{ spatial = false }`, but the [docs here](https://lovr.org/docs/lovr.audio.newSource) don't mention that flag.  It should be `{ effects = false }`.  I made this change and they don't sound spatialized/muffled anymore.

Additionally, there is no need to manually `setEffectEnabled` every Effect now for the blips.  You can leave the `effects` option as `nil` (AKA `true`, the default), which will enable all effects.

**Comment by mcclure** [comment]
OK. I was behind on the API then. Thanks.
