### ISSUE TITLE
All-in-one Plugin Support

### ISSUE THREAD

**Issue by bjornbytes** [bjornbytes/lovr#427]
Lua's stock loaders offer 2 ways of loading native libraries.  For `require 'a.b.c'`, it will try:

- `a/b/c.so`, `a/b/c.dll`, `/usr/local/a/b/c/init.so` etc.
- `a.so`, `a.dll`, `/usr/local/a/init.so` etc. (all-in-one)

In both cases this is controlled by `package.cpath` and the symbol loaded will be `luaopen_a_b_c`.  The purpose of all-in-one is to package multiple Lua libraries in one native library file.  luasocket notably uses this approach to package e.g. `luasocket.ftp`, `luasocket.http`, `luasocket.dns` modules into a single dll file.

The plugin loader that `lovr.filesystem` uses currently supports the first type of library, but not the second.  This issue is about adding the second.

When confronted with `require 'a.b.c'`, the loader should, in addition to trying e.g. `<exepath>/a/b/c.dll`, it would also try `<exepath>/a.dll`.  That's it.

It isn't yet clear if this should be a separate loader or stuffed into the existing one.  Will likely need to just feel it out during implementation.  Seems like latter would be simpler/reduce duplication.

**Comment by brainrom** [comment]
LOVR can load `socket`, `socket.ftp`, `socket.http` from `socket.so`, using `luaopen_socket`, `luaopen_socket_ftp`, `luaopen_socket_http` symbols respectively, but can't load `mime` from `socket.so` (and `socket` from `libluasocket.so`, where CMake builds module by default, too!), even if `luaopen_mime` symbol presents in `socket.so`, workaround is symlinking/copying `mime.so -> socket.so` . Maybe, when `require` is called. LOVR should search symbols through all available `.so`/`.dll` inside lovr's executable directory (`build/bin` for example) and throw an error only in case of unsuccess.

**Comment by bjornbytes** [comment]
> but instead of it, lovr search it in `pwd`. So, I think it's a bug.

Where are you seeing that native libraries are searched for in the working directory?

In l_filesystem, the base path is `lovrFilesystemGetExecutablePath` (`/path/to/lovr`).  The executable gets stripped off -> `/path/to/`.  Finally the module and extension is appended -> `/path/to/module.so`.

**Comment by brainrom** [comment]
Here :cry:  :
```
main.lua:2: module 'socket.http' not found:
        no field package.preload['socket.http']
        no file './socket/http.lua'
        no file '/usr/local/share/luajit-2.1.0-beta3/socket/http.lua'
        no file '/usr/local/share/lua/5.1/socket/http.lua'
        no file '/usr/local/share/lua/5.1/socket/http/init.lua'
        no file './socket/http.so'
        no file '/usr/local/lib/lua/5.1/socket/http.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './socket.so'
        no file '/usr/local/lib/lua/5.1/socket.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
```
`no file './socket.so'`
Currently I'm trying to fix this behavior.

**Comment by brainrom** [comment]
Ok, I understood lualoader process. Btw, because of some unknown reasons libluasocket successfully loaded when pwd was equal to executable path. 
I made a separate loader ([patch](https://github.com/brainrom/lovr/commit/d2bbf4c36e013196280f74f9061900c48b621d8e)). It's not so fancy, as it can be, but it works. 
I'll try to take out all loader functionality to another function, pass module argument and all-in-one/not all-in-one flag and call it in dummy lua loaders.

**Comment by bjornbytes** [comment]
Maybe luasocket loaded when in pwd due to Lua's built-in loader functionality.
