### ISSUE TITLE
Compilation issues on Ubuntu

### ISSUE THREAD

**Issue by jmiskovic** [bjornbytes/lovr#43]
I had many issues while compiling lovr on Linux Mint (Ubuntu derivate), most of them related to older system headers/libs being used instead of ones supplied in _deps_ directory.

In the end I managed to stumble through it, so here's list of issues I had with my solution/workaround:

```
/home/user/lovr/deps/msdfgen/core/msdfgen-c.cpp: In function ‘void msGenerateMSDF(uint8_t*, int, int, msShape*, float, float, float, float, float)’:
/home/user/lovr/deps/msdfgen/core/msdfgen-c.cpp:72:29: error: ‘isfinite’ was not declared in this scope
       data[i++] = isfinite(r) ? clamp(int(r * 0x100), 0xff) : 0xff;
```
I replaced all _isfinite_ instances with _std::isfinite_ in msdfgen-c.cpp.

```
/home/user/lovr/src/api/graphics.c: In function ‘luax_readvertices’:
/home/user/lovr/src/api/graphics.c:65:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (int i = 1; i <= count; i++) {
```
Added _CMAKE_C_FLAGS:STRING=-std=c99_ to CMakeCache.txt.

```
/home/user/lovr/deps/enet/unix.c: In function ‘enet_address_set_host’:
/home/user/lovr/deps/enet/unix.c:121:21: error: storage size of ‘hints’ isn’t known
     struct addrinfo hints, * resultList = NULL, * result = NULL;
```
Added _#define _XOPEN_SOURCE 600_ to the top of that file.

```
/home/user/lovr/src/audio/audio.c: In function ‘lovrAudioInit’:
/home/user/lovr/src/audio/audio.c:20:10: error: unknown type name ‘LPALCRESETDEVICESOFT’
   static LPALCRESETDEVICESOFT alcResetDeviceSOFT;
```
Had different version of libopenal-dev from package manager, so I had to compile local version in deps/openal-soft and set _OPENAL_INCLUDE_DIRS:INTERNAL_ in CMakeCache.txt to correct dir.

I had to do same thing for assimp, glfw and physfs. For glfw, static lib didn't work, I had to build dynamic lib. Also needed to include _-lX11 -ldl -lXxf86vm_ linker flags.

I'm out of my depth with CMake so I'm not able to submit a decent pull request.

**Comment by bjornbytes** [comment]
It seems some of these problems could be fixed if the headers in the `deps` folder were used instead of the system installed ones.  I'll do the fixes for C99 and std::isfinite.

**Comment by bjornbytes** [comment]
CMake now builds the dependencies in `deps` by default now (there are optional flags that will enable the old pkg-config behavior).  The other issues have since been fixed as well, so compilation on Ubuntu should be okay now.
