### ISSUE TITLE
Broken AppImage integration [FIX INCLUDED]

### ISSUE THREAD

**Issue by darltrash** [bjornbytes/lovr#430]
AppImageLauncher (libappimage) is unable to integrate Lövr with the system. 
Upon closer inspection, I realized that the problem was that the lovr.desktop file lacked the Exec definition, which should be:
`Exec=AppRun`.

The end file should look like this:
```ini
[Desktop Entry]
Exec=AppRun
Name=LÖVR
Type=Application
Icon=logo
Categories=Development;
```

Also i noticed that there was another AppImage inside the AppImage, which is probably just a mistake made by the packager.
![IMAGE](https://user-images.githubusercontent.com/38925212/116821187-dab09c80-ab46-11eb-966e-0184384b2c87.png)

**Comment by bjornbytes** [comment]
Thanks!  Along with #421 there were definitely some problems with this one, on the next release I'll be including all these fixes

**Comment by Wallbraker** [comment]
So I just tried this, and at least my appimage install it doesn't require the `Exec` field to be set.

**Comment by Wallbraker** [comment]
Hello @darltrash, I was the one that did the AppImage files, thank you for the fix. I have made a two MRs #448 #449
