### ISSUE TITLE
LOVR not buildable with Lua instead of LuaJIT

### ISSUE THREAD

**Issue by brainrom** [bjornbytes/lovr#434]
Looks like math library links in LuaJIT, adding `m` and `${CMAKE_DL_LIBS}` to `target_link_libraries(lovr` solves this issue.

**Comment by bjornbytes** [comment]
Was this with CMake on Linux?

**Comment by brainrom** [comment]
Yes ;)
I'll prepare PR with nice fix tomorrow. 
Btw, today I've successfully compiled and ran LOVR (but with Lua, not LuaJIT) on e2k processor architecture. Compiled with MCST LCC compiler, runs on Linux. It seems like it's one more available platform for LOVR.
