### ISSUE TITLE
getViewAngles don't work on Oculus Quest 2 when tracking disabled.

### ISSUE THREAD

**Issue by brainrom** [bjornbytes/lovr#446]
When I disable tracking (6DOF) in Oculus Quest menu, `lovr.headset.getViewAngles(1)` returns `nil, nil, nil, nil`, but `lovr.headset.isTracked()` returns `true`. When 6DOF is enabled, all works perfect.

**Comment by bjornbytes** [comment]
[Currently](https://github.com/bjornbytes/lovr/blob/master/src/modules/headset/headset_vrapi.c#L142-L143) it checks to see if both position is valid and orientation is valid.  Maybe it should be changed to just check orientation, or see if either of the bits are set.

**Comment by brainrom** [comment]
Okay, I've rebuilt the app. It seems, like disabling `VRAPI_TRACKING_STATUS_POSITION_VALID` is absolutely enough to correctly get view angles with 3DOF.
