### ISSUE TITLE
Return lovr userdata types from plugins

### ISSUE THREAD

**Issue by brainrom** [bjornbytes/lovr#453]
Now I'm trying to make a plugin that should return already initialized texture and now I'm encountered a problem, that even if I include all necessary headers at texture creation time I get `undefined symbol: lovrTextureFormat`. Is it possible to do such thing at current stage of development or I should find another way to accomplish that?

**Comment by bjornbytes** [comment]
It's not officially supported to make a plugin that interfaces with LÖVR internals.  It's technically possible if you get together all the includes and compiler flags, but the plugin could break later if LÖVR changes something.  Right now, they're just meant for providing access to independent C libraries, at least until LÖVR has a stable C API (#383).
