### ISSUE TITLE
Stereo Image on Desktop headset driver breaks on nVidia GPU.

### ISSUE THREAD

**Issue by brainrom** [bjornbytes/lovr#454]
Linux, Nvidia driver 465.31. Planes, skyboxes, 3D models have this behavior. When using OpenXR (Monado in my case), all seems OK, and in mirroring window too.
![sample](https://user-images.githubusercontent.com/15963835/124475554-875b0480-ddaa-11eb-8b23-5c1d2d7249d3.png)

**Comment by bjornbytes** [comment]
Very weird, maybe lovr could set a scissor when drawing each eye to prevent the 'overflow'

**Comment by bjornbytes** [comment]
This will also definitely be fixed on vulkan.  There it always uses the openxr rendering mode (array textures).

**Comment by bjornbytes** [comment]
Maybe scissor could fix this

**Comment by bjornbytes** [comment]
Works okay on nouveau
