### ISSUE TITLE
Haxe support!

### ISSUE THREAD

**Issue by Rabios** [bjornbytes/lovr#456]
Hi there, Sorry if annoyed ya devs...
However i done Haxe support in form of externs, Which could be found [here](https://github.com/Orange-hx/hxlovr) ❤️ 

Thanks for reading! :)

**Comment by bjornbytes** [comment]
Cool!  BTW there is also https://github.com/excessive/lovr-haxe-wrappergen.  I don't know much about haxe but maybe there is some overlap/collaboration possible between these 2 efforts.
