### ISSUE TITLE
OSVR headset support

### ISSUE THREAD

**Issue by TSnake41** [bjornbytes/lovr#46]
It should be nice to add [OSVR](https://osvr.github.io/) support to LÖVR since [a lot of devices supports it](https://osvr.github.io/compatibility/).

The [ClientKit](http://resource.osvr.com/docs/OSVR-Core/group__ClientKit.html) is a good starting point.

[OSVR-Core documentation](http://resource.osvr.com/docs/OSVR-Core/index.html)

**Comment by bjornbytes** [comment]
This could be cool.  LÖVR actually [used OSVR at first](https://github.com/bjornbytes/lovr/blob/9bb4ad82ef4258031f6a52afd6a4315f406ed1f5/src/interface.c) before moving to OpenVR.  I don't think I'll be able to prioritize this soon though.
