### ISSUE TITLE
Umbrella bug: EFFECT_NONE rough edges

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#460]
For sound Sources, there is a distinction between EFFECT_NONE and effect=0. EFFECT_NONE sounds are barred from the spatializer, and can never have effects enabled. effect=0 sounds are passed into the spatializer but the spatializer is expected to do nothing to them.

But there are problems:

- Although EFFECT_NONE is supposed to be a sticky bit, `source:setEffectEnabled("anything", false)` can change it. Worse, it will change the effect state to garbage.
- The docs do not make it clear that the EFFECT_NONE state exists. [`newSource` doc](https://lovr.org/docs/lovr.audio.newSource) says "The special value false can be used to completely disable effects, bypassing the spatializer entirely" but does not indicate this is a permanent effect. setEffectEnabled does not mention it will be a noop on a _NONE object.
- Although EFFECT_NONE is a distinct state, there is no way for a user to query whether a source is EFFECT_NONE, the way they can with the individual spatialization effects.

**Comment by mcclure** [comment]
Per discussion with Bjorn consider `setEffectEnabled("anything", true)` on EFFECT_NONE throwing an error.

**Comment by bjornbytes** [comment]
Made the following changes:

- Calling `Source:setEffectEnabled` on a Source created with `{ effects = false }` will throw an error (dev).
- Updated documentation for newSource, isEffectEnabled, setEffectEnabled to explain effects = false better.

**Comment by bjornbytes** [comment]
Leaving open since there is still no way to ask if a Source was created with effects = false.

**Comment by bjornbytes** [comment]
There is now a `spatial` flag on sources with a `lovrSourceIsSpatial` getter.  The concept of "does a source use the spatializer" is completely separate from "which effects are enabled".
