### ISSUE TITLE
Network connections?

### ISSUE THREAD

**Issue by crertel** [bjornbytes/lovr#467]
Hello!

Is there any chance we can get a HTTP or (even better) Websockets client for Lovr? If not, how would we go about pulling that in?

My use case is hacky prototyping on a Quest connecting to a local development server running a web stack.

**Comment by brainrom** [comment]
[This](https://github.com/brainrom/lovr-luasocket)
Tested (and it works!) on Quest 2, not just desktop Linux.

**Comment by crertel** [comment]
Oh sweet! How do plugins work if I wanted to pull in other Lua libs?

**Comment by brainrom** [comment]
They need to be built with LOVR itself. Just clone plugin in `plugins` folder (create it) inside the LOVR and then buid LOVR as usual.

**Comment by bjornbytes** [comment]
You can also place a plugin library (dll/so) next to the LÖVR executable and it will work.

In addition to lovr-luasocket, [luajit-request](https://github.com/LPGhatguy/luajit-request) may be useful.
