### ISSUE TITLE
Mac Installation

### ISSUE THREAD

**Issue by jonasjohansson** [bjornbytes/lovr#468]
I'm unable to find documentation on how the Mac deployment pipeline is setup. I've got the DMG and the app installed. I have a folder with the **main.lua** inside, but it's not openable via the app. What's the intended process for macOS?

`function lovr.draw()
  lovr.graphics.print('hello world', 0, 1.7, -3, .5)
end`

**Comment by microspino** [comment]
Same here. Tried dragging the parent folder onto the lovr.app without luck. Would love to try it.

**Comment by microspino** [comment]
UPDATE, I achieved to run a hello world this way:

```
cd /Applications/LÖVR.app/Contents/MacOS
./lovr ~/path/to/the/parent/folder/of/main.lua
```

**Comment by bjornbytes** [comment]
The Getting Started guide has been updated to mention how to run a project on macOS and Linux.  Thanks for filing this!
