### ISSUE TITLE
Oculus 2 quest crash: lovr-docs/examples/Interaction/Physics_Pointer/main.lua

### ISSUE THREAD

**Issue by trevlovett** [bjornbytes/lovr#469]
hello-world runs ok but I get a crash running this example. I have pasted the logcat errors below:

8-09 18:23:17.498  2027 21641 E AppInternalConverter: Item Zorbic is not supported, latest_supported_binary is null.
08-09 18:23:17.498  2027 21641 E com.oculus.library.model.ComfortRating: Cannot parse comfort rating: null
08-09 18:23:18.364   736 21597 E FrameSetDispatcher: [HAND] Client: Failed to read from receive FMQ for packet ID: 5621105.
08-09 18:23:18.364   736 21597 E FrameSetDispatcher: This probably means this client is taking more than 33 ms to process this frame.
08-09 18:23:18.364   736 21597 E FrameSetDispatcher: Retrying.
08-09 18:23:18.671  3685  3746 E RCTVR_HERMES: [error]: 'Library', [ 'Improper entitlement: invalid comfort rating = UNKNOWN' ]
08-09 18:23:18.673  3685  3746 E RCTVR_HERMES: [error]: 'Error while generating extraLogParams', [Error: You may not call store.getState() while the reducer is executing. The reducer has already received the state as an argument. Pass it down from the top reducer instead of reading it from the store.]
08-09 18:23:19.652  3285  3353 E memtrack: Couldn't load memtrack module
08-09 18:23:23.921 21663 21663 E org.lovr.app: Unknown bits set in runtime_flags: 0x8000
08-09 18:23:24.778  3285  3285 E [SUI] AnytimeUIPanelAppBase: Release ViewModel called on already destroyed ViewModelnull
08-09 18:23:24.782  3285  3285 E [SUI] AnytimeUIPanelAppBase: ViewModel not released DestinationUIV2ViewModel
08-09 18:23:24.987 21663 21694 E TREX    : Package 'com.oculus.superres' was not found!
08-09 18:23:24.987 21663 21694 E TREX    : Package com.oculus.superres has an invalid signature!
08-09 18:23:24.987 21663 21694 E TREX    : Skipping load of package com.oculus.superres due to an invalid signature!
08-09 18:23:25.034  2027 21664 E AppInternalConverter: Item Zorbic is not supported, latest_supported_binary is null.
08-09 18:23:25.034  2027 21664 E com.oculus.library.model.ComfortRating: Cannot parse comfort rating: null
08-09 18:23:25.871   811   811 E crash-reporter: CrashUtils::AddPackageInfo: failed to get version name for process org.lovr.app: Status(-129, EX_TRANSACTION_FAILED): '-2147483640: '
08-09 18:23:25.877 21663 21694 F libc    : Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x71dc33c9f8 in tid 21694 (Thread-2), pid 21663 (org.lovr.app)
08-09 18:23:25.904 21713 21713 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-09 18:23:25.904 21713 21713 F DEBUG   : Build fingerprint: 'oculus/hollywood/hollywood:10/QQ3A.200805.001/17692500235300000:user/release-keys'
08-09 18:23:25.904 21713 21713 F DEBUG   : Revision: '0'
08-09 18:23:25.904 21713 21713 F DEBUG   : ABI: 'arm64'
08-09 18:23:25.904 21713 21713 F DEBUG   : Timestamp: 2021-08-09 18:23:25-0400
08-09 18:23:25.904 21713 21713 F DEBUG   : pid: 21663, tid: 21694, name: Thread-2  >>> org.lovr.app <<<
08-09 18:23:25.904 21713 21713 F DEBUG   : uid: 10097
08-09 18:23:25.904 21713 21713 F DEBUG   : signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x71dc33c9f8
08-09 18:23:25.904 21713 21713 F DEBUG   :     x0  000000723089e820  x1  0000000000000003  x2  d1361c47597a84ff  x3  00000071dc230779
08-09 18:23:25.904 21713 21713 F DEBUG   :     x4  00000071dc2f7e40  x5  656e657261746f72  x6  ff716e736071646d  x7  7f7f7f7f7f7f7f7f
08-09 18:23:25.904 21713 21713 F DEBUG   :     x8  bb2adaf0e990c2c3  x9  dac2288bc4cc6717  x10 3ffdac2288bc4cc6  x11 3fb999999999999a
08-09 18:23:25.904 21713 21713 F DEBUG   :     x12 000000000397fff0  x13 000000000000004b  x14 00000000000003c1  x15 0000000000000004
08-09 18:23:25.904 21713 21713 F DEBUG   :     x16 00000071dc3179e0  x17 00000071dc25fcf4  x18 00000071daf80000  x19 0000007239ed34f8
08-09 18:23:25.904 21713 21713 F DEBUG   :     x20 000000723089e820  x21 0000007239ec1550  x22 0000007239ec13e0  x23 0000007239ed34f8
08-09 18:23:25.904 21713 21713 F DEBUG   :     x24 fff9000000000000  x25 00000000fff90000  x26 ffffffffffffffff  x27 0000007239ed5de0
08-09 18:23:25.904 21713 21713 F DEBUG   :     x28 0000007239ed5d48  x29 00000071dbd40b50
08-09 18:23:25.904 21713 21713 F DEBUG   :     sp  00000071dbd40b40  lr  00000071dc2f8ba8  pc  00000071dc33c9f8
08-09 18:23:26.048 21713 21713 F DEBUG   :
08-09 18:23:26.048 21713 21713 F DEBUG   : backtrace:
08-09 18:23:26.048 21713 21713 F DEBUG   :       #00 pc 00000000000129f8  [anon:.bss]

**Comment by bjornbytes** [comment]
Sorry about the delay.  It's possible that this has since been fixed, I'm not seeing any issues with the physics pointer example on a Quest 1.  Please reopen if you still get the crash.
