### ISSUE TITLE
Calling audio.getDevices() causes crash

### ISSUE THREAD

**Issue by wangell** [bjornbytes/lovr#473]
I'm trying to integrate lua-deepspeech and I'm running into a crash when calling audio.getDevices() to get access to the microphone:

Assertion 'm->state == STATE_PASSIVE' failed at pulse/mainloop.c:787, function pa_mainloop_prepare(). Aborting.
Aborted (core dumped)

Using a fresh Ubuntu 20.04 install.  Playing audio works as normal.

**Comment by bjornbytes** [comment]
I was able to reproduce this.  FWIW it doesn't occur on the `dev` branch (that branch switched from PulseAudio to ALSA).  So I guess it will be fixed in the next release.

**Comment by wangell** [comment]
Just tried dev branch - can confirm that it fixes the issue. Thanks!
