### ISSUE TITLE
glTF color don't work with shaders.

### ISSUE THREAD

**Issue by brainrom** [bjornbytes/lovr#476]
I'm trying to use glTF models with colors in object instead of textures. Without shaders, colors looks exactly as in model, but in
 `vec4 color(vec4 graphicsColor, sampler2D image, vec2 uv)` I haven't this color, 
not in `vec4 graphicsColor` nor in `sampler2D image`.
If I draw a 1x1 texture with exact color, it works, but it's only a workaround.

**Comment by bjornbytes** [comment]
The default shader does this:

```glsl
  return graphicsColor * lovrDiffuseColor * lovrVertexColor * texture(image, uv);
```

`lovrDiffuseColor` corresponds to the `baseColorFactor` in the glTF material, and `lovrVertexColor` corresponds to the `COLOR_0` attribute in the Model.  The `Shader` page on the docs describes the built in variables, including all of the other material properties in case you need those.
