### ISSUE TITLE
callback for button presses like lovr.keypressed?

### ISSUE THREAD

**Issue by trevlovett** [bjornbytes/lovr#477]
A callback for controller button presses would be nice if it offers a lower-latency way of grabbing input vs. checking in lovr.update. I'm working on a VR music application and the latency of checking presses in lovr.update is too high.

**Comment by bjornbytes** [comment]
Unfortunately VR APIs like OpenXR don't provide an event-based means of checking for input, you can only poll for input states (I don't really understand why this is the case).  Also, events like `lovr.keypressed` are still only polled at the beginning of a frame, so events wouldn't really reduce latency here.

One thing that OpenXR does expose is "lastChangeTime" -- the time when the button was last pressed/released.  This could maybe be used to do some prediction to hide latency (interpolating poses/colliders forward/backward, seeking in an audio source, etc.).  LÖVR doesn't expose that currently but maybe it could be e.g. a second return from `lovr.headset.isDown`.
