### ISSUE TITLE
Lovr doesn't appear in Windows MR headset

### ISSUE THREAD

**Issue by shawty** [bjornbytes/lovr#479]
Hi, sorry if this is not the correct place to ask this, but currently trying Lovr with a Windows Mixed reality headset (Lenovo Explorer to be Exact)

Lovr runs and works ok with every sample I try, and it loads up Steam VR etc, but the actual output appears in a dual view window on my desktop, and not inside the goggles on the VR headset itself.

It seems to understand that the headset is there, because if I move my head, the desktop app tracks the movement, in the VR helmet however, all I see is the circular steam VR playfield with the mountains in the background, and a loading panel with "Lovr" written in the middle, and "waiting..." in the black space underneath.

It does this with everything I try from the samples, and also the tutorials.

Is there some settings or command line switches or something I need to make it work correctly?

Cheers
Shawty

**Comment by bjornbytes** [comment]
Do other OpenVR applications render inside the headset properly?

**Comment by shawty** [comment]
Yes they do, no problems.

Also, if steamvr + mr portal are running, and I use the desktop view to control my windows desktop inside VR, when I drag a Lovr folder onto the lovr icon, steam VR pops up a small dialog with the following message on:

"please plug your headset into the same graphics card as your primary monitor"

**Comment by shawty** [comment]
While researching this, I came across this:

https://gist.github.com/peteristhegreat/e4503e9cb08484eb91d7571c54a9f7a6

This is exactly what I see if I run Lovr once everything is loaded.

**Comment by shawty** [comment]
I have to leave the PC for now, I may be back later on, where I will continue to research this

**Comment by sangohan** [comment]
> "please plug your headset into the same graphics card as your primary monitor"

i think i worked out what causes this. I had my HTC vive plugged into my nvidia 3070, but my monitor plugged into my intel integrated graphics card. When you start an application, windows "chooses" what sort of graphics performance the app should get, and in this case, the default is the same graphics card as the monitor. Obviously, the intel graphics card can't do VR. 

You can change an application's graphics performance mode, see these instructions from https://petri.com/change-windows-10-graphics-settings-to-solve-display-problems-on-devices-with-dual-gpus

```
Graphics performance preference settings

To change the graphics processor preference settings for an application, you need to go to Graphics settings in the Settings app.

    Open the Settings app in Windows 10 using WIN+I.
    In the Find a setting box, type graphics and select Graphics settings from the list.
    In the dropdown menu below Graphics performance preference, select either Desktop app or Microsoft Store app, depending on the kind of app for which you want to set a preference.
    If you selected Microsoft Store app, then choose the app from the dropdown menu and click Add.
    If you selected Desktop app, then click Browse and find the runtime for the app you want to configure. Usually these will be an .exe file somewhere in the Programs Files or Program Files (x86)

```

**Comment by shawty** [comment]
@sangohan - thanks, I'll give that a try at the weekend, in "Day-job mode" at the moment, unfortunately ....

**Comment by shawty** [comment]
Hi, finally got around to testing @shangohan's comment above and problem is solved.

It seems to be the case that even WITH the headset plugged in and visible by steam etc, that windows favours the intel graphics by default for most apps.

Forcing the setting as described above fixes this.

I have to say though, that using the intel graphics for testing actually does work well, what I'm finding is while I develop my Lovr programs, I'm doing so using the intel graphics, output in a twin window on the desktop, then finally putting them on the hardware when I'm happy they are all ok.

We can close this now as I suspect it's not really an issue, although might be worth mentioning this in the documentation esp for new users.

Cheers
Shawty

**Comment by bjornbytes** [comment]
A cool part about moving to OpenXR and Vulkan is that OpenXR is able to tell Vulkan which graphics device to use, so this sort of problem should be solved soon.  Glad to hear it's figured out.

**Comment by shawty** [comment]
Yep, so now I can concentrate on why I want to use Lovr now :-)

And that's to port this:

![image](https://user-images.githubusercontent.com/1876454/133294069-b0181604-1b66-484b-8fe9-7d14bf06b7e3.png)

From Blitz Basic 3D.

(It's a model of the old Steel Factory where I live, created for our local history group, can't wait to get it into Lovr)

Thanks for the assist.
