### ISSUE TITLE
Mesh:setVertices(vertices, 0) segfaults

### ISSUE THREAD

**Issue by monolifed** [bjornbytes/lovr#494]
It is erroneous but it shouldn't cause a segfault.

**Comment by bjornbytes** [comment]
I properly got an error when trying to reproduce this, do you have any more specifics?  (I'd like to improve the error message here though -- it says that the vertex index "overflowed" which isn't correct).

**Comment by monolifed** [comment]
```lua
local mesh = lovr.graphics.newMesh({{'lovrPosition', 'float', 2}}, 3)
mesh:setVertices({{0,0}, {1,1}}, 0)
```
This code causes a segfault for me

**Comment by bjornbytes** [comment]
Thanks, it's fixed now.
