### ISSUE TITLE
Error when compiling with OpenXR

### ISSUE THREAD

**Issue by viX-shaw** [bjornbytes/lovr#514]
channel.c
C:\Users\Vivek\Projects\LOVR_DEV\lovr\deps\openxr\include\openxr/openxr_platform.h(394,5): error C2061: syntax error: i
dentifier 'IUnknown' (compiling source file C:\Users\Vivek\Projects\LOVR_DEV\lovr\src\modules\headset\headset_openxr.c)
 [C:\Users\Vivek\Projects\LOVR_DEV\lovr\build\lovr.vcxproj]
C:\Users\Vivek\Projects\LOVR_DEV\lovr\deps\openxr\include\openxr/openxr_platform.h(395,13): error C2143: syntax error:
missing '{' before '*' (compiling source file C:\Users\Vivek\Projects\LOVR_DEV\lovr\src\modules\headset\headset_openxr.
c) [C:\Users\Vivek\Projects\LOVR_DEV\lovr\build\lovr.vcxproj]
C:\Users\Vivek\Projects\LOVR_DEV\lovr\deps\openxr\include\openxr/openxr_platform.h(396,1): error C2059: syntax error: '
}' (compiling source file C:\Users\Vivek\Projects\LOVR_DEV\lovr\src\modules\headset\headset_openxr.c) [C:\Users\Vivek\P
rojects\LOVR_DEV\lovr\build\lovr.vcxproj]

**Comment by bjornbytes** [comment]
Are you compiling for windows on a windows machine?  Which version?

**Comment by viX-shaw** [comment]
Yes, Windows 10

**Comment by bjornbytes** [comment]
https://github.com/KhronosGroup/OpenXR-SDK-Source/issues/237

Seems like the line [here](https://github.com/bjornbytes/lovr/blob/master/src/modules/headset/headset_openxr.c#L13) should have `#include <unknwn.h>` added above/below.

**Comment by bjornbytes** [comment]
Should be fixed now
