### ISSUE TITLE
Texture width 16384 exceeds max of 16384

### ISSUE THREAD

**Issue by weex** [bjornbytes/lovr#518]
Running lovr built from `master` on Mac. Attempted to load a large texture for the skybox and got this error. Maybe an off-by-one error?

```
Error:
Texture width 16384 exceeds max of 16384

Stack:
main.lua:16: in function 'load'
boot.lua:184: in function <boot.lua:181>
[C]: in function 'xpcall'
```

This isn't urgent for me as I have a smaller one I'll be going with, but wanted to log it here.

**Comment by bjornbytes** [comment]
This indeed looks like an off by one error.  Fixed in 599bbc5cf4ce60cdc534cc88fae6485a042cdad6.  Thanks!
