### ISSUE TITLE
Clarity tweak for Getting Started page

### ISSUE THREAD

**Issue by KelseyHigham** [bjornbytes/lovr#519]
Hi! I'm working through the Getting Started page, and I was tripped up by this paragraph:

> On macOS and Linux, the project can be run by running the `lovr` executable with the path to the project as an argument (on macOS, the executable is located at `LÖVR.app/Contents/MacOS/lovr`).

I assumed I had to pass in the `main.lua` file, rather than the project folder. It didn't work, I got the `Unable to read VR Path Registry` error, and I started researching that error instead of `No game :(`. 

I recommend adding a word:

> On macOS and Linux, the project can be run by running the `lovr` executable with the path to the project **_folder_** as an argument (on macOS, the executable is located at `LÖVR.app/Contents/MacOS/lovr`).

**Comment by bjornbytes** [comment]
Thanks for the suggestion.  I made the change in commit `3864010` over at [lovr-docs](https://github.com/bjornbytes/lovr-docs)
