### ISSUE TITLE
Improving the noise function

### ISSUE THREAD

**Issue by jmiskovic** [bjornbytes/lovr#527]
The noise1234 that LOVR uses is a Perlin noise, which has problems in some situations.

When zoomed out, the noise has obvious artifacts in form of horizontal and vertical lines:
![image](https://user-images.githubusercontent.com/17770782/152642640-994ab88e-aef3-4c95-a5ae-fe842df02bfb.png)

Also, when computed far away from origin (for example `x + 1e7`), the output becomes blocky / pixelated:
![image](https://user-images.githubusercontent.com/17770782/152642683-9aa4a4ce-8ebb-4ee1-9aa7-a4fc7acabdac.png)

Another minor point: even though it advertises output between 0 and 1, in practice the computed values don't go outside the 0.11 to 0.89 range.

The CPML contains a LuaJIT [implementation](https://github.com/excessive/cpml/blob/master/modules/simplex.lua) of simplex noise which I found to be superior to LOVR's C implementation. The Simplex noise is considered superior to Perlin noise, and its patent has recently expired.

The LuaJIT version doesn't exhibit any of the mentioned artifacts, the output looks good under all testing conditions. It is also much faster, about **x10 times** in a naive for-loop test. Its output covers the whole -1 to 1 domain. 

![image](https://user-images.githubusercontent.com/17770782/152643717-f0bc8fad-c4b3-4e89-813c-799e9df17410.png)
The LOVR noise is on the left, the simplex noise is on the right.

Both implementations derive from Stefan Gustavson's work. One notable difference is that Simplex noise doesn't output constant value for integer coordinates.

---

Aside from improving the base noise function, it would be really nice if LOVR could provide a GLSL version of noise1234 which would behave the same as CPU version. This would allow users to switch from Lua implementation to shader implementation, re-using the constants for noise scaling and offset, and still generating the same output.

**Comment by jmiskovic** [comment]
This is the code I used to generate and visualize the noise:

```Lua
local simplex = require'simplex'

local noise_scale = 0.02
local c1 = lovr.graphics.newCanvas(1024, 1024)
local i1 = c1:newImage()
local t1 = c1:getTexture()
local m1 = lovr.graphics.newMaterial(t1)
local min, max = math.huge, -math.huge

local function recomputeLovrNoise(offset)
  for x = 0, i1:getWidth() - 1 do
    for y = 0, i1:getHeight() - 1 do
      local v = lovr.math.noise(offset + x * noise_scale, y * noise_scale)
      --v = math.atan((v - 0.5) * 4) * 0.5 + 0.5
      i1:setPixel(x, y, v, v, v, 1)
    end
  end
  t1:replacePixels(i1)
end

local c2 = lovr.graphics.newCanvas(1024, 1024)
local i2 = c2:newImage()
local t2 = c2:getTexture()
local m2 = lovr.graphics.newMaterial(t2)

local function recomputeSimplexNoise(offset)
  for x = 0, i2:getWidth() - 1 do
    for y = 0, i2:getHeight() - 1 do
      local v = simplex(offset + x * noise_scale, y * noise_scale)
      min, max = math.min(min, v), math.max(max, v)
      v = v * 0.5 + 0.5
      i2:setPixel(x, y, v, v, v, 1)
    end
  end
  t2:replacePixels(i2)
end

recomputeLovrNoise(0e7)
recomputeSimplexNoise(0e7)


function lovr.draw()
  lovr.graphics.setShader()
  lovr.graphics.plane(m1, -3, 1.5, -5, 5, 5)
  lovr.graphics.plane(m2,  3, 1.5, -5, 5, 5)
end
```

**Comment by bjornbytes** [comment]
I appreciate the detailed issue.  Let's do it!  Stuff I'm going to experiment with

- [simplexnoise1234](https://github.com/stegu/perlin-noise/blob/master/src/simplexnoise1234.c)
- [open-simplex-noise-in-c](https://github.com/smcameron/open-simplex-noise-in-c)
- [stb_perlin](https://github.com/nothings/stb/commit/59e7dec3e8bb0a8d4050d03c2dc32cf71ffa87c6)
- Porting [Noise.lua](https://weber.itn.liu.se/~stegu/simplexnoise/Noise.lua) (the cpml one) to C?

Switching from stb to perlin is a big change, but given that the function is `lovr.math.noise` and doesn't specify the type of noise, I think this is okay.  I've heard that simplex noise can have some artifacts that aren't present in perlin noise though, so I'll be looking out for those.

Regarding shader noise: I think baking it into a texture and sampling that is the way to go (for performance and ensuring compatibility between lovr.math.noise and the shader result), but lovr wouldn't know whether you want 1D/2D/3D and what kind of resolution you want, so it might be better if this is implemented per project.  People may also want to use other types of noise or pseudo-random sequences in shaders.

**Comment by jmiskovic** [comment]
One more interesting noise function - [PSRDnoise](https://stegu.github.io/psrdnoise/2d-tutorial/), the latest from Gustavson. It has capability to be periodic if needed, which is great for tiling textures and for generating temporally periodic signals. The function also calculates the gradient at each point which I can think many uses for.

**Comment by bjornbytes** [comment]
It may also be a good idea to use doubles for the noise computation.

**Comment by bjornbytes** [comment]
- Using doubles doesn't improve the range/pattern of the noise (didn't check if it gave a speedup)
- Using simplexnoise1234 provides a better result that looks almost identical to the LuaJIT implementation.  It doesn't seem to produce as many artifacts and runs at the same speed.  However, the range is from .05 - .95 with both floats and doubles.  May be related to the integer hashing.
- psrdnoise looks awesome.  It's only 2D and 3D but has the `angle` parameter for animating across time.  The tutorial raises a good point that it's probably faster to compute it in the shader rather than using texture bandwidth for a noise texture.  Maybe it would be worth porting it back to the CPU (or seeing if `srdnoise23` provides identical results).  Even though it's 3D/4D it's probably possible to make 1D/2D versions that omit some of the parameters, to avoid breaking the API.  The gradients are a nice bonus as well.

**Comment by bjornbytes** [comment]
For now I've switched to simplex noise because it's a big improvement and fixes the problems raised here.  Going to keep thinking about psrdnoise though.

**Comment by jmiskovic** [comment]
Awesome, thank you.
