### ISSUE TITLE
Incorrect documentation for Vec4

### ISSUE THREAD

**Issue by jumpsplat120** [bjornbytes/lovr#528]
The documentation found for [Vec4:unpack](https://lovr.org/docs/v0.15.0/Vec4:unpack) shows it returning 3 values instead of 4, both in the example, and in the return space.

**Comment by bjornbytes** [comment]
Fixed [here](https://github.com/bjornbytes/lovr-docs/commit/460b954143b298a580ef3f7bffff2fc621545f3f), thanks!
