### ISSUE TITLE
If using adb push on Quest 2, t.headset.supersample is erroneously set to true by default

### ISSUE THREAD

**Issue by KelseyHigham** [bjornbytes/lovr#534]
It may be overridden by the [nogame conf.lua](https://github.com/bjornbytes/lovr/blob/master/src/resources/boot.lua#L4-L9). `t.modules.audio` and `t.modules.physics` don't appear to be overridden by that code, because they still work.

---

Sample project that should run at 72fps, but drops to ~61fps when you look at a plane with a background color set:

```lua
function lovr.load(t)
	lovr.graphics.setBackgroundColor(0, .5, 1)
end

function lovr.draw()
	lovr.graphics.setColor(.5, .5, .5)
	lovr.graphics.plane("fill", 0, 2, -2, 10, 10)

	lovr.graphics.setColor(1,1,1)
	lovr.graphics.print(lovr.timer.getFPS(), 0, 2, -1.5)
end
```

This project runs at 72fps if `supersample` is set to false.
This project runs at 72fps if you sleep and wake the headset while the app is running, I suspect because that causes the home environment to unload.

**Comment by bjornbytes** [comment]
The conf.lua in the build contains this

```lua
function lovr.conf(t)
  t.headset.supersample = true
end
```

So I think this can be merged with #533, since there is now an explanation for why the audio/physics modules still work.
