### ISSUE TITLE
Text rendering is garbled now

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#54]
This sample program
```
function lovr.draw(eye)
  local s = string.format("%s\n%d controllers", eye, lovr.headset.getControllerCount()) 
  for i,controller in ipairs(lovr.headset.getControllers()) do
    s = string.format("%s\n%d: %s %s %1.1f, %1.1f", s, i, controller:isTouched("touchpad") and "Y" or "N", controller:isDown("touchpad") and "Y" or "N", controller:getAxis("touchx"), controller:getAxis("touchy"))
  end

  lovr.graphics.print(s, 0, 2, -3, .5)
end
```

prints information about the current controllers. If you run this and move your fingers back and forth on the vive touchpad on current lovr master, the text becomes garbled eventually.

The example uses multiline rendering, but the problem can be reproduced without newlines.

![image](https://user-images.githubusercontent.com/277318/45897610-9dd47480-bda5-11e8-9078-6a64bdd4b10b.png)

**Comment by bjornbytes** [comment]
This is fixed now!  It was an edge case related to the number of characters being printed.
