### ISSUE TITLE
Expose collision contact info

### ISSUE THREAD

**Issue by bjornbytes** [bjornbytes/lovr#541]
`World:collide` currently returns a boolean indicating whether the shapes collided.  More specifically, it indicates whether there were any contact points between the two shapes.  However, those contact points have a lot of extra useful info!  It would be really neat to know *where* on the shapes the collisions took place, the normal vectors of those contact points, etc.  ODE is already giving us all this info, so it would be as simple as returning it in a table or exposing it from a callback/iterator interface.

There are lots of places to go from here, like allowing people to filter the contacts, create contact joints manually, set per-contact friction/restitution, and maybe more.  But starting with the raw info would power lots of cool things that aren't possible right now.

**Comment by KelseyHigham** [comment]
Returning a table of contact points from `World:collide`:
- you can easily check the #length of the table, which might be useful?

Supplying a callback to `World:collide`:
- consistent with `World:raycast`

I think a callback might imply "this is a collision event, like you've seen in other engines", and it might be confusing to people that it can be called multiple times, in one frame, for one collision between two objects. 

I have a slight preference for returning a table. I also wouldn't mind just doing both.

**Comment by bjornbytes** [comment]
I sketched out the following change

- Remove `World:collide`, `World:computeOverlaps`, `World:overlaps`, and the `World:update` callback.
- Add `World:get/setContactFilter` (name very TBD)
  - This is a function you can optionally set that will get called when `World:update` wants to create a contact.
  - It gets passed `shapeA, shapeB, x, y, z, nx, ny, nz, depth`
  - It should return `collide, friction, bounce` to control whether/how the collision happens (replaces `:collide`).

It's a breaking change, but I think it has some advantages over the current API:

- Easier to use (just set a callback when creating the world, no need to call overlaps/computeOverlaps/collide).
- Less confusion about how :collide interacts with :update.
- Exposes all of ODE's contact info.

Disadvantages are that it's a breaking change, and it calls a callback more often.

**Comment by bjornbytes** [comment]
After thinking about it more, the above idea doesn't make it easy enough to ask "what are the contacts between 2 colliders/shapes".

**Comment by bjornbytes** [comment]
This is implemented as `World:getContacts` now.  It takes 2 shapes and returns a table of contacts, where each contact is a table with the position, normal, and overlap depth.  This does mean that the collision test gets duplicated if you also need to collide the 2 shapes, but I think that's okay for now.
