### ISSUE TITLE
setFlipEnabled changes winding

### ISSUE THREAD

**Issue by monolifed** [bjornbytes/lovr#546]
In my 2d library with flipped-y and setFlipEnabled(true) fonts keep their winding as counter-clockwise
But all the other meshes change from counter-clockwise to clockwise
So culling must be disabled to make everything visible

Is this the intended behavior?

**Comment by bjornbytes** [comment]
This is not the intended behavior.  I don't think the function will be needed anymore with Vulkan, but in the meantime [this](https://github.com/bjornbytes/lovr/blob/master/src/modules/graphics/font.c#L172-L179) could maybe be changed to add the vertices in a different order when flip is enabled.
