### ISSUE TITLE
`lovr.graphics.fill()` permanently disables depth test for all subsequent commands

### ISSUE THREAD

**Issue by KelseyHigham** [bjornbytes/lovr#564]
In this sample code, `flush()` and `setDepthTest()` both do nothing when enabled. `skybox()` works as expected.

```function lovr.draw()
  lovr.graphics.setColor(0, 0, 0)
  lovr.graphics.fill()
  -- lovr.graphics.flush()
  -- lovr.graphics.setDepthTest('lequal', true)
  lovr.graphics.setColor(.5, .5, .5)
  lovr.graphics.cube('fill', 0, 1.7, -2)
  lovr.graphics.setColor(1, 1, 1)
  lovr.graphics.cube('fill', 0, 1.7, -3)
end
```
0.15.0
![image](https://user-images.githubusercontent.com/286211/170384234-34641bba-0b69-4db1-9585-6577cc716f6a.png)

(Also, `fill()` doesn't seem to perform depth tests (e.g. for drawing a sky after drawing geometry), but I wasn't sure if this was by design.)

**Comment by bjornbytes** [comment]
This was fixed in https://github.com/bjornbytes/lovr/commit/053c3189953eb493b0f8030f5dac246ae2292bff

**Comment by bjornbytes** [comment]
Also `fill` is currently designed to go on top of everything else.  There have been times when I've wanted both "in front of everything" and "behind everything" though.
