### ISSUE TITLE
unprotected exception if negative values are provided as w/h/d for a collider / box shape / etc

### ISSUE THREAD

**Issue by chadvandy** [bjornbytes/lovr#567]
As it says on the tin - 100% fault on my end but I accidentally calculated the negative value of width instead of using the absolute value of width, and supplying a negative value to the w/h/d parameters of World:newBoxCollider() causes an immediate crash without any handled exceptions.

**Comment by bjornbytes** [comment]
Fixed in fbe54d5.  Thanks!
