### ISSUE TITLE
Possibly build glslangValidator before shader compilation

### ISSUE THREAD

**Issue by lun-4** [bjornbytes/lovr#579]
As communicated in Slack before opening this issue, the Vulkan merge means that CMake uses the system's `glslangValidator` executable, even though `glslang` is vendored in the source tree. It would be welcome to build that and use the vendored executable to prevent system inconsistencies (my system's `glslang` is 8.13.3743, which is over 2 years ago, and so, incompatible with the CMake script's usage of glslangValidator, for example).

Leaving it as an issue just in case someone gets unfortunate enough to have the same problem. :P

**Comment by Calandiel** [comment]
Yeah, this should really either be mentioned in the building instructions in documentation or rely on the vendored executable.
