### ISSUE TITLE
lovr.system.isKeyDown() not working

### ISSUE THREAD

**Issue by Actravaz** [bjornbytes/lovr#580]
I followed exactly what the document said but there's an error that says attempt to call field isKeyDown (is nil)

here's the code:
`if lovr.system.isKeyDown("w") == true then
    camy = camy - 0.01
 end`

**Comment by jmiskovic** [comment]
This function was added to the nightly version and doesn't exist on stable
release v0.15.0.

If you want to stay on stable version, there is lovr-keyboard library which
has isDown() function.

**Comment by Actravaz** [comment]
The library worked, Thanks!
