### ISSUE TITLE
Setting Source's pitch

### ISSUE THREAD

**Issue by akabomb-prog** [bjornbytes/lovr#583]
Audio Sources do not have a setPitch method or similar for setting the playback rate of a sound, which is very useful if, for example, using one sound to be played with different pitches for variety.

Sound data that has a different playback rate can probably be generated for use in a Source, but that has to be done before a Source is created, which does not let you modulate the pitch in real-time.

**Comment by bjornbytes** [comment]
`Source:setPitch` was added 10 days ago in d8c23bacec733482afbf56fd57749132de14aa8d, look for it in the next release!

**Comment by akabomb-prog** [comment]
Oh, good to know!
