### ISSUE TITLE
Add support for blend shapes/shape keys

### ISSUE THREAD

**Issue by Calandiel** [bjornbytes/lovr#586]
I haven't seen an issue opened about it and I believe it's a major missing feature. It's extremely difficult to do, say, facial expressions without them and they're often used in animations in a corrective role.
Any thoughts on their place in LOVR? I'd be open to working on them myself if you accept pull requests on such features. I believe some rudimentary support shouldn't be too difficult to get going.

**Comment by bjornbytes** [comment]
Super interested in adding these (esp. for VRM).  My vague plan would be to expand the animation compute shader (`etc/shaders/animator.comp`) to manipulate the vertices using the blendshapes, or potentially write a new compute shader for it.  If you have experience with this or want to try taking a stab at it, that would be awesome!

**Comment by bjornbytes** [comment]
Oh, we would also need to figure out the Lua API

**Comment by bjornbytes** [comment]
On the train I thought about it more and broke it down into some rough TODOs

- [ ] ModelData Blend Shape Structs/Schema
- [ ] ModelData Animation Property for Weights
- [ ] glTF Sparse Accessors
- [ ] glTF Blend Shape Loading (targets, weights)
- [ ] Model has array of weights for each node (number per node is not constant!)
- [ ] lovrModelCreate loads blend shapes into GPU buffers in some arrangement
- [ ] lovrModelAnimate can animate node weights
- [ ] lovrModelReskin (maybe renamed to UpdateVertices) dispatches compute shader to do blend shapes
- [ ] Lua API for Model:get/setNodeWeight(s)

glTF does not technically support blend shape names but there is a common convention for them, so they can probably be loaded.

Seems the hard part remaining for my understanding is the GPU layout for everything (how the shapes are arranged into buffers and how the compute shader will access them).  A few different ways to do it.

**Comment by bjornbytes** [comment]
Just got blend shapes working on the `blendshapes` branch!  The API matches the initial suggestion:

- `Model:getBlendShapeCount`
- `Model:getBlendShapeName`
- `Model:getBlendShapeWeight(name|index)`
- `Model:setBlendShapeWeight(name|index, weight)`

There is no limit on the number of blend shapes, and the weights can be animated using the existing animation system.  Still doing some testing/optimization/fixes on the branch, but it's working with the glTF sample models.
