### ISSUE TITLE
Oculus and OpenVR headset drivers are 180 degrees rotated from each other

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#59]
I am using the sept 11 master. I build two versions, one using -DLOVR_OCULUS_PATH and thus using OculusVR SDK and the other defaulting to OpenVR. I run the same test program in both of them.

They are 180 degrees off from each other. If I face my monitor and run the test program, in the OpenVR mode the scene renders behind me, and if I do this in OculusVR mode the scene renders in front of me. Otherwise everything works correctly in both modes.

Expected behavior: The scene should appear identical in both OpenVR and OculusVR.

**Comment by bjornbytes** [comment]
Were you able to confirm that apps run via OpenVR/Steam had the same forward direction as apps run from the Oculus app?  Is there a chance that the two runtimes had their play spaces configured such that they were facing opposite directions?

**Comment by bjornbytes** [comment]
Both [OpenVR](https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L40) and [LibOVR](https://developer.oculus.com/reference/libovr/1.20/structovr_posef/) think they return coordinates in a right-handed coordinate system.  So a conversion shouldn't be necessary.

**Comment by mcclure** [comment]
This issue is completely wrong. In fact, what happens is that the Vive *calibration program* orients the playfield away from the monitor and the Oculus *calibration program* orients it toward (in both cases, on purpose). So I simply had my Vive calibrated an opposite direction than I thought I did and Lovr was doing the correct thing. Sorry!
