### ISSUE TITLE
Crash when resizing window

### ISSUE THREAD

**Issue by akabomb-prog** [bjornbytes/lovr#591]
I'm trying to create a resizable window in LOVR. Here's the whole `conf.lua`:
```lua
function lovr.conf(t)
    t.window = {
        width = 1280,
        height = 720,
        resizable = true
    }
end
```
The window size is correct, but after resizing it, LOVR crashes with this console output:
```
Error:
GPU error: Queue present failed

Stack:
boot.lua:141: in function <boot.lua:110>
[C]: in function 'xpcall'
Error occurred while trying to display another error:
GPU error: Surface image acquisition failed

Stack:
[C]: in function 'getWindowPass'
boot.lua:213: in function <boot.lua:193>
[C]: in function 'xpcall'
```
Running LOVR v0.16.0 on Windows 10.

**Comment by bjornbytes** [comment]
Should be working now, let me know if you have any issues

**Comment by akabomb-prog** [comment]
Awesome, can confirm it works!

**Comment by bjornbytes** [comment]
You're using a build from GitHub actions, right?  There hasn't been a new stable release since v0.16.0 that includes the fix yet.

**Comment by Aunarky** [comment]
Ah, got it. my bad
