### ISSUE TITLE
Inderect rendering texture are shifted by 1 line.

### ISSUE THREAD

**Issue by brainrom** [bjornbytes/lovr#593]
`renderTexture`'s top line have the data, which belongs to the bottom of the texture. It shows by a small white line at the top.
![image](https://user-images.githubusercontent.com/15963835/198386438-e2ddb93a-1961-4d48-852d-b2d1eb77d5db.png)
```
renderTexture = lovr.graphics.newTexture(512,512, {mipmaps=false, usage={"sample", "render"}})

local isRendered = false

function lovr.update()
if (not isRendered) then
    lovr.graphics.setBackgroundColor(0, 0, 0)
    local rPass = lovr.graphics.getPass('render', renderTexture)
        rPass:cube(mat4(vec3(0,-1,-2), vec3(0.5,0.5,0.5)))
    lovr.graphics.submit(rPass)
    lovr.graphics.setBackgroundColor(0, 0, 0)
    isRendered = true
end
end
function lovr.draw(pass)
    pass:setMaterial(renderTexture)
    pass:plane(mat4(vec3(0,1.5,-0.5), vec3(0.5,0.5,0)))

end
```

**Comment by bjornbytes** [comment]
The texture coordinates are wrapping on the edge.  Creating a clamping sampler (`lovr.graphics.newSampler({wrap = 'clamp'})`) and adding `pass:setSampler(sampler)` fixes it.
