### ISSUE TITLE
Calling lovr.system.openWindow outside of boot.lua causes graphics to not get drawn

### ISSUE THREAD

**Issue by akabomb-prog** [bjornbytes/lovr#602]
I noticed this when I tried to call the function in main.lua in `lovr.load()` after `t.window` was set to false in lovr.conf. After calling openWindow, the window is open and `lovr.update(dt)` still gets run, but `lovr.graphics.getWindowPass()` returns nil in update. As I understand, openWindow is called in boot.lua automatically if t.window is not set to a false-y value.
I made a project to test this issue.

# main.lua
```lua
function lovr.load()
    print("window open: ", lovr.system.isWindowOpen())

    print("calling lovr.system.openWindow")
    lovr.system.openWindow{
        width = 1280,
        height = 720,
        fullscreen = false,
        resizable = true,
        title = "custom window"
    }

    print("window open: ", lovr.system.isWindowOpen())
end

function lovr.update(dt)
    print("update(dt)", dt)
end

function lovr.draw(pass)
    print("draw(pass)", pass)
    pass:text("hello world", 0, 1.7, -5)
end
```

# conf.lua
```lua
function lovr.conf(t)
    t.window = false
end
```

# Console output
## Expected
This is with `t.window` not being modified whatsoever or being set to a table with options to pass to openWindow. "hello world" gets drawn.
```
window open:    true
calling lovr.system.openWindow
window open:    true
update(dt)      0.26455969997915
draw(pass)      Pass
update(dt)      0.013464800023939
draw(pass)      Pass
update(dt)      0.012878799985629
draw(pass)      Pass
update(dt)      0.016489100002218
draw(pass)      Pass
update(dt)      0.016752700001234
draw(pass)      Pass
update(dt)      0.01657370000612
draw(pass)      Pass
update(dt)      0.016671199991833
draw(pass)      Pass
...
```
## Outputted
This is with `t.window = false` or `t.window = nil`. The game window is a solid white, "hello world" is not drawn.
```
window open:    false
calling lovr.system.openWindow
window open:    true
update(dt)      0.21321000001626
update(dt)      0.00019109999993816
update(dt)      0.00015759997768328
update(dt)      0.0011324000079185
update(dt)      0.00035380001645535
update(dt)      0.00014009998994879
update(dt)      0.00012559999595396
update(dt)      0.00012250000145286
update(dt)      0.00011480000102893
update(dt)      0.00012229999992996
update(dt)      0.00011580000864342
update(dt)      0.00011339999036863
update(dt)      0.00011309998808429
update(dt)      0.00011350002023391
update(dt)      0.00011299998732284
...
```

**Comment by akabomb-prog** [comment]
Disabling lovr.graphics in conf.lua by doing `t.modules.graphics = false` and instead calling `love.graphics.initialize()` after opening the window (like it is in boot.lua) seems to make graphics work:
```lua
lovr.graphics = require "lovr.graphics"

function lovr.load()
    print("window open: ", lovr.system.isWindowOpen())

    print("calling lovr.system.openWindow")
    lovr.system.openWindow{
        width = 1280,
        height = 720,
        fullscreen = false,
        resizable = true,
        title = "custom window",
        icon = nil
    }

    lovr.graphics.initialize()

    print("window open: ", lovr.system.isWindowOpen())
end
```

**Comment by bjornbytes** [comment]
I think atm that's the intended behavior, it works something like this:

- When `lovr.graphics.initialize` is called, if a window is open then it will attach to it.  Otherwise, the graphics module will only be available for headless/headset rendering.
- Similarly, when `lovr.headset.start` is called, graphics module needs to be initialized.  It would be possible to start a headless VR session if graphics isn't initialized, but that isn't implemented yet.

This is all up for discussion though.  Maybe there are ways to simplify it.  At the very least there could be some more docs.

**Comment by bjornbytes** [comment]
It would be possible to improve the graphics module so that it can handle windows being opened after initialization, or being closed.  Right now it doesn't seem like a priority though.
