### ISSUE TITLE
LOVR crashes on startup

### ISSUE THREAD

**Issue by 233Neon** [bjornbytes/lovr#607]
LOVR crashes when opening the engine. I double-click LOVR.exe on Windows 11 and it just opens a white screen and crashes.
I just downloaded this, still haven't gotten it to work a day later.

![image](https://user-images.githubusercontent.com/45669952/204793347-6cb27508-d65d-48ef-b4f8-7b28ac9c47a6.png)
![image](https://user-images.githubusercontent.com/45669952/204793456-1d7b3a53-e2bc-4a47-b054-7af67ca93d88.png)

**Comment by bjornbytes** [comment]
Hi, thanks for the issue.  Can you provide a little more information?

- The headset you're using, if any, along with the VR runtime (SteamVR, Oculus, etc.)
- The GPU you're using
- If you able to run from `cmd.exe`, there might be a message in the console that helps

You may also have more luck with the nightly build.

**Comment by 233Neon** [comment]
I am using no headset, just a mouse and keyboard.
I'm using an Nvidia Geforce RTX 2060
 Nothing appears in cmd and the Nightly build also crashes.
![image](https://user-images.githubusercontent.com/45669952/204863621-a3379c50-3692-41c1-9628-e1eef73665c6.png)

**Comment by bjornbytes** [comment]
Does adding `--console` after lovr.exe print anything?

**Comment by 233Neon** [comment]
Doesn't print anything.

**Comment by bjornbytes** [comment]
Unfortunately I don't really have anything to go off of.  Other things to try might be ensuring your GPU drivers are up to date or running in a debugger to see where a crash is happening.  I'll keep an eye out to see if anyone has similar issues.

**Comment by 233Neon** [comment]
It may be due to my computer not properly supporting Vulkan. You think that's an issue?

**Comment by bjornbytes** [comment]
Yeah, because it opens the window briefly before closing that makes me think it has something to do with the graphics module, which uses Vulkan 1.1.  Do other Vulkan apps work?  The RTX 2060 should support it though.

**Comment by 233Neon** [comment]
If I try and switch to Vulkan on an emulator, like RPCS3 It crashes. It's possible Vulkan may be automatically switching to my second AMD Ryzen 7 4000 Series GPU.

**Comment by 233Neon** [comment]
Interestingly enough, Vulkan is not enabled on my laptop, no idea how to enable it.
![image](https://user-images.githubusercontent.com/45669952/205118155-0719625d-bbec-490c-ab80-adf791955f80.png)
![image](https://user-images.githubusercontent.com/45669952/205118210-72e01795-94e3-41f6-9846-ecb761180f48.png)

**Comment by 233Neon** [comment]
I figured out the issue, I needed to update my AMD Radeon Graphics Drivers on their website https://www.amd.com/en/support
Vulkan is now enabled and the engine opens properly.

**Comment by bjornbytes** [comment]
Glad to hear it!
