### ISSUE TITLE
macOS version won't start on Ventura (x86)

### ISSUE THREAD

**Issue by wolf81** [bjornbytes/lovr#615]
When downloading & installing the disk image on macOS Ventura (13.0) on my iMac (x86) I see the following error:

> You can't open the application "LÖVR" because this application is not supported on the Mac.

When trying to build from source & running the lovr binary I see the following error instead:

> Error:
> GPU error: Failed to load vulkan library
> 
> Stack:
> boot.lua:90: in function <boot.lua:4>
> [C]: in function 'xpcall'

Not sure if vulkan is not supported yet on macOS Ventura or if there's some other issue?

**Comment by bjornbytes** [comment]
MoltenVK needs to be installed to render graphics atm.  macOS builds of LÖVR might need to package MoltenVK so people don't need to have it installed.  I don't have access to macOS hardware very often so I haven't looked into this yet (how easy it is to link with, what the file size impact is, etc.).  Also see #610.

**Comment by wolf81** [comment]
@bjornbytes I installed MoltenVK now. However still getting the same issue.

I do see that OpenVR is installed now. However the file `~/Library/Application Support/OpenVR/.openvr/openvrpaths.vrpath` is empty. I tried deleting the file, but that didn't help. I am guessing this file should contain paths to some VR devices (I got none, just want to run without VR).

I recall I had this issue in the past, but can't remember how I fixed it back then. 

What is your primary dev platform? I could configure dual-boot for my Mac to get a workable environment.

**Comment by bjornbytes** [comment]
OpenVR isn't used anymore, just OpenXR, but that's completely optional.

Right now we generally have most people testing on Windows, Linux, and Android (Quest/Pico).  All of those platforms support Vulkan natively without needing the translation library.

**Comment by wolf81** [comment]
@bjornbytes Installing [VulkanSDK](https://vulkan.lunarg.com/doc/sdk/1.3.236.0/mac/getting_started.html) resolved the issue.

**Comment by bjornbytes** [comment]
I'm currently looking into bundling it with LÖVR macOS builds, but expect progress to be relatively slow.
