### ISSUE TITLE
Desktop rendering on macOS in windowed mode is constrained to 25% of the view.

### ISSUE THREAD

**Issue by wolf81** [bjornbytes/lovr#620]
In macOS, when rendering in a window (not fullscreen, no headset connected) the view is limited to 25% of the total window area.

This issue was verified in version v0.16.0 using a locally built (but unmodified) version of LOVR. 

See discussion & example image here: https://matrix.to/#/!XVAslexgYDYQnYnZBP:matrix.org/$1671371144169315aOiDS:matrix.org

**Comment by bjornbytes** [comment]
I think this line needs to use `os_window_get_fbsize` instead of `os_window_get_size`:

https://github.com/bjornbytes/lovr/blob/master/src/modules/graphics/graphics.c#L652

Initial window size doesn't take DPI into account, but after a resize it should.

**Comment by undefdev** [comment]
Couldn't  `os_window_get_fbsize` be used in general?

**Comment by bjornbytes** [comment]
Hm, what do you mean?  On high-dpi systems, the framebuffer size is different from the window size (800x600 window, 1600x1200 framebuffer).

**Comment by undefdev** [comment]
Ah sorry, that could have been a more detailed question.
I was asking to understand what a reasonable fix would be.
I made the change you suggested locally and was wondering if this is just a hotfix, or if it could be committed to master.

If the framebuffer size is different from the window size on high-dpi systems, but on non-high-dpi systems framebuffer and window size are the same, I expect that replacing `os_window_get_size` with `os_window_get_fbsize` in [graphics.c#L652](https://github.com/bjornbytes/lovr/blob/master/src/modules/graphics/graphics.c#L652) would fix the problem on high-dpi systems without breaking it on other systems.

**Comment by bjornbytes** [comment]
Yeah, it's a reasonable fix.  If someone is able to test it and verify that it fixes the macOS window then it should be merged.

**Comment by undefdev** [comment]
Cool. I tested it and created a [pull request](https://github.com/bjornbytes/lovr/pull/629).
