### ISSUE TITLE
Load module on demand?

### ISSUE THREAD

**Issue by eigenbom** [bjornbytes/lovr#632]
Curious if we can load a module (e.g., audio) manually / on demand? This is more a dev/workflow issue as enabling audio module in conf file increases startup time, and i'm not always going to play audio.

Imagining something like...
```lua
-- some event triggers this...
if not lovr.audio then
   lovr.audio = load_module("audio")
end
```

**Comment by eigenbom** [comment]
For more context i have a simple module that just wraps lovr.audio state. Typically i disable audio module in conf until i need to test an audio thing. Would be nice to have the module just boot on demand (even if it halts the app for a couple of seconds).

```lua
local M = {}

function M.setup()
	if not lovr.audio then
		log.warn("lovr.audio isn't enabled")
		return
	end
	...
end

function M.play(sound)
	if not lovr.audio then
		lovr.audio = lovr.load_module("audio") -- Load it?
		M.setup()
	end
	play_sound(...)
end

return M

```

**Comment by bjornbytes** [comment]
Yep, you can set it to false in conf.lua (`t.modules.audio = false`) and then require it (`lovr.audio = require('lovr.audio')`) later.

**Comment by eigenbom** [comment]
thx :)

**Comment by eigenbom** [comment]
confirmed this works for audio and physics modules
