### ISSUE TITLE
Universal macOS build

### ISSUE THREAD

**Issue by bjornbytes** [bjornbytes/lovr#633]
Support a universal macOS build (x86_64 and arm64) for macOS and make that the default for GitHub actions.  Currently almost works just by adding `-DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"`, but the LuaJIT fork is grumpy.  Another option might be to do separate builds and smoosh them together with `lipo`.

**Comment by Alexintosh** [comment]
Is there a way to run it on arm based macs right now?

**Comment by bjornbytes** [comment]
The latest release was accidentally made on an M1, so it actually only works on arm-based macs.  The nightly builds are made on x86_64 macs, but I think it will still work on an arm mac via emulation (Rosetta or something?)

**Comment by popey** [comment]
Actually I think it's broken on M1 too. The latest build on the website and in the releases page, both exhibit the same behaviour when run, unrunnable binary. The previous 0.15 release is an x86_64 binary which does run on M1. The 0.16 release is an arm64 build which (ironically, perhaps) does not run on M1.

**Comment by bjornbytes** [comment]
The GH actions builds now have improved MoltenVK packaging and also a reduced minimum macOS requirement.  Some people on macOS have reported that the new builds are working.

Although this issue was about doing a universal build (with both ARM64 and x86_64 code in the same binary), I don't really feel like doing that right now, and the x86 builds from GitHub actions should work on ARM macs via Rosetta.
