### ISSUE TITLE
Issue with trying to load. (missing dll)

### ISSUE THREAD

**Issue by geichelb3512** [bjornbytes/lovr#634]
When i try to load, i get error "The code execution cannot proceed because MSVCP140.dll was not found." Anyone have a fix?

**Comment by bjornbytes** [comment]
I think this means you have to install the "Microsoft Visual C++ Redistributable" package

**Comment by geichelb3512** [comment]
> Microsoft Visual C++ Redistributable

Thanks, i will try this now

**Comment by geichelb3512** [comment]
> Microsoft Visual C++ Redistributable

Woohoo! Lovr is up and running!
