### ISSUE TITLE
Problems with pushing my file to vr headset.

### ISSUE THREAD

**Issue by geichelb3512** [bjornbytes/lovr#635]
So, i pushed the lua folder that i had to the org.lovr.app/files directory, however, i still have the no game screen.
cmd says this with adb output: test.\: 1 file pushed, 0 skipped. 0.0 MB/s (73 bytes in 0.053s) so it pushed.
i did cd to this location: C:\Users\geich\OneDrive\Desktop\vr dev
the folder is at: C:\Users\geich\OneDrive\Desktop\vr dev\test
I used the adb push --sync test. /sdcard/Android/data/org.lovr.app/files command, but still have a no game screen
Do i need anything else in the lua other than the function of hello world(Thats all the game is, a hello world screen)
HELP!

**Comment by jmiskovic** [comment]
Hi! Let's first double-check that `main.lua` is in the correct place:

```
adb shell file /sdcard/Android/data/org.lovr.app/files/main.lua
/sdcard/Android/data/org.lovr.app/files/main.lua: ASCII text         <- expected output
```
(just wanted to make sure because some 'adb push' options will create a sub-dir on the device).

And that hello world is the same one from [docs example](https://lovr.org/docs/Intro/Hello_World)?

**Comment by geichelb3512** [comment]
> adb shell file /sdcard/Android/data/org.lovr.app/files/main.lua

Welp, that output never happened. i got
`/sdcard/Android/data/org.lovr.app/files/main.lua: cannot open`

**Comment by jmiskovic** [comment]
Yeah, you should move every file from 'test' dir into the 'files' directory. 

This 'files' dir is the source root for lovr and 'main.lua' must be inside, otherwise you get the no game screen.

**Comment by geichelb3512** [comment]
> Yeah, you should move every file from 'test' dir into the 'files' directory.
> 
> This 'files' dir is the source root for lovr and 'main.lua' must be inside, otherwise you get the no game screen.

It put a dot after the .lua
So after changin the dir, it still didnt work. however, after renaming it, i got hello world!

**Comment by geichelb3512** [comment]
Wait, wait wait wait wait.

**Comment by geichelb3512** [comment]
So, now that i know that i have to do that, how do i make it so that all of the folders contents get put in the right place, all at once? I dont want to have to do it one by one.

**Comment by bjornbytes** [comment]
If you have `cd`-ed into the project folder in your terminal, you should just need to run this to get everything in the right place:

```sh
adb push --sync . /sdcard/Android/data/org.lovr.app/files
```

You can also run your original command but pass your test folder as `test/.` instead of `test.` (note the slash and the dot).

**Comment by geichelb3512** [comment]
> If you have `cd`-ed into the project folder in your terminal, you should just need to run this to get everything in the right place:
> 
> ```shell
> adb push --sync . /sdcard/Android/data/org.lovr.app/files
> ```
> 
> You can also run your original command but pass your test folder as `test/.` instead of `test.` (note the slash and the dot).

Woohoo! We got a fix! Sorry i am always asking for help, i am a new dev.
