### ISSUE TITLE
How do i make it spin clockwise?

### ISSUE THREAD

**Issue by geichelb3512** [bjornbytes/lovr#636]
Hi, so i have this code
`local angle = lovr.headset.getTime(0)
pass:draw(model, 0, 0.25, -2.5, .2, angle)

`
Which spins the model counter clockwise. How would i spin it clockwise?

**Comment by bjornbytes** [comment]
You can do `-angle` to spin it the other way.

**Comment by geichelb3512** [comment]
the discord got me!
