### ISSUE TITLE
How to get sdk without android studio

### ISSUE THREAD

**Issue by geichelb3512** [bjornbytes/lovr#637]
so, the way i got the sdk is through android studio which takes too much spaxe on my conputer
how can i get the sdk seperate from android studio
i know how to get the ndk and jdk

**Comment by Angelia64** [comment]
It's mine now

**Comment by geichelb3512** [comment]
> It's mine now


What does this mean?

**Comment by bjornbytes** [comment]
You can use `sdkmanager` to install the Android SDK, NDK, etc. without using Android Studio. It's documented on the Compiling guide on the website: https://lovr.org/docs/Compiling#android

Also please don't double post issues on the chat and this issue tracker.  People will reply if they know the answer and have time to respond.
