### ISSUE TITLE
Issue when trying to use keytool

### ISSUE THREAD

**Issue by geichelb3512** [bjornbytes/lovr#638]
keytool error: java.io.FileNotFoundException: my-release-key.keystore (Access is denied)
java.io.FileNotFoundException: my-release-key.keystore (Access is denied)
this is output from java
how do i fix this?

**Comment by bjornbytes** [comment]
Please don't cross-post between the chat and issue tracker in an effort to get more visibility on your problem.  People will reply if they know the answer and have time to respond.
