### ISSUE TITLE
Variables only available in vertex/fragment shader should not be defined at all in other (fragment/vertex) shaders

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#643]
I check out dev branch, git [886db5f9](https://github.com/bjornbytes/lovr/commit/886db5f91d5349065e4a4f8f204562700744aa83). I do a totally standard build (`cmake.exe .. -A x64`.)

I run the following test program that does nothing but build a shader. I run in desktop driver using a [conf file](https://github.com/mcclure/lovr/blob/andi/game/lua/conf.lua).

```
function lovr.load()
local shader = lovr.graphics.newShader([[

vec4 lovrmain() {
  return Projection * View * Transform * VertexPosition;
}
]], [[
vec4 lovrmain() {
  // return PassColor; // This by itself fails too.
  return vec4(0.5, 0.5, 0.5, 1.) * PassColor;
}
]])
end
```

It fails.

```
Error:
Could not parse fragment shader:
ERROR: 0:3: 'gl_BaseInstance' : undeclared identifier
ERROR: 0:3: '[]' : scalar integer expression required
ERROR: 0:3: '*' :  wrong operand types: no operation '*' exists that takes a left-hand operand of type ' const
 4-component vector of float' and a right operand of type 'layout( column_major std140) temp structure{layout(
 column_major) global highp 4X4 matrix of float transform, layout( column_major) global highp 4X4 matrix of fl
oat normalMatrix,  global highp 4-component vector of float color}' (or there is no acceptable conversion)
ERROR: 0:3: '' : compilation terminated
ERROR: 4 compilation errors.  No code generated.
```
If you swap the comments (don't multiply by the vec4) the third error goes away but the first two stay. The documentation says PassColor is a vec4 tho so I'd expect the multiply should be fine too.

Is it recommended to use master rather than dev currently?

**Comment by mcclure** [comment]
This is on Windows 10, 10.0.19045 Build 19045, CMake 3.23.1, compiler should be sourced from VS2019.

**Comment by mcclure** [comment]
Same results with OpenXR driver and airlink quest attached

**Comment by mcclure** [comment]
Same results on master 4afb0ae2bf50

**Comment by bjornbytes** [comment]
`PassColor` is only available in the vertex shader (Shaders guide groups the builtin variables by shader stage).  Some alternatives that might work:

- The `Color` variable is available in the fragment shader, which includes all the non-per-pixel colors (pass/material/vertex).  It's computed by the vertex shader and sent to the fragment shader.
- The `DefaultColor` macro multiplies `Color` by the diffuse texture sample.

Do either of these work, or do you specifically need to isolate the `:setColor` value in the frag shader?

**Comment by mcclure** [comment]
Color works. I see now I was misreading the documentation.

Is it surprising that PassColor is a recognized symbol in fragment shaders at all?

**Comment by bjornbytes** [comment]
That's a good point.  The `#define`s can be scoped better so you can't use things that won't compile properly.

**Comment by mcclure** [comment]
> That's a good point. The `#define`s can be scoped better so you can't use things that won't compile properly.

I'm gonna just rename this issue if that's ok lol

**Comment by bjornbytes** [comment]
This is fixed, error message now  looks like:

> ERROR: 0:2: 'PassColor' : undeclared identifier

Which is much better!
