### ISSUE TITLE
FPS goes to "silly" values when Oculus headset is sleeping

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#646]
In my tests, I am running an app that draws a scene and also a FPS tester that runs on the mirror window. I am using a Quest 2 in "Oculus Link" mode which should be equivalent to an Oculus Rift.

What I find is that when I have the headset on, the mirror window draws the scene and also draws my mirror FPS tester on top of it. When I take the headset off, or after I have opened the app but before I have put the headset on for the first time, the scene goes black in the mirror window and the mirror FPS tester is drawn alone. That is expected. What is **not expected** is that when the headset is deactivated and the scene is black, the FPS goes to absurd FPS values, like typically around 2000 FPS. My screen maxes out at 60 fps or something. This is surely wasting CPU.

**Expected behavior** is that if FPS in the openxr driver uncaps while the headset is sleeping, lovr should detect this and either reduce the framerate to match the mirror window vsync rate like the desktop driver does; or, if this is too difficult, manually cap at some "reasonable" ceiling like 120 FPS or something.

Repro case: Built https://github.com/mcclure/lovr/tree/andi-dev  
and ran `./build/Debug/lovr.exe game/lua app/test/testUi3.lua app/debug/fps.lua`
This is dev branch [4afb0ae](https://github.com/bjornbytes/lovr/commit/4afb0ae2bf5096b59c33c6dcd512d2d85cf626cd) with trivial patches, so the Lovr project in game/lua in that commit should be perfectly fine to execute in stock lovr with the same results

**Comment by bjornbytes** [comment]
If I put a pedantic hat on, I would say it's the job of the Oculus runtime to be throttling the VR app here.

But practically, since the idea of reporting this to Oculus is presumably futile, lovr can probably add a throttle when OpenXR tells us the session is not visible.

**Comment by bjornbytes** [comment]
Actually I take that back (sorry Oculus <3), I think they are fully moving the session to the IDLE state, in which case lovr should be throttling.  I put a commit on `dev` that does a 1ms throttle when idle.  It's a little less strict than 60 or 120hz, but should still prevent burning the CPU.  Let me know if it works okay (I may have guessed wrong and they aren't going to idle, or something).

**Comment by mcclure** [comment]
Seems to hover around 250 fps now when idle, which could maybe be improved on later but isn't particularly bad at all!
