### ISSUE TITLE
pass:setBlendMode(nil) is not documented

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#647]
https://lovr.org/docs/Pass:setBlendMode

Does not document what happens if you pass "nil" for the arguments. It says "The default blend mode is alpha with the alphamultiply alpha mode." implying nil goes to alpha mode.

However, nil does <i>something</i>. In both master and dev <a href="https://github.com/bjornbytes/lovr/blob/master/src/api/l_graphics_pass.c#L262">pass:setBlendMode()</a>, on null arguments, defaults argument # 2 to "alphamultiply", but a null argument #1 is a special "BLEND_NONE" value. https://lovr.org/docs/BlendMode does not list  either "none" or `nil` as a valid possibility. But lovrPassSetBlendMode <a href="https://github.com/bjornbytes/lovr/blob/master/src/modules/graphics/graphics.c#L3618">has unique handling for this NONE value</a>. (In my testing, it doesn't seem to do anything different from "alpha".)

"EXPECTED BEHAVIOR" whatever this does should be documented.

**Comment by bjornbytes** [comment]
`nil` disables blending (can think of it like "replace" where the color from the shader is written directly to framebuffer.

Updated the docs to add this variant.  Future documentation issues should be filed in the [lovr-docs repo](https://github.com/bjornbytes/lovr-docs).  There's also a handy edit button on each page if you want to make small changes (I get that this issue required some extra clarification tho).
