### ISSUE TITLE
Last version Crashes on Windows

### ISSUE THREAD

**Issue by milen-prg** [bjornbytes/lovr#660]
Windows 10 Pro 64 bit,
Last lovr version crashes, the nightly version only try to open window and closes immediately. (at try to start lovr.exe)

**Comment by bjornbytes** [comment]
There isn't enough information here to know what's going on.  Recently one other person experienced a crash on Intel GPU due to the shader cache.  You can disable that by setting `t.graphics.shadercache = false` in conf.lua to see if it helps.  What GPU are you using?

**Comment by milen-prg** [comment]
But there is no conf.lua. In archive are only 7 files:
glfw3.dll, lovr.exe, lovrc.bat, luajit.dll, msdfgen.dll, ode.dll and openxr_loader.dll.
I try to start the lovr.exe, and Windows opens message that the Lovr stopped work and I close it (in the nightly  version, only blinks on screen and nothing).

In the old version, the VR window was opened (but I can't remember the old version number, because I directly replace it with the new release archive).

**Comment by bjornbytes** [comment]
To change some of the config settings to see if it helps, you can make a project by putting these 2 files in a folder:

```lua
-- main.lua
function lovr.load()
  print(lovr.graphics.getDevice().name) -- print the GPU you have
end

function lovr.draw(pass)
  pass:text('Hi!!!', 0, 1.7, -3)
end
```

```lua
-- conf.lua
function lovr.conf(t)
  t.graphics.shadercache = false -- maybe this will fix something?
end
```

You can run it from `cmd.exe` like this: `lovr --console C:\path\to\folder`.

Are you using a VR headset?  The WMR runtime doesn't support Vulkan yet

**Comment by milen-prg** [comment]
I not use VR, just see that lovr was copied on my system and before start to learn it, decided to update... I want to play with making desktop "games" in lua.

I try, add this project with this 2 lua files in lovr folder and the result is the same with or without conf.lua:

C:\lovr-v0.16.0-win64>lovr --console .

C:\lovr-v0.16.0-win64>Error:
GPU error: Failed to load vulkan library

Stack:
boot.lua:90: in function <boot.lua:4>
[C]: in function 'xpcall'

My video card is not for game, but I like to play with some small physics 3d demonstrations, just look for most simple way to make them (before use vpython). My card is:

Intel HD Graphics 4400

It have last drivers, but may be Vulkan can't work with it?

**Comment by bjornbytes** [comment]
Ok, unfortunately your GPU doesn't support Vulkan, so v0.16.0 won't work.  Sorry about that, there might be ways LÖVR can improve this in the future.  Thanks for the issue.
