### ISSUE TITLE
Does lovr support pico4?

### ISSUE THREAD

**Issue by DuinoDu** [bjornbytes/lovr#666]
Hi, does lovr support pico4? Or how can I add support for pico4?

**Comment by bjornbytes** [comment]
Hi, the nightly builds on GitHub actions (on either `master` or `dev` branch) have APKs that should work on Pico Neo 3 and Pico 4.  If you're able to test and confirm that the nightly APKs are working (or not working!) on Pico 4, that would be very much appreciated.  Currently they have only been tested on Pico Neo 3.

However, controller bindings are only set up for Neo 3 right now.  If you're comfortable with C and want to add Pico 4 controller bindings, that would be great.  The main relevant parts are here:

- A new interaction profile for Pico 4 would need to be added [here](https://github.com/bjornbytes/lovr/blob/98e648871ee91e7e2e8e40cee4f95be36da6bac7/src/modules/headset/headset_openxr.c#L631) and [here](https://github.com/bjornbytes/lovr/blob/98e648871ee91e7e2e8e40cee4f95be36da6bac7/src/modules/headset/headset_openxr.c#L644)
- [Here](https://github.com/bjornbytes/lovr/blob/dev/src/modules/headset/headset_openxr.c#L827-L863) are the Pico Neo 3 controller bindings.  Similar bindings would need to be added for Pico 4, using the [OpenXR spec](https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#XR_BD_controller_interaction) as a reference.  The bindings are really similar to Pico Neo 3, with a few differences on the menu button.

There's a controller test project here that I use to test bindings: https://lovr.org/docs/Debugging/Raw_Input
