### ISSUE TITLE
`pass:skybox()` crashes without error if you don't provide arguments

### ISSUE THREAD

**Issue by KelseyHigham** [bjornbytes/lovr#667]
the entire main.lua:
```lua
function lovr.draw(pass)
  pass:skybox()
end
```

setup:
latest nightly master
macOS 12 Monterey, [Intel Mac](https://everymac.com/systems/apple/macbook_pro/specs/macbook-pro-core-i7-2.8-15-dual-graphics-mid-2015-retina-display-specs.html)

**Comment by bjornbytes** [comment]
Fixed this to error when the texture is missing
