### ISSUE TITLE
on macOS, shader constants are only sent to the first object drawn

### ISSUE THREAD

**Issue by KelseyHigham** [bjornbytes/lovr#668]
after that, data sent is consistent between runs, but completely wrong.

setup:
latest nightly master
macOS 12 Monterey, [Intel Mac](https://everymac.com/systems/apple/macbook_pro/specs/macbook-pro-core-i7-2.8-15-dual-graphics-mid-2015-retina-display-specs.html)

the entire main.lua:
```lua
-- this should display 3 red cubes.

-- on my machine, it shows two red cubes on the left.
-- the rightmost cube starts out light yellow and fades to white.

red_shader = lovr.graphics.newShader('unlit', [[
Constants {
  vec3 red_constant;
};

vec4 lovrmain() {
  return vec4(red_constant, 1);
}
]])

function lovr.draw(pass)
  pass:setColor(1, 0, 0)
  pass:cube(-1.5, 1.7, -3)
  pass:setShader(red_shader)
  pass:send('red_constant', {1, 0, 0}) -- change this to a vec4 to make the third box disappear entirely
  pass:cube( 0, 1.7, -3)
  pass:cube( 1.5, 1.7, -3)
end
```

**Comment by bjornbytes** [comment]
This MoltenVK issue is from 2019 and was already fixed but is somewhat similar to what is happening:

https://github.com/KhronosGroup/MoltenVK/issues/657

**Comment by bjornbytes** [comment]
I just tested this on macOS!  I got the following validation error with `t.graphics.debug = true`:

```
Validation Error: [ VUID-VkVertexInputBindingDescription-stride-04456 ] Object 0: handle = 0x7f87a9875818, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x1606ae17 | Invalid Pipeline CreateInfo[0] (portability error): Vertex input stride must be at least as large as and a multiple of VkPhysicalDevicePortabilitySubsetPropertiesKHR::minVertexInputBindingStrideAlignment. The Vulkan spec states: If the VK_KHR_portability_subset extension is enabled, stride must be a multiple of, and at least as large as, VkPhysicalDevicePortabilitySubsetPropertiesKHR::minVertexInputBindingStrideAlignment (https://vulkan.lunarg.com/doc/view/1.3.224.1/mac/1.3-extensions/vkspec.html#VUID-VkVertexInputBindingDescription-stride-04456)
```

`minVertexInputBindingStrideAlignment` is 4 on MoltenVK.  LÖVR currently uses vertex strides of zero for missing attributes, which causes undefined behavior on MoltenVK.  Even though the shader is just using a push constant, I believe the undefined behavior here is causing the issue.

**Comment by bjornbytes** [comment]
After the recent shader changes, I can confirm that this is fixed!
