### ISSUE TITLE
Temporary vector space exhausted

### ISSUE THREAD

**Issue by xiejiangzhi** [bjornbytes/lovr#673]
```
function lovr.load()
  local pos = vec3(1)
  local dir = vec3(1, 0, 0)
  local r = vec3(0)
  for i = 1, 4000 do
    r = pos + vec3(i) * 2 - dir * 0.5
  end
  print(r)
end
```
Doing a simple calculation with only 4000 loops gives the error "Temporary vector space exhausted".

I think this problem needs to be solved, because lovr's vector is global by default, unless I don't use the built-in vector at all (including modifying the imported third-party library), otherwise as long as a small amount of vector calculation is performed in the loop, it will appear this problem.

I just want to generate a few particles, the global vector pool is completely useless. And I can't use lovr.math.drain yet, because it will also empty the caller's vector.

**Comment by bjornbytes** [comment]
The next version increases the pool from 16K vectors to 4M vectors (256x bigger), which should help a lot with this.

Another idea that hasn't been implemented yet is to add `lovr.math.push` and `lovr.math.pop`, so library code could drain its own vector pool without disturbing the vectors of the caller.

**Comment by bjornbytes** [comment]
Closing for now because there's since been an improvement, but feel free to comment/reopen if you still have issues with the pool capacity.
