### ISSUE TITLE
VK_ERROR_OUT_OF_DEVICE_MEMORY when loading a 55MB model

### ISSUE THREAD

**Issue by Ensber** [bjornbytes/lovr#675]
i am loading a .glb model an i get the VK_ERROR_OUT_OF_DEVICE_MEMORY error. here is an example for the version: LOVR 0.16.0 (Toad Rage)

[examlpe.zip](https://github.com/bjornbytes/lovr/files/11798169/examlpe.zip)

My GPU is a NVIDIA GeForce RTX 2070 Super
Dedicated RAM: 8GB
Shared RAM: 12GB

**Comment by immortalx74** [comment]
With a lesser GPU (GTX 970) using either the latest build from main or the dev branch, I'm not getting this error.
So I guess it's something that was fixed since the latest release.

**Comment by Ensber** [comment]
yes, i can confirm that it works on the nightly build, but i cant use it sice the lovr.graphics.newBuffer(data, format) seems to have changed and thus broke my code. Is there a newer documentation available that the lövr master docs?

**Comment by immortalx74** [comment]
If you browse the official documentation, on the top-left there's a dropdown which by default reads "v0.16.0". Click on it and select "master". AFAIK docs get updates as soon as new features/fixes are made.

**Comment by bjornbytes** [comment]
You can also use a nightly build from the `master` branch instead of `dev`.  `master` branch has the bugfix, but doesn't have any API changes.
