### ISSUE TITLE
Sphere Test and Box Test for lovr.physics

### ISSUE THREAD

**Issue by bjornbytes** [bjornbytes/lovr#680]
There isn't currently an easy way to query all the colliders/shapes in an area with lovr.physics.

It's possible to create a sensor collider, but this requires recomputing and iterating over all of the overlapping shapes.

There could be functions similar to `World:raycast` like `World:queryBox` and `World:querySphere`, which call a callback with all of the shapes in the specified area.

**Comment by xiejiangzhi** [comment]
A little thought:
```
local my_shape = lovr.physics.newCapsule(0,5, 0.5)
local pos = vec3()
local rot = quat()
world:queryShape(my_shape, pos, rot)
```

It may be slow, but complex shapes can be queried.
I see that in the Lovr code, the ODE can be queried using dGeomID, so all Lovr shapes are available.

**Comment by KelseyHigham** [comment]
i would love a world:queryShape function – i would just keep one sphere and one capsule around and reuse them for everything, specifying radius and length every time.

if they were tagged, and set to ignore specific tags, i could use them for locomotion and combat as desired.

**Comment by KelseyHigham** [comment]
come to think of it, this query wouldn't work properly with meshes, if the query shape's center is inside the mesh, due to #672...

**Comment by bjornbytes** [comment]
Regarding `queryShape` -- shapes can only be positioned if they are attached to a collider (at least in lovr right now).  So queryShape has to behave in 2 ways:

- If the Shape *is* attached to a collider, queryShape would probably ignore any pose-related arguments and instead use the shape's world-space position from its collider.  It could also move the shape if a pose was given, do the query, and move it back, but this is kinda weird.
- If the Shape *is not* attached to the collider, then it doesn't have a pose at all, so for queryShape to be useful, it would need to take pose arguments (like in the example posted above).

This is...kind of messy.  Ideally you'd be able to create an empty shape (not attached to a collider), position it somewhere, and do a query.  Maybe lovr can try to change Shape to allow this, I don't remember the rationale for the current limitations.

So while this simmers I think I'll at least implement `:queryBox` and `:querySphere`, because those are easy to add and useful, even if `:queryShape` gets sorted out later.

**Comment by bjornbytes** [comment]
queryBox and querySphere are implemented on `dev` now!  I think I'll close this issue, but the more general/tricky queryShape method is still up for discussion.
