### ISSUE TITLE
Wrong coordinate origin

### ISSUE THREAD

**Issue by xiejiangzhi** [bjornbytes/lovr#682]
Device: Vive Pro with SteamVR

The coordinate origin and orientation isn't center and orientation of play area, them may be outside the play area.(SteamVR "Recenter" will change the position & orientation)

It is not possible to get the center of the play area.

position device floor also outside the play area.
I try getBoundsGeometry, it return nil.

dev branch, this feature was fine not too long ago. We need to fix it, or give an interface to get the center and set the origin

**Comment by bjornbytes** [comment]
The recentering behavior in LÖVR did recently change: the origin is no longer in the center of the play area, but is instead located on the floor at the "local" origin, which changes based on recentering.

The way to get the center of the floor is supposed to be `lovr.headset.getPose('floor')`, e.g.

```lua
function lovr.draw(pass)
  pass:push()
  pass:transform(mat4(lovr.headset.getPose('floor')))
  -- draw any floor-relative content here
  pass:pop()
end
```

However, the coordinate space is definitely not working properly with SteamVR right now.  I think this is a bug with SteamVR 1.26, see [here](https://steamcommunity.com/app/250820/discussions/3/3808406007543348602/).  I'm going to monitor this discussion thread on SteamVR to see if there's a fix, and if not then potentially disable recentering on SteamVR.

It currently works fine on Quest.

**Comment by xiejiangzhi** [comment]
Thanks,  I just tested it again, restarting SteamVR, the floor will get the center position and direction of the play area.
If StreamVR “Recenter” is executed, the floor will change its position and direction, and will no longer be in the center of the play area. Until the next SteamVR restart, the floor will revert to the center position.

I've tried using pass:transform and the render position is correct, but the device position data won't match. I don't know how to do the correct conversion.

**Comment by xiejiangzhi** [comment]
My testing code

```
local lh = lovr.headset

local function draw_hand(pass, path)
  local x, y, z, angle, ax, ay, az = lh.getPose(path)
  local pos = vec3(x, y, z)
  pass:sphere(pos, 0.05)
  pass:line(pos, pos + quat(angle, ax, ay, az):direction())
end

function lovr.draw(pass)
  local fx, fy, fz, fangle, fax, fay, faz = lh.getPose('floor')
  local w, d = lh.getBoundsDimensions()

  pass:setColor(1, 0, 0)
  pass:sphere(fx, fy, fz, 0.2)
  pass:box(0, 0, 0, w, 0.05, d, 0, 0, 1, 0, 'line')

  local tf = mat4(fx, fy, fz, fangle, fax, fay, faz)
  pass:transform(tf)

  pass:setColor(0, 0, 1)
  pass:box(0, 0, 0, w, 0.05, d, 0, 0, 1, 0, 'line')

  pass:setColor(0, 1, 0)
  draw_hand(pass, 'hand/left')
  draw_hand(pass, 'hand/right')
end
```

**Comment by xiejiangzhi** [comment]
I got it, device position & orientation should invert this transformation.

The new code

```
local lh = lovr.headset

local DeviceCoordMat

local function draw_hand(pass, path)
  local x, y, z, angle, ax, ay, az = lh.getPose(path)
  local pos = DeviceCoordMat * vec3(x, y, z)
  local rot = quat(DeviceCoordMat) * quat(angle, ax, ay, az)

  pass:sphere(pos, 0.05)
  pass:line(pos, pos + rot:direction())
end

function lovr.draw(pass)
  local fx, fy, fz, fangle, fax, fay, faz = lh.getPose('floor')
  local w, d = lh.getBoundsDimensions()
  local render_transform = mat4(fx, fy, fz, fangle, fax, fay, faz)
  DeviceCoordMat = mat4(render_transform):invert()

  pass:setColor(1, 0, 0)
  pass:sphere(fx, fy, fz, 0.2)
  pass:box(0, 0, 0, w, 0.05, d, 0, 0, 1, 0, 'line')

  pass:transform(render_transform)

  pass:setColor(0, 0, 1)
  pass:box(0, 0, 0, w, 0.05, d, 0, 0, 1, 0, 'line')

  pass:setColor(0, 1, 0)
  draw_hand(pass, 'hand/left')
  draw_hand(pass, 'hand/right')
end
```

**Comment by bjornbytes** [comment]
Tested with new SteamVR beta 1.26.6 and the issue persists.

Pushed a commit to `dev` that just uses the center of the play area as the origin for now.  

Something that might be useful is to change from t.headset.seated to t.headset.origin and make the origin `'seated'`, `'standing'`, or `'floor'`.  Standing would use the recentering position, whereas floor would always be in the center of the play area.  That way people can pick which floor-level origin they want.

Still, this particular bug seems to be something wrong with SteamVR.
