### ISSUE TITLE
Torus is invisible when its thickness is zero

### ISSUE THREAD

**Issue by bjornbytes** [bjornbytes/lovr#698]
It should draw a ring-like thing.  Also maybe there should just be a :ring method that draws a ring-like thing, especially if it isn't easy for :torus to do so gracefully.  Also maybe :cylinder and :cone should draw circles when their lengths are zero, they might be drawing a bunch of unnecessary geometry right now.

**Comment by KelseyHigham** [comment]
also capsule of length zero (or at least capsule defined by two of the same point)

**Comment by bjornbytes** [comment]
Capsule was already fixed in 78308acfa4117d070f84edb36d984f75d8325eac!  Forgot to mention that

**Comment by jmiskovic** [comment]
I would expect all of 3D shapes to fallback to 2D shapes as you suggest, but to their double-sided variants.

For example, `:circle` should stay one-sided, and `:cylinder` and `:cone` with length 0 should be double-sided.

**Comment by bjornbytes** [comment]
Uhh, wait, torus is *supposed* to disappear when its thickness is zero!  For some reason when I wrote this I was thinking thickness was only on the z axis (like a cylinder), but it's a thickness "around" the central ring.

Cylinder and cone are indeed already double-sided when their lengths are zero.

(`:ring` would still be cool!)
