### ISSUE TITLE
On macOS, mouse position is affected by DPI

### ISSUE THREAD

**Issue by KelseyHigham** [bjornbytes/lovr#699]
This bug is new in 0.16; it didn't occur in 0.15.

Demonstrating this by drawing 4 lines, dragging my mouse cursor along the 4 edges of the screen, then leaving it in the middle of the screen.

0.16.x, prior to the hand position update. @1X first, Retina @2X second:
![Screen Shot 2023-08-23 at 10 04 52 AM](https://github.com/bjornbytes/lovr/assets/286211/689bd35f-3837-4602-8a09-6925898e0e0f)
<img width="832" src="https://github.com/bjornbytes/lovr/assets/286211/adc5566f-3174-4ee6-8562-376977b709c2">

0.16 current dev, with the hand position update. @1X first, Retina @2X second:
![Screen Shot 2023-08-23 at 9 59 16 AM](https://github.com/bjornbytes/lovr/assets/286211/3e2b1342-85c3-4429-856e-8a89015e26bb)
<img width="832" alt="Screen Shot 2023-08-23 at 10 00 06 AM" src="https://github.com/bjornbytes/lovr/assets/286211/c1479509-661a-4e59-985b-b4a31ccb402d">

0.16 current dev, with the hand position update, and the mouse in the middle of the window. @1X first, Retina @2X second:
![Screen Shot 2023-08-23 at 10 01 48 AM](https://github.com/bjornbytes/lovr/assets/286211/e271e05f-3472-4fcf-b45b-8f9eb791b079)
<img width="832" alt="Screen Shot 2023-08-23 at 10 01 23 AM" src="https://github.com/bjornbytes/lovr/assets/286211/f20d2253-7cf3-4697-9bf5-c9ea8addaab3">

**Comment by bjornbytes** [comment]
Hm it might have been a bad idea to change window size to use pixels for its units instead of screen coordinates.  GLFW uses screen coordinates for literally everything else.

**Comment by bjornbytes** [comment]
Should be fixed now, along with #700 .  Window size and mouse coordinates (and everything else) now use GLFW's window coordinates, and graphics-y measurements like pass texture dimensions and simulator's display dimensions use pixels (i.e. multiplied by window pixel density).  It's easier to follow GLFW's convention.
