### ISSUE TITLE
[SteamVR] Overlay closes main app (t.headset.overlay)

### ISSUE THREAD

**Issue by Python1320** [bjornbytes/lovr#709]
Opening any VR app in SteamVR and launching the following seems to close the original app no matter what:
`conf.lua`
```lua
function lovr.conf(t)
    t.headset.overlay = true
end
```
`main.lua`
```lua
function lovr.draw(pass)
    pass:cube(0, 1.7, -1, .5, lovr.headset.getTime(), 0, 1, 0, 'line')
end
```

Development [appears](https://www.reddit.com/r/OpenXR/comments/rk0eg2/comment/hp76ug8/?utm_source=reddit&utm_medium=web2x&context=3) to have [stalled](https://community.khronos.org/t/better-support-for-mutliple-simultaneous-applications/108932) on OpenXR overlays in favour of API layers it seems.

It also seems there is no LÖVR pre-built with both `overlay` and SteamVR, which is a shame, since there it probably works.

OpenXR has API layers seems to be the current supported option: ["OpenKneeboard currently supports overlays with: OpenXR Direct3D 11 games, via a custom API layer"](https://fredemmott.com/blog/2022/05/31/in-game-overlays.html) (unfortunately licenses are not compatible with LÖVR).

Related:
 - https://github.com/mbucchia/OpenXR-Layer-Template/wiki/Tutorial-1:-Your-first-OpenXR-API-layer
 - https://github.com/mbucchia/OpenXR-Layer-Template
 - https://github.com/ValveSoftware/steamvr_unity_plugin/pull/336
 - https://github.com/ValveSoftware/steamvr_unity_plugin/issues/108#issuecomment-830678776 
 - https://github.com/LunarG/OpenXR-OverlayLayer#implementation-specifics
 - https://github.com/LunarG/OpenXR-OverlayLayer/issues/31#issuecomment-1632648626

**Comment by bjornbytes** [comment]
This is currently the intended behavior.  `t.headset.overlay` turns your app into an OpenXR overlay, and SteamVR does not support OpenXR overlays.

API layers automatically work with any OpenXR runtime/application, including LÖVR.  I currently use API layers to add Ultraleap hand tracking to LÖVR, for example.

To get overlay functionality on SteamVR, we're basically either waiting on SteamVR to add support for `XR_EXTX_overlay` (unlikely), or for the OpenXR working group to release better overlay extensions and SteamVR to add support for *those*.  Until then, `XR_EXTX_overlay` is the best way to do it.  To my knowledge it only works on monado and other monado-based runtimes.
