### ISSUE TITLE
Expose Build Info

### ISSUE THREAD

**Issue by bjornbytes** [bjornbytes/lovr#712]
Request from chat

> it would be cool if lovr.getVersion() returned the branch
> and build time
> those might be useful on the error screen/error printout too

Branch?  Commit hash?  Date/time?  Commit message?!

`lovr.getVersion`?  `lovr.getBuildInfo`?

**Comment by wasokeli** [comment]
i like that hashes are short and easy to recognize, but there's a couple downsides
- you gotta copy and paste them, because they're hard to remember and write
- they're not sequential, so you gotta look at git/hub to see how old your version is

**Comment by wasokeli** [comment]
i think my ideal would be like "0.16.dev.2023-09-25"
or shorten it by rolling over months, "0.16.dev.2125"

**Comment by bjornbytes** [comment]
Running `git describe` in lovr's repo prints `v0.16.0-541-gc0fb`: the last tagged version, the number of changes since then, plus the hash.  (Jotting this down here).  Also, if you're on exactly the tagged version, it will just print `v0.16.0` which is kinda cool.

**Comment by bjornbytes** [comment]
`lovr.getVersion` and `lovr --version` now include the git hash as a 5th return, when built by GH actions.
