### ISSUE TITLE
Support for Quest 3 Passthrough/Mixed Reality (MR) ?

### ISSUE THREAD

**Issue by bradparks** [bjornbytes/lovr#715]
Hey! I'm wondering if there's any plans/ways to make passthrough mode work anytime soon?

I saw [the docs here](https://lovr.org/docs/FAQ) mentioned passthrough, but they seemed a bit old, and was wondering with Quest 3 and VisionPro, if mixed reality/augmented reality was on the roadmap?

Thanks!

**Comment by bjornbytes** [comment]
Hi, passthrough was just released a couple weeks ago with v0.17.0!  You can do `lovr.headset.setPassthrough(true)` to enable it.  It works on all Quest devices, and other OpenXR-compatible AR devices.
