### ISSUE TITLE
Open white window

### ISSUE THREAD

**Issue by milen-prg** [bjornbytes/lovr#723]
I try v.0.17 on Windows 11 Pro and LOVR opens only white window. I try also the hello world project and the result is the same. In console have no messages.

**Comment by bjornbytes** [comment]
What GPU do you have?  It could be a problem with Vulkan initialization.  Running with `--graphics-debug` argument could produce more information.

**Comment by immortalx74** [comment]
There's also a Vulkan test you can try to see if your GPU is capable:
https://github.com/skeeto/vulkan-test

**Comment by milen-prg** [comment]
I have last updated nVidia GeForce RTX 3060 12GB GDDR6

![image](https://github.com/bjornbytes/lovr/assets/59639866/763e29db-8420-450e-8da1-78d471809f82)

**Comment by milen-prg** [comment]
C:\lovr>lovrc.bat --graphics-debug

lovr --console --graphics-debug
Warning: GPU debugging is enabled, but validation layer is not installed

**Comment by immortalx74** [comment]
I'm on Windows 11 Pro too (23H2) and also have an RTX 3060 12GB. Try this:
On the project folder (where main.lua is located) create a new file and name it conf.lua
Paste this inside and try running your project:
`function lovr.conf( t )
    t.headset.drivers = {'desktop'}
end`

**Comment by milen-prg** [comment]
@immortalx74 I have the same system configuration, but this not help. The lovr.exe opens full white window (There is responsive system menu). And I see that when it is open, the GPU is at 100% load.

**Comment by immortalx74** [comment]
If the system menu is responsive then it means that at least the app doesn't hang. BTW were you able to print something in the console?
One other thing you can try is to play a sound (there's an example in the docs under Audio). This way you will be able to know that the lovr callbacks are running, and that your issue might be only a graphical one.

**Comment by bjornbytes** [comment]
It could maybe be a problem with window resizing?  This is really bizarre...  I agree with immortalx that it would be good to check if lovr.update is getting called or if audio can play properly.

**Comment by bjornbytes** [comment]
Closing since this isn't actionable without more information.
