### ISSUE TITLE
quest2 filesystem cant refresh

### ISSUE THREAD

**Issue by blenderman94** [bjornbytes/lovr#739]
hez i have somethin strange on the quest2 if i load a file like a txt it work fine until i trz to reload it with more content. it only refreshes when i re launch the app it ingores growrth but works when the file is shortening :D (i dont have anz sql libs on android so i kind of have to make one since nobodz known how to compile it with meaningful tutorial)

**Comment by bjornbytes** [comment]
Lua files generally won't be refreshed until the app is reloaded, but if you're using something like `lovr.filesystem.read` then it will return the latest contents of the file.  How are you reading/writing the text file?

**Comment by blenderman94** [comment]
no only on app restart

**Comment by bjornbytes** [comment]
I think to help I'm going to need a more concrete description of how you're updating the file, what the result is, and how it doesn't match what you expect.

There are ways to get updates to a file while a LÖVR app is running but I don't really understand what you're doing or trying to do yet.

**Comment by blenderman94** [comment]
im reading a text file edited by an external text editor if the file is shortening it gets picked up when i re load it wit lovr but if the file grows the reloading does not work just on restarting.  (its probaly a behaviour of android filesystem) i tryed to make a sql like databse since we greatly lack of that thing is essential for any profesional application. so i made  a hack is sql database i tried to edit a table in real time and just re load it but its just does not work. so i had to make first a text editor and a keyboard interface embeded into vr   to be able to keep everything in memory :D im basicaly using your framework for science research so i just cant live without sql databases in short i problam standalone on my vr headset without a pc an sql database in lovr can be great charm for devolopers to use your framework since the idea is kinda good for it.
