### ISSUE TITLE
open-xr dependency needs to be updated to avoid building error: 'wayland-client.h' not found

### ISSUE THREAD

**Issue by RiQuY** [bjornbytes/lovr#740]
open-xr build fails when building in openSUSE Tumbleweed because cmake is not able to find 'wayland-client.h' on `/usr/include` because it is on  `/usr/include/wayland`.

The issue is fixed upstream on this PR: 
- https://github.com/KhronosGroup/OpenXR-SDK-Source/pull/346 

That fix does not have a release version yet, it is on main. So I suggest updating `lovr/deps/open-xr` to the latest commit to get the fix.

This is the cmake build log with the error if you want to check it:
- https://gist.github.com/RiQuY/d744905540c31f57efeab2e9b142299a

**Comment by bjornbytes** [comment]
This fix was released in version 1.0.27 of the OpenXR SDK.  LÖVR's OpenXR submodule is currently at 1.0.30 (`55224479ab13db8ebc8ab1e3d49197bce6201b0b`).  It looks like the fix is already included, right?  Or am I missing something?

**Comment by RiQuY** [comment]
> This fix was released in version 1.0.27 of the OpenXR SDK. LÖVR's OpenXR submodule is currently at 1.0.30 (`55224479ab13db8ebc8ab1e3d49197bce6201b0b`). It looks like the fix is already included, right? Or am I missing something?

You are right, I had read Jan 20, 2023 like 2024. Sorry about that. If this is the case, I don't know why it is still happening.

**Comment by bjornbytes** [comment]
I read 2023 as 2024 too at first haha.

I uninstalled `libwayland-dev` and I got the same error you did, but if did `cmake .. -DBUILD_WITH_WAYLAND_HEADERS=OFF` then everything works.  Since LÖVR doesn't use wayland and OpenXR's wayland stuff is weird anyway, I think BUILD_WITH_WAYLAND_HEADERS could be set to OFF in LÖVR's CMakeLists.txt.

**Comment by RiQuY** [comment]
> I read 2023 as 2024 too at first haha.
> 
> I uninstalled `libwayland-dev` and I got the same error you did, but if did `cmake .. -DBUILD_WITH_WAYLAND_HEADERS=OFF` then everything works. Since LÖVR doesn't use wayland and OpenXR's wayland stuff is weird anyway, I think BUILD_WITH_WAYLAND_HEADERS could be set to OFF in LÖVR's CMakeLists.txt.

Are you suggesting me to do that as a workaround or do you mean that you are gonna include the fix?

**Comment by bjornbytes** [comment]
I bumped OpenXR to 1.0.33 on `dev` and set BUILD_WITH_WAYLAND_HEADERS to OFF as well.  Let me know if you're still having problems.  Thanks for the issue!

**Comment by RiQuY** [comment]
@bjornbytes Sorry for answering so late. I tried building it again using the latest commit on dev branch but I've got a new error.

These are the commands I ran:
```
❯ git clone https://github.com/bjornbytes/lovr.git
❯ cd lovr
❯ git submodule update --init --recursive
❯ mkdir build
❯ cd build
❯ cmake ..
❯ cmake --build .
```

Related error:
```
[100%] Building C object plugins/lovr-http/CMakeFiles/http.dir/http.c.o
/media/Almacen/Programas/lovr/plugins/lovr-http/http.c:468:10: error fatal: curl/curl.h: No existe el fichero o el directorio
  468 | #include <curl/curl.h>
      |          ^~~~~~~~~~~~~
compilación terminada.
gmake[2]: *** [plugins/lovr-http/CMakeFiles/http.dir/build.make:76: plugins/lovr-http/CMakeFiles/http.dir/http.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1974: plugins/lovr-http/CMakeFiles/http.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

Full cmake build log:
- https://gist.github.com/RiQuY/5563321d0a9fc5d36ad9c52ac99a205c

EDIT: I installed `libcurl-devel` and I think the error stop happening but I got this warning at the end of the build:
```
[100%] Building C object plugins/lovr-http/CMakeFiles/http.dir/http.c.o
/media/Almacen/Programas/lovr/plugins/lovr-http/http.c: En la función ‘http_request’:
/media/Almacen/Programas/lovr/plugins/lovr-http/http.c:556:3: aviso: ‘CURLOPT_PROTOCOLS’ es obsoleto: since 7.85.0. Use CURLOPT_PROTOCOLS_STR [-Wdeprecated-declarations]
  556 |   curl.easy_setopt(handle, CURLOPT_PROTOCOLS, CURLPROTO_HTTP | CURLPROTO_HTTPS);
      |   ^~~~
En el fichero incluido desde /media/Almacen/Programas/lovr/plugins/lovr-http/http.c:468:
/usr/include/curl/curl.h:1745:3: nota: se declara aquí
 1745 |   CURLOPTDEPRECATED(CURLOPT_PROTOCOLS, CURLOPTTYPE_LONG, 181,
      |   ^~~~~~~~~~~~~~~~~
[100%] Linking C shared module http.so
[100%] Built target http
[100%] Built target move_files
[100%] Built target lj_gen_vm_s
[100%] Built target libopenxr_loader.so.1.0
```

**Comment by bjornbytes** [comment]
That's coming from `lovr-http`, which is an optional component (plugin).  If you don't need HTTP you can remove the `lovr-http` folder from the plugins folder and it won't build.  That warning is safe to ignore though, lovr-http is designed to work with older versions of curl for the time being, since some Debian distributions don't have 7.85 yet.
