### ISSUE TITLE
Shaders Variables are partially broken

### ISSUE THREAD

**Issue by brainrom** [bjornbytes/lovr#752]
Currently, on `dev` branch, using `Pass:send(name, buffer, offset, extent)` or `Pass:send(name, texture)`  (maybe other combinations are affected too) leads to `Shader has no variable named ...` error. Checked on `PBR Materials` and `Shadows` examples.

**Comment by bjornbytes** [comment]
Strange, these 2 examples are working for me...  I tested 79e28eb7e35ee221db139adc0cce06312cc95861 of lovr and `67288ff8f8cb05e9bee84ab355a3c463de294ee3` of lovr-docs.  Do you have any more info?

**Comment by brainrom** [comment]
I checked the lovr's commit, but not the submodules. Git messed it somehow, after `git submodule update --init` shaders works again.
