### ISSUE TITLE
LOVR will not launch on Quest 2

### ISSUE THREAD

**Issue by armoar334** [bjornbytes/lovr#758]
When trying to use LOVR on my Quest 2, it refuses to open. It stays on the three dot loading screen forever, and if I press the oculus home button, it returns me to quest home without even showing the return/exit menu. I have tried
 - Installing over ADB
 - Installing from within the headset with a sideloaded file manager
 - Running without any files in /sdcard/Android/data/org.lovr.app/files (No "No game" screen is ever displayed)
 - Running with the [demo](https://lovr.org/docs/Getting_Started_(Quest)) example file
 - Running with my own basic files  
  
I have developer mode active, and all my other sideloaded apps and games are perfectly functional

**Comment by armoar334** [comment]
Just found out that if I use the oculus button with hand tracking, the return / exit menu does show. The program still does not load however

**Comment by jmiskovic** [comment]
Can you please try an APK from nightly build, for example [this one](https://github.com/bjornbytes/lovr/actions/runs/8240215495/artifacts/1316622576)?

About 3 weeks ago Meta pushed a Quest update that broke OpenXR compatibility. LOVR app needs to be rebuilt against the newest OpenXR. On nightly builds it is fixed, but not on the stable release.

**Comment by bjornbytes** [comment]
Beat me to it!  I'll be updating the APK on the website soon.

**Comment by armoar334** [comment]
:+1: That's fixed, thanks

**Comment by bjornbytes** [comment]
I released v0.17.1, updated APK is on website.
