### ISSUE TITLE
MacOs vulkansdk out of date

### ISSUE THREAD

**Issue by nensanders** [bjornbytes/lovr#761]
https://github.com/bjornbytes/lovr/blob/26d17fc4029d12a641e575cd713b3f18d7b96170/src/core/gpu_vk.c#L2441

The VK_KHR_synchronization2 is not available in the vulkan sdk used for mac os.

https://github.com/bjornbytes/lovr/blob/26d17fc4029d12a641e575cd713b3f18d7b96170/.github/workflows/build.yml#L110

Was added here https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.2.6
I tried the newer version but it failed loading.

**Comment by bjornbytes** [comment]
I was able to reproduce this with old versions of the SDK, but upgrading to version 1.3.275 of MoltenVK/VulkanSDK fixed the issue.  I pushed a commit that upgrades the version used in the CI builds.

What issue did you have with the newer version of MoltenVK?

**Comment by bjornbytes** [comment]
Closing as complete since the macOS builds have been updated to a version that supports `VK_KHR_synchronization2`.  I also updated the compiling guide to mention the minimum supported MoltenVK version.  If you're still having any issues, let me know!
