### ISSUE TITLE
readback does not works as intended

### ISSUE THREAD

**Issue by blenderman94** [bjornbytes/lovr#766]
i have this code from the gudie but it does not saves anything. plus the readback is also semingly have wrong values in it.

local screenshot = false
local readback
local texture
local pass

function lovr.keypressed(key)
  if key == 'p' then screenshot = true end
end

function lovr.load()
  local width, height = lovr.headset.getDisplayDimensions()

  texture = lovr.graphics.newTexture(width, height, {
    usage = { 'render', 'transfer', 'sample' }
  })

  pass = lovr.graphics.newPass(texture)
end

function lovr.update()
  pass:reset()
  for i = 1, lovr.headset.getViewCount() do
    pass:setViewPose(i, lovr.headset.getViewPose(i))
    pass:setProjection(i, lovr.headset.getViewAngles(i))
  end
  pass:text('hellooo', 0, 1.7, -1, .1)
  lovr.graphics.submit(pass)

  if screenshot and not readback then
    readback = texture:newReadback()
    screenshot = false
  end

  if readback and readback:isComplete() then
    local filename = 'screenshot.png'
    lovr.filesystem.write(filename, readback:getImage():encode())
    print('saved screenshot to ' .. filename)
    readback = nil
  end
end

function lovr.draw(p)
  p:fill(texture)
end

**Comment by blenderman94** [comment]
i was trying to set the bg color to something else but even then it semingly does not shows the correct values

**Comment by blenderman94** [comment]
i read the resulting blob back with blob:getString

**Comment by jmiskovic** [comment]
The example works on my end. Where are you looking for the screenshot file? If you are not aware about how lovr's filesystem works, take a look at the table in [filesystem module documentation](https://lovr.org/docs/lovr.filesystem) and look up the save directory for your OS. The `screenshot.png` should be saved there.

You can also skip `lovr.filesystem`, and directly use Lua's built-in IO functions to save the file yourself to a location of your choice.

**Comment by blenderman94** [comment]
i looked next to the executable and even in the project folder

**Comment by blenderman94** [comment]
maybe its on some other directory then the lovr's folder?

**Comment by jmiskovic** [comment]
Again, take a look at the table in [filesystem module documentation](https://lovr.org/docs/lovr.filesystem), find your OS in that table and check the save dir on disk to find the file. For Windows the saved file should in `%AppData%\LOVR\default\`

**Comment by bjornbytes** [comment]
I posted a response in the other issue where this was posted as well, #765.
