### ISSUE TITLE
There is an error in the last update

### ISSUE THREAD

**Issue by WOLFxxxxxx** [bjornbytes/lovr#774]
![Capture](https://github.com/bjornbytes/lovr/assets/128394802/ba201216-4633-4921-abbc-5cb956d03404)

**Comment by bjornbytes** [comment]
From the screenshot, it looks like you compiled this yourself.  Which commit did you compile?  What CMake options did you use?  You might be missing a Microsoft Visual C Redistributable.

**Comment by WOLFxxxxxx** [comment]
ا
The problem of switching from dev to version v0.17.1 has been solved
