### ISSUE TITLE
ا Why not program a game in c like raylib without using lua

### ISSUE THREAD

**Issue by WOLFxxxxxx** [bjornbytes/lovr#777]
![Screenshot_٢٠٢٤-٠٥-٢٥-١٧-١٢-١٤-٥٣٣_com android chrome-edit](https://github.com/bjornbytes/lovr/assets/128394802/aab01254-e335-4b50-87fd-4bf37fa83815)

**Comment by bjornbytes** [comment]
LÖVR doesn't have an official C API yet.  Reasons:

- It would increase maintenance burden.  The Lua API is challenging enough as it is.
- The internal C API still changes pretty frequently.  The C API will either break a lot or there would need to be work to make things backwards compatible (see previous bullet).
- Designing a C API is very different compared to designing a Lua API.  The existing C API is completely in service of LÖVR's Lua API and isn't as pretty of a C API as I'd want it to be.
- Writing C code in LÖVR isn't as fun when it's part of a public facing C API.  Everything would need to be namespaced, we would no longer be able to throw exceptions, etc.

With that said, you're free to use LÖVR from C and several people have already done this.  It's just not officially supported.

If you want to use C to make a game, there are better frameworks available for that (you mentioned one of them!).

**Comment by WOLFxxxxxx** [comment]
Thank you very much
