### ISSUE TITLE
How to remove membrane from grass

### ISSUE THREAD

**Issue by WOLFxxxxxx** [bjornbytes/lovr#778]
![Capture](https://github.com/bjornbytes/lovr/assets/128394802/369a3d96-d94f-4075-8ded-b561573a3c26)

**Comment by bjornbytes** [comment]
Transparent objects needs to be drawn back-to-front.  The objects in front are getting drawn first and writing to the depth buffer, and the objects behind them are getting drawn later and depth testing against the transparent pixels.

You can put objects into a table with their distance to the camera and sort based on that.

In the future LÖVR may be able to do this automatically.

**Comment by jmiskovic** [comment]
You can achieve a lot with this line at the start of `lovr.draw` function:

`pass:setAlphaToCoverage(true)`

It won't solve all issues with complex overlaps but it should fix the situation in your screenshot. There's a great article that covers a more advanced technique for foliage: [Anti-aliased Alpha Test: The Esoteric Alpha To Coverage](https://bgolus.medium.com/anti-aliased-alpha-test-the-esoteric-alpha-to-coverage-8b177335ae4f)
