### ISSUE TITLE
 The screen is black when running the apk file

### ISSUE THREAD

**Issue by WOLFxxxxxx** [bjornbytes/lovr#782]
![Screenshot_٢٠٢٤-٠٦-٠٦-١٩-٤٦-٤٥-٢٧٢_org lovr app](https://github.com/bjornbytes/lovr/assets/128394802/59cfa183-8000-4ab3-89aa-6277d6cb6a75)

**Comment by bjornbytes** [comment]
LÖVR only officially supports VR headsets on Android.
