### ISSUE TITLE
networking frezzes

### ISSUE THREAD

**Issue by blenderman94** [bjornbytes/lovr#788]
hello im trying to get enet working but it just freezes straight im using your enet example from the documentation.

**Comment by bjornbytes** [comment]
Did you put the client.lua and server.lua code in separate files and run 2 lovr instances?

**Comment by bjornbytes** [comment]
I just tried it and it works okay.  Make sure you copy the client code into client.lua, and the server code into server.lua.  Then start the server with `lovr server.lua` and run the client with `lovr client.lua` and you'll see them connect and send a message between each other.

**Comment by blenderman94** [comment]
yeah but it  just keeps a white screen and do nothing. i tryed even without initializing the lovr part just from lua but its keeps refusing any kind of connection. same on quest 2 also on windows 11

**Comment by bjornbytes** [comment]
Have you gotten 2 lovr instances on the same computer to connect to each other (localhost) successfully, or are you still trying to get that working?  There are a lot of things that can go wrong when trying to connect 2 different computers together, so getting it working locally is a good sanity check.

In what way is it refusing the connection?  Are you getting any errors?  Do you see any of the prints?

**Comment by blenderman94** [comment]
i tryed but both hangs on a white screen.  strangly if i make a c++ server and use python it connect toit work fine between c++ and python  but in lovr   neworking is semingly broken all together im using windiws 11. it basicaly makes it mposible to communicate with lovr from an outside source. the even will always remain a nil so i asume the programs fails to connect. (i let lovr trought my firewal and run is as admin on my pc)
