### ISSUE TITLE
HTTP(S)

### ISSUE THREAD

**Issue by bjornbytes** [bjornbytes/lovr#80]
Would be cool to have HTTP(S) support.  But it would be even cooler if resources could optionally be "Request" objects or URLs, similar to how `Blob` objects work where they can be specified as filenames or Blobs.  Imagine the possibilities:

```
lovr.graphics.newModel('https://example.com/asset.gltf')
```

It's interesting to think about synchronous vs. asynchronous requests: Maybe assets could be loaded asynchronously and just "pop in" once they've loaded.

Currently looking at [mongoose](https://github.com/cesanta/mongoose) as a potential single-file library to use for this.

This belongs in the data module, e.g. `lovr.data.newRequest`.

**Comment by bjornbytes** [comment]
In emscripten we can probably use the browser's native request capabilities?

**Comment by tapir** [comment]
This would be really cool. I'm developing a game for Quest and I've just noticed there are not http clients that work with android out of the box.

**Comment by brainrom** [comment]
Actually, I'm already finished porting luasocket from LOVE2d to LOVR and it works successfully on Oculus Quest 2 and Linux PC. I'll publish PR ASAP.

**Comment by tapir** [comment]
ah nice to hear! does it support http**s** too? I'm not familiar with luasocket.

**Comment by brainrom** [comment]
#387 Ready to test

**Comment by bjornbytes** [comment]
This should be a plugin, at least initially.

**Comment by brainrom** [comment]
[This](https://github.com/brainrom/lovr-luasocket) isn't enough?

**Comment by bjornbytes** [comment]
Yeah I think that's one of the reasons why this can be closed.  People may still be interested in HTTPS too.

**Comment by brainrom** [comment]
This can be achieved by making [LuaSec](https://github.com/brunoos/luasec) as LOVR plugin. Maybe, I'll do it after a while.

**Comment by bjornbytes** [comment]
Update for anyone that stumbles on this issue: HTTPS is now available in [lovr-http](https://github.com/bjornbytes/lovr-http), and is included in LOVR by default.
