### ISSUE TITLE
lövr is not captable to use the internet at all?

### ISSUE THREAD

**Issue by blenderman94** [bjornbytes/lovr#814]
greetings im trying to send a simple string over local on windows for a few months now (7) but lövr semingly is seariusly broken in a terms of ding anything over internet.

what i tryed so far.

used the tutorial for  enet  - never worket at all.
tryed to compilea socket libary - failed
tryed to ask the os to do some wit hos. execute failed.

basicaly what a wanted is to send a string hello from lövr to an other program on the same machine.

can you lease make a proper tutorial not what we have right now or just fix the networking in lövr? 

it will be a lifesaver for my nerves thanks in advance!

**Comment by bjornbytes** [comment]
Thanks for the issue.  I just tried out the sample from the enet tutorial to make sure it works.  Here's what I did:

First, I created a folder named `client`, made a file named `main.lua` in there, and put this code in it:

```lua
local enet = require 'enet'

function lovr.load()
  local host = enet.host_create()
  local server = host:connect('localhost:6789')

  local done = false
  while not done do
    local event = host:service(100)
    if event then
      if event.type == 'connect' then
        print('Connected to', event.peer)
        event.peer:send('hello world')
      elseif event.type == 'receive' then
        print('Got message: ', event.data, event.peer)
        done = true
      end
    end
  end

  server:disconnect()
  host:flush()
end
```

Then, I made a folder named `server`, made a file named `main.lua` in there, and put this code in it:

```lua
local enet = require 'enet'

function lovr.load()
  local host = enet.host_create('localhost:6789')
  while true do
    local event = host:service(100)
    if event and event.type == 'receive' then
      print('Got message: ', event.data, event.peer)
      event.peer:send(event.data)
    end
  end
end
```

I also put a `conf.lua` file in the server folder with this, since the server doesn't need to render anything:

```lua
function lovr.conf(t)
  t.modules.graphics = false
  t.modules.headset = false
  t.window = nil
end
```

Then, I started the server with `lovr .` from the server folder, and ran the client with `lovr .` from the client folder.

The server printed this:

    Got message:    hello world     127.0.0.1:53034

The client printed this:

    Connected to    127.0.0.1:6789
    Got message:    hello world     127.0.0.1:6789

Can you share any more details about what you tried with the enet tutorial and how it failed?  I'd love to improve the documentation, and I could start with the more specific steps I wrote out here, but I'm not sure if it would actually improve things without knowing the problem you're running into.

**Comment by blenderman94** [comment]
im working on solution to use my vr heqadset with virtualy any device. by simulating what steam vr does but without need to have xr on the device what runs the game ( Linux sucks with vr a lot ) rest is confidential.

**Comment by blenderman94** [comment]
this worked for me on pc between 2 lövr instances. but i like  comunicate between my headset and some other programing langues like python or c++  having a painful long hours invested into this one i can get a message out. function send_to_socket(host, port, message)
    -- Escape the message to handle spaces and special characters
    local escaped_message = string.format("%q", message)
    
    -- Construct the command to send the message
    local command = string.format('echo %s | nc %s %d', escaped_message, host, port)
    
    -- Execute the command
    os.execute(command)
end       but i cant get a message in. function listen_on_socket(ip, port)
    -- Construct the `nc` command to listen on the given IP and port
    -- Without the `-k` flag, the listener will stop after one connection
    local command = string.format('nc -l -s %s -p %d', ip, port)

    print(string.format("Listening on %s:%d", ip, port))
    print("The listener will stop after handling one connection.")
    
    -- Execute the command
    local result = os.execute(command)

    -- Check if the command was successful
    if result == 0 then
        result="strange stuff!"
    else
   this is some duck tape cause sadly my server side will be not lövr

**Comment by blenderman94** [comment]
if it helps the program must do 2 things. the client must run  on a quest2 being able to send and receive text to a python program running on a pc. thats all it has to do.  (client is gona use as a wrapper its gona collect inputs and send it to a program) (the python program gonna collect the stuff like input and gona send back some stuff in a text format.)
