### ISSUE TITLE
Logitech MX Ink Input

### ISSUE THREAD

**Issue by bjornbytes** [bjornbytes/lovr#815]
Logitech MX Ink is a stylus peripheral for Quest headsets.  MX Ink will already kind of work with LÖVR since it's able to emulate a controller, but dedicated support would be nice to expose things like pressure sensitivity.

The OpenXR extension hasn't been published yet, but Quest exposes the unofficial [XR_LOGITECH_mx_ink_stylus_interaction](https://logitech.github.io/mxink/OpenXR.html) extension.

**Comment by bjornbytes** [comment]
Couple design questions for the Lua API:

- The pen can be held in the left or right hand, and reports actions on a specific hand.  Would we need to have `pen/left` and `pen/right` devices, or is just a `pen` device okay?  Is it important to know which hand the pen is assigned to?
- The front/back buttons support double click events.  Normally people could just detect this in Lua, but the double click time threshold can be customized in the Quest settings, so there is benefit to exposing this.  Maybe `lovr.headset.wasPressed('pen/front/doubleclick')`?

API sketch:

- New `Device`:
  - `pen`
    - (I'm hoping that we don't need to expose separate sub-devices like `pen/grip`, `pen/point`, `pen/tip`, etc. and this can just be the tip pose.  Maybe we could map the grip pose onto one of the hand devices if needed.  I think all the different pose paths were added because OpenXR requires them for hands).
- New `DeviceButton` for `pen`:
  - `tip`
  - `front` (maybe also extra doubleclick sub-button)
  - `middle`
  - `back` (maybe also extra doubleclick sub-button)
  - `docked` (kinda weird)
- New `DeviceAxis`'s for `pen`:
  - `tip`
  - `middle`

This would be pretty specific to the MX Ink though, and could cause problems if we want to add support for other pens in the future.  An alternative, more abstract design for the buttons might look like this:

- `tip`
- `touchpad`, mapped to the pressure sensitive middle button.  This reuses an existing button enum and would work for any pen with a pressure sensitive button, even if it's not the "middle" one.
- `a` for the front button
- `b` for the back button
- Maybe `x` and `y` for the double clicks?  ehh...

It's pretty arbitrary and brittle, but LÖVR could try to follow a consistent system like this for all pen-like devices.

**Comment by wasokeli** [comment]
the Quest Pro controllers can be flipped upside-down to act as a stylus. i think they have pressure sensitivity too. so the LÖVR API should take that into account
