### ISSUE TITLE
Errors when exporting win11

### ISSUE THREAD

**Issue by WOLFxxxxxx** [bjornbytes/lovr#823]
![Screenshot (4)](https://github.com/user-attachments/assets/cd16533d-edac-40c2-a94e-b511074af70f)

**Comment by bjornbytes** [comment]
This means you don't have clang installed.  But last time I tried tup on windows there were some issues.  I'd try using CMake, following the steps in [the Compiling guide](https://lovr.org/docs/Compiling#windows).  (If CMake complains that you don't have a compiler, make sure you install at least the Visual Studio build tools first).
