### ISSUE TITLE
Possibility for non-vr usage?

### ISSUE THREAD

**Issue by LavenderTheGreat** [bjornbytes/lovr#95]
Maybe with some kind of manual camera control? Would be pretty neat.

**Comment by bjornbytes** [comment]
Hi!  LÖVR comes with manual camera controls that are used whenever a headset isn't connected.  But you can also disable VR completely by setting `t.modules.headset` to `false` in conf.lua.  You might also find [`lovr-keyboard`](https://github.com/bjornbytes/lovr-keyboard) and [`lovr-mouse`](https://github.com/bjornbytes/lovr-mouse) useful.  There is also an answer to this on [the FAQ](https://lovr.org/docs/FAQ) that might be useful.
