### ISSUE TITLE
Does not run on my computer.

### ISSUE THREAD

**Issue by ShoesForClues** [bjornbytes/lovr#96]
Tried to run it on my computer, didn't even open, no window or anything. Tried compatibility mode for windows 7 & 8, as well as running in administrator. I also tested both 32 and 64 bit releases. I'd assume it should work without the need of a VR headset connected as the FAQ claims it would run in a simulated VR window. 

Here's my specs:
Processor: i5 3230-M 2.6GHz
RAM: 8GB
GPU: Intel HD Graphics 4000
OS: Windows 10 Home x64

**Comment by bjornbytes** [comment]
Hey, thanks for opening this.  It would be interesting to figure out if it's related to the executable itself or if it's something related to rendering (there hasn't been much testing on Intel GPUs).  Some questions that might help narrow things down:

- Does `lovr --version` print anything out when you run that from cmd.exe?  If it does, then at least the executable is working properly and it's getting into the C main function.
- If you make a project (folder with main.lua) and put some print statements in there, do those show up?  In that case, the framework is booting up properly and it's probably something wrong with the graphics module.

**Comment by ShoesForClues** [comment]
running "lovr --version" did not output anything, neither did printing from main.lua in the function lovr.load() I'm assuming this does have to do with openVR because it was said it wasn't supported for intel graphics or something.

https://github.com/ValveSoftware/openvr/issues/451

**Comment by bjornbytes** [comment]
Hmm, so someone else has run into this same issue on a GTX 660.  --version should print stuff way before any of the headset code starts to initialize, so I'm wondering if it's something wrong with the way the executable is packaged (Visual C++ Redistributables?) or something.  Going to keep investigating...
